{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.4.1-Resharped-1.9.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.1-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.1-Resharped-1.9.65.jar",
          "size": 9217904,
          "sha512": "b01f9bcd419effcb3974be3629410f02404c96fd8dd6dd81e325a93d90a22cc814b595778e1cd157fcc6f2a8aebb652bd38f9fbc00caa5298e105ffedcb29702",
          "sha256": "2d9a74440fb1b1c18dad74401f56bfe0eaa0bfcfbf4450be17f0fa847edcf162",
          "sha1": "6f7148742137f0134d975e9353032a2a0e767a47",
          "md5": "72f7f5e67cfc9b0d746c0aa6cf0b67a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.1-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.1-Resharped-1.9.65.jar",
          "size": 9217904,
          "sha512": "b01f9bcd419effcb3974be3629410f02404c96fd8dd6dd81e325a93d90a22cc814b595778e1cd157fcc6f2a8aebb652bd38f9fbc00caa5298e105ffedcb29702",
          "sha256": "2d9a74440fb1b1c18dad74401f56bfe0eaa0bfcfbf4450be17f0fa847edcf162",
          "sha1": "6f7148742137f0134d975e9353032a2a0e767a47",
          "md5": "72f7f5e67cfc9b0d746c0aa6cf0b67a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.1-Resharped-1.9.65-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.1-Resharped-1.9.65-sources.jar",
          "size": 3555573,
          "sha512": "edb5cf7d34e5221863e520717b41b7ae87a4bf43d80d96f6b8fa2ad9c8644387ebcf109bb3f27a07f944ce76be902207ee8a0bd0e703f2810fcc71f49a8845d0",
          "sha256": "3631b02d1b8e732064b6d2d35bf94005784d1af9df5a8c6e116cf4dc1191a65e",
          "sha1": "2f4131d198f93d146e76b600a1c226640f467141",
          "md5": "b053ef9ede56b561a8299dde460d66c5"
        }
      ]
    }
  ]
}
