{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.20.1-1.0.1-Resharped-1.7.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.0.1-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.20.1-1.0.1-Resharped-1.7.55.jar",
          "size": 5838129,
          "sha512": "cc2fffc835195042ac1b30ba86e1293c63ba5de0c2e51fc95c48c20fd5bda74fb4a37df525ef20ab38be8c2f72291be077141c90284b9fe13f6f50297ae69218",
          "sha256": "73fceb5409a14c722c552e643bf510fec4ec1448aa046bc5357ff60c876db4e3",
          "sha1": "4cafeff8ab99c0e8122d695e7f77b7b6b891fd31",
          "md5": "51b73d2a74b3e2fa3995703764e0f2ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "attributes",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "emi-580555",
          "version": {
            "requires": "6420944"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6815736"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6608232"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.105"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180902"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "5984629"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-83-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.0.1-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.20.1-1.0.1-Resharped-1.7.55.jar",
          "size": 5838129,
          "sha512": "cc2fffc835195042ac1b30ba86e1293c63ba5de0c2e51fc95c48c20fd5bda74fb4a37df525ef20ab38be8c2f72291be077141c90284b9fe13f6f50297ae69218",
          "sha256": "73fceb5409a14c722c552e643bf510fec4ec1448aa046bc5357ff60c876db4e3",
          "sha1": "4cafeff8ab99c0e8122d695e7f77b7b6b891fd31",
          "md5": "51b73d2a74b3e2fa3995703764e0f2ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.0.1-Resharped-1.7.55-sources.jar",
          "url": "slashblade-refabricated-1.20.1-1.0.1-Resharped-1.7.55-sources.jar",
          "size": 3645967,
          "sha512": "7fd4298c15f4e8adbe82939f7e1eb1bfc273e50fe4383cf81af6c371ec3270a7952273400608d72e8c94d6e4409cdcf06bccde62ac4f8a64988dad3ac004ff56",
          "sha256": "11843819a2aa63cd8a6d5d582574e2f4debb4c1640d1a1a4bbaaada85ec91f80",
          "sha1": "f44c761667920e69171d75f9601383cc20adfe42",
          "md5": "ebc40fcf96cd3ba955d542ff1f62bfde"
        }
      ]
    }
  ]
}
