{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.2.0-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.2.0-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.2.0-Resharped-1.8.61.jar",
          "size": 7135419,
          "sha512": "8214977240230464e380b44324ef2fd72b2d09b7c443609d9b6fd151bfdcafe99f2696c26d2bfa4282291800f02f47d1d4b748998e46a8629d7771da9bcdb6fb",
          "sha256": "6341d3b788d4c8fe8dd5af45303210ff1dd894bfe94eeb65c883672ca7d4da2d",
          "sha1": "f298e3243f5f7a094db029617e175502832872b4",
          "md5": "fad924a56d66bca954b310b7d86337a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.2.0-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.2.0-Resharped-1.8.61.jar",
          "size": 7135419,
          "sha512": "8214977240230464e380b44324ef2fd72b2d09b7c443609d9b6fd151bfdcafe99f2696c26d2bfa4282291800f02f47d1d4b748998e46a8629d7771da9bcdb6fb",
          "sha256": "6341d3b788d4c8fe8dd5af45303210ff1dd894bfe94eeb65c883672ca7d4da2d",
          "sha1": "f298e3243f5f7a094db029617e175502832872b4",
          "md5": "fad924a56d66bca954b310b7d86337a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.2.0-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.2.0-Resharped-1.8.61-sources.jar",
          "size": 3555841,
          "sha512": "7388e6dce87b62cb643e54fc457a761c592f0c0a9f02ed920f98943727da5e1090a17ed7d4856b83843e48953f44f32258a5670c74a7dee57c01cf317e7c5950",
          "sha256": "4cb0ae8c22a9a592fceb9ea717800671ebe47303ae9e2b87a39c77d45fa9fe0d",
          "sha1": "90f5561d032fdd1d20b0f75659914c59a4513382",
          "md5": "924ab841d68883646aefa03099312f24"
        }
      ]
    }
  ]
}
