{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.2-Resharped-1.8.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.2-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.2-Resharped-1.8.57.jar",
          "size": 7133571,
          "sha512": "3233884a83ee99889a5b549f24f7614cb222c9562183a99779d4dccabb3b4a803600059d1e31d1d4eed8cba330e53cc94c967faa99cc9d539b5a5afd262acf6b",
          "sha256": "4dd8be6205e747d232a0d8e10bf55d4e28d99865940eff63f4d6cfe66ba0360b",
          "sha1": "b2016b578f4cfe7d00d8e9002a39812ecb8f0e79",
          "md5": "f25a5bb8d24e911d865bbc4818e1a8f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.2-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.2-Resharped-1.8.57.jar",
          "size": 7133571,
          "sha512": "3233884a83ee99889a5b549f24f7614cb222c9562183a99779d4dccabb3b4a803600059d1e31d1d4eed8cba330e53cc94c967faa99cc9d539b5a5afd262acf6b",
          "sha256": "4dd8be6205e747d232a0d8e10bf55d4e28d99865940eff63f4d6cfe66ba0360b",
          "sha1": "b2016b578f4cfe7d00d8e9002a39812ecb8f0e79",
          "md5": "f25a5bb8d24e911d865bbc4818e1a8f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.2-Resharped-1.8.57-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.2-Resharped-1.8.57-sources.jar",
          "size": 3555418,
          "sha512": "ad3202016677566f3024c3263d51bd0fb976356f348bfb6bed3e48d6f83ebfe1981fbe2c200a8a62cd77481f7442024b67b4a8f0757a315c807876ce0649b684",
          "sha256": "c5214514cf76df2e8fc5b7d0fdf505875f5456cd42d75747b42f4cf7cf830bce",
          "sha1": "946de352864c80ef353833cbddb074d39f54a12a",
          "md5": "b9c7520e215ab7f7c0dd136649ec6cef"
        }
      ]
    }
  ]
}
