{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "client_extensions",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "client_extensions-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "client_extensions-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 689091,
          "sha512": "584be7d0a89fa0e4f9fff71d3dfcd694c40f6bf781a9be785a4802a67e1ef92c89d9504330a9f063e4e12b0611349e5851d38bef5608453af513a0808cea664f",
          "sha256": "f85f1aa742089cd7298ff6ab3142ac364ad3911ae77383df53a47cecc6ebf4ee",
          "sha1": "a601567d7e42e1343760ef3d72327e970bbaae55",
          "md5": "dd26608face6c96634a6508b03469ee2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "client_extensions-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "client_extensions-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 689091,
          "sha512": "584be7d0a89fa0e4f9fff71d3dfcd694c40f6bf781a9be785a4802a67e1ef92c89d9504330a9f063e4e12b0611349e5851d38bef5608453af513a0808cea664f",
          "sha256": "f85f1aa742089cd7298ff6ab3142ac364ad3911ae77383df53a47cecc6ebf4ee",
          "sha1": "a601567d7e42e1343760ef3d72327e970bbaae55",
          "md5": "dd26608face6c96634a6508b03469ee2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client_extensions-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "client_extensions-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 9193,
          "sha512": "486521fe173253f2dd14adffc7b99a3daadac7fba92b3b41e29f179ad49704fdb68618b6dcf01bccbeae44d97b6ffc80928b065b895633beb3894b3751ae4d91",
          "sha256": "2d23f85b05cb33ba7c1f746b4ac472f1ef4de98f294072d2c601a3a27fcea73d",
          "sha1": "78dd3cef31da52e69acb2770651629df71ff4272",
          "md5": "9784756a177945a984f78280b7a10591"
        }
      ]
    }
  ]
}
