{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.4+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.22.1.316"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "size": 6720344,
          "sha512": "806c8b685760fb869e95ee013231633ec80146e7e9bb1eb9dc5f81d402c79552f0ec6b15d3eab6d2661b2677e4915b649d8a9ee776bf4d229be4e4b73e628fcb",
          "sha256": "a9b5a2b0c8a6b318551ce8724cd8040bbcf0e34428eafa285aefe6562651f358",
          "sha1": "42272b4843802c1de20beebe8055b74d60218077",
          "md5": "7c95ccaefee7b1a42ac6ec4e4058eb53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.1.3-Resharped-1.8.60"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "size": 6720344,
          "sha512": "806c8b685760fb869e95ee013231633ec80146e7e9bb1eb9dc5f81d402c79552f0ec6b15d3eab6d2661b2677e4915b649d8a9ee776bf4d229be4e4b73e628fcb",
          "sha256": "a9b5a2b0c8a6b318551ce8724cd8040bbcf0e34428eafa285aefe6562651f358",
          "sha1": "42272b4843802c1de20beebe8055b74d60218077",
          "md5": "7c95ccaefee7b1a42ac6ec4e4058eb53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.21.1-sources.jar",
          "size": 3803067,
          "sha512": "fc999b0eb47be1c1c392fa531e76175e91a0a51751e762abe8fa4e1ea08a68b20756acd7463fb36e0021b7cfc4bfe154fcd1df05d397d81749383d847a352323",
          "sha256": "5cb52626a3f1a70775240909f17f70de2e44d4462fe086c33c0c3ff9fd83f9b9",
          "sha1": "63fff45f916ad53356b9151bba254fdac0c2a849",
          "md5": "bd69e05f733c989e89dacf5d51aedbb9"
        }
      ]
    }
  ]
}
