{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.4+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.22.1.316"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "size": 6720203,
          "sha512": "dd9736874b8be3a898b5a8e037e630c4339588cce84854f3d9e493cd14ceb23bb4aeca505510685809d29ded71bc9fff1ed16dcf1a7cf3633c44e8e855996bb8",
          "sha256": "40337a25ec994c0c3b41872df1485b45a0b5c884c6166c4c195a2ac6610396ac",
          "sha1": "47916292dddfdb221824033aa38050b61a1d7f1e",
          "md5": "19df4ce25abb15a812d506490565105b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.1.3-Resharped-1.8.60"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.21.1.jar",
          "size": 6720203,
          "sha512": "dd9736874b8be3a898b5a8e037e630c4339588cce84854f3d9e493cd14ceb23bb4aeca505510685809d29ded71bc9fff1ed16dcf1a7cf3633c44e8e855996bb8",
          "sha256": "40337a25ec994c0c3b41872df1485b45a0b5c884c6166c4c195a2ac6610396ac",
          "sha1": "47916292dddfdb221824033aa38050b61a1d7f1e",
          "md5": "19df4ce25abb15a812d506490565105b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.21.1-sources.jar",
          "size": 3803028,
          "sha512": "03109bbf26b3e7224252265aa3fe2775c957c6f1095db989f34ea2b68e66f94ca6fe9fb6ef3f8987f8e4658fc3406913f5b73b423ddf3cf579b15cd97c4b75b7",
          "sha256": "d1a5e1fb29048d4cd2352247f755933ef1f922314c288b8d4f0943d3a1aca659",
          "sha1": "d7c1be7971d6914a3c3aacbeddfbc170c03cd49a",
          "md5": "d251713fd63cc00edf7cfb401e92a664"
        }
      ]
    }
  ]
}
