{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.3.5-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "size": 8523647,
          "sha512": "a7178fd9c425dd49d86ce6e23912835d1b4fd046b7ea53467245678e3f0749f4e3a013d478948ac09cb4b444530f518c1d721b8f5aedcb6e4acd8199d7706dbb",
          "sha256": "dcae129850679d3c916f78be466691766edf2592a9676391db3848929f6e588b",
          "sha1": "7d4c4ffe07bba9edb9eeb71137e2f8d36dda87fd",
          "md5": "d7d388ce8a3d13126202791622e9fca2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "size": 8523647,
          "sha512": "a7178fd9c425dd49d86ce6e23912835d1b4fd046b7ea53467245678e3f0749f4e3a013d478948ac09cb4b444530f518c1d721b8f5aedcb6e4acd8199d7706dbb",
          "sha256": "dcae129850679d3c916f78be466691766edf2592a9676391db3848929f6e588b",
          "sha1": "7d4c4ffe07bba9edb9eeb71137e2f8d36dda87fd",
          "md5": "d7d388ce8a3d13126202791622e9fca2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61-sources.jar",
          "size": 3556484,
          "sha512": "a42facc7dc73717e6be22917fcda74ee1354aa34625bc39cf74ef6c3e860b8b9fd3addd3bf9172d232c64397babc4c416a44e7eee1fa49fdc4acf67e0ab72bbc",
          "sha256": "0c4513f48a4b7c24d74e9dfc170ffd6e163ecb105f4ba58975456e9df510a6af",
          "sha1": "289a6dd998711a040d07e89153c2c786c1e5e3d2",
          "md5": "99810dac0cdfdaeb3db244150e3de886"
        }
      ]
    }
  ]
}
