{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.3.5-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "size": 9207912,
          "sha512": "28dc48ae8b8bf5106a3103da5092539a37d4427b6d282de1fe2d66911da82153e64b56977474c8ad3e30515610ef418b26726f9c28d2e00619366616175eb0fd",
          "sha256": "ae095f5f4c27ed093d7b8a08cff3a5f45d8c099f2c81f5d7458a61426d636d8c",
          "sha1": "717c546cbd396f2d2976a62da8c6daf18ac30987",
          "md5": "556e1ccc8cbb49befe39b083c31d2d48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "size": 9207912,
          "sha512": "28dc48ae8b8bf5106a3103da5092539a37d4427b6d282de1fe2d66911da82153e64b56977474c8ad3e30515610ef418b26726f9c28d2e00619366616175eb0fd",
          "sha256": "ae095f5f4c27ed093d7b8a08cff3a5f45d8c099f2c81f5d7458a61426d636d8c",
          "sha1": "717c546cbd396f2d2976a62da8c6daf18ac30987",
          "md5": "556e1ccc8cbb49befe39b083c31d2d48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61-sources.jar",
          "size": 3556484,
          "sha512": "87b5af8c1c28dd0284005d838530988fa0438df0baa2d72c27a24ff078da7f8d00dddeb4edc17939fcd9c57131a93077470b11cea51f2362e973eef619ce4e84",
          "sha256": "01f5a52c82816bb12f2033f62fe013ac04788965026a2b2f9668cb206feec5a8",
          "sha1": "f50536b9c023dd1086f64fb7163e5cdc1a2e613c",
          "md5": "1b35d8a2f745e21322690d9f046c7eec"
        }
      ]
    }
  ]
}
