{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.3.5-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "size": 8523710,
          "sha512": "19804e725bc14687953eb8f150cb1f5417f44b6a9ce3a3103b73ccc83b16616712170134927a01e1b161ea9abcdf6dc20bb9faac99bef1d2791486b4c53f8083",
          "sha256": "b3c2d9acfbead52e2967af9da99e1a0bece2cee5b1c41cd65e33637a97e7bafe",
          "sha1": "039ee9f1f9b7f017f6ca06bd2a66af7c19597015",
          "md5": "1785c7c7a6252396b7cc4301f5dbd915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61.jar",
          "size": 8523710,
          "sha512": "19804e725bc14687953eb8f150cb1f5417f44b6a9ce3a3103b73ccc83b16616712170134927a01e1b161ea9abcdf6dc20bb9faac99bef1d2791486b4c53f8083",
          "sha256": "b3c2d9acfbead52e2967af9da99e1a0bece2cee5b1c41cd65e33637a97e7bafe",
          "sha1": "039ee9f1f9b7f017f6ca06bd2a66af7c19597015",
          "md5": "1785c7c7a6252396b7cc4301f5dbd915"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.5-Resharped-1.8.61-sources.jar",
          "size": 3556484,
          "sha512": "0d656c0ecb832c8f6aa7cff8da3abc75f76ff67c18cda080d20b5d5350f373508a2bccc458a9372e4746cf74a46d075e20fc249a4842263040b8dbf1770846c0",
          "sha256": "5001ffc64f4a07ff9bba68575d7cf1d579979b21f20206343169f1ed057567ba",
          "sha1": "750c01879480843af89d346530d0061e9118e395",
          "md5": "e52c4adf94985dc38e8aab0022284dfd"
        }
      ]
    }
  ]
}
