{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.4+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.4+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.4+mc1.20.1.jar",
          "size": 52633168,
          "sha512": "4324dee1441c9f2070cc5c057e30f4f3e70f3bd3a2adfc841cefd5c8cdc45951df891551b2a47c4ed332c3bcd1804f3416a8b37803e0837029f543139165ea3f",
          "sha256": "17c66c37fea56a33ca8ebe09979ddcf4b03d524dd13892ce7fb2e16b26bae2a9",
          "sha1": "4f60f98daaed1c72069b55de2b3f0a64d3ca315d",
          "md5": "d71600238638d1571ff5b39e4a80ed91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.0-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.4+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.4+mc1.20.1.jar",
          "size": 52633168,
          "sha512": "4324dee1441c9f2070cc5c057e30f4f3e70f3bd3a2adfc841cefd5c8cdc45951df891551b2a47c4ed332c3bcd1804f3416a8b37803e0837029f543139165ea3f",
          "sha256": "17c66c37fea56a33ca8ebe09979ddcf4b03d524dd13892ce7fb2e16b26bae2a9",
          "sha1": "4f60f98daaed1c72069b55de2b3f0a64d3ca315d",
          "md5": "d71600238638d1571ff5b39e4a80ed91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.4+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.4+mc1.20.1-sources.jar",
          "size": 50197192,
          "sha512": "e1c1573fa16f20048aa9bb85f4a4c39e0aac3ff9493f0224a7f3f67d08077e8c3084e8d0a5bda282329a9c63eca0124eacbcd912b32dc5be60dbf4278e8062d1",
          "sha256": "cef2f02b8f14f2a5345e3339d2e0cb263a874bb75a7ef51967eba2ed0f4fada9",
          "sha1": "34373872d23e71bf8506977c33ef1deedd51bfcc",
          "md5": "aa10819b58b5b1f71ab5f722f04c0694"
        }
      ]
    }
  ]
}
