{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "registry",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "registry-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "registry-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 704760,
          "sha512": "436bd7eda7a359e7f4b8e636aff536d542e062bff401488236031e2275c14d423527ff108d0d33927b257a191271098f8bb783484aff3ad96f0b5fb098db6939",
          "sha256": "4aa91366e63a8a80b0a37366b763bb65c52e5d672ccef69b1fbe386d956cfd2d",
          "sha1": "19708466eafa40572560adacbaf9da30b88aaa23",
          "md5": "f2bc199ae0bf586614d58322e440b417"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "registry-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "registry-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 704760,
          "sha512": "436bd7eda7a359e7f4b8e636aff536d542e062bff401488236031e2275c14d423527ff108d0d33927b257a191271098f8bb783484aff3ad96f0b5fb098db6939",
          "sha256": "4aa91366e63a8a80b0a37366b763bb65c52e5d672ccef69b1fbe386d956cfd2d",
          "sha1": "19708466eafa40572560adacbaf9da30b88aaa23",
          "md5": "f2bc199ae0bf586614d58322e440b417"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "registry-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "registry-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 19935,
          "sha512": "8fdbfb64fdb3fa9bd549ace731d2e3226a5a35c6fcbad5cc597bc01e629b84c18d8ff683ccf6852f4d2269e10f17f9c993d932c28a1148f3037732e027adf08b",
          "sha256": "bfb16d59eaf82a3b664ba906a0c325b9aee12da38175cbff38eff3d0cfdf4fe7",
          "sha1": "4846f2eca8ca08c5dbfed2cb46c76ff570b81593",
          "md5": "e006204e18192c6e2d76baef237200f5"
        }
      ]
    }
  ]
}
