{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "touhoulittlemaid-fabric-1.21.1",
    "version": "0.4.0-neo1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.21.1-0.4.0-neo1.4.5.jar",
          "url": "touhoulittlemaid-fabric-1.21.1-0.4.0-neo1.4.5.jar",
          "size": 24621420,
          "sha512": "5ad3f98955a5bf008edc2f3b87f892fd65e226ce9b84779da6e47ca83da47bae09f745d12acb558436a1099b963607a5235b7a3a658d1ae757992246e5a863c7",
          "sha256": "f282afa684998a7a76a645394e08eb6d56c02bbfb4c86f936301cc2b8bec81c9",
          "sha1": "c60c4044a9bbf14471bf67ad6246c1f478e59519",
          "md5": "a9b677a9d863f4fdcb21ae814f7dded4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.4+1.21.1"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "org.gagravarr",
          "module": "vorbis-java-core",
          "version": {
            "requires": "0.8"
          }
        },
        {
          "group": "io.github.jaredmdobson",
          "module": "concentus",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "19.22.1.316-fabric"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "15.10.1+fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "cyberanner-ironchest",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carry-on",
          "version": {
            "requires": "2.2.2-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patchouli",
          "version": {
            "requires": "1.21-87-fabric"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.4+kotlin.2.2.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "libipn",
          "version": {
            "requires": "fabric-1.21-6.5.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "inventory-profiles-next",
          "version": {
            "requires": "fabric-1.21.1-2.1.8"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "immersive_melodies",
          "module": "immersive_melodies-fabric",
          "version": {
            "requires": "0.6.2+1.21.1"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Fabric-1.21.1",
          "version": {
            "requires": "1.0.61"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "improved-mobs",
          "version": {
            "requires": "1.21.1-1.14.2-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tenshilib",
          "version": {
            "requires": "1.21.1-2.1.1-fabric"
          }
        },
        {
          "group": "libs",
          "module": "TACZ-Refabricated",
          "version": {
            "requires": "1.21.1-0.0.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patpat",
          "version": {
            "requires": "1.2.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "proxlib",
          "version": {
            "requires": "0.2.4+1.21"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.0.1-Resharped-1.7.55"
          }
        },
        {
          "group": "io.github.cottonmc",
          "module": "LibGui",
          "version": {
            "requires": "11.1.0+1.21"
          }
        },
        {
          "group": "me.zeroeightsix",
          "module": "fiber",
          "version": {
            "requires": "0.23.0-SNAPSHOT"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-minimap",
          "version": {
            "requires": "25.2.10_Fabric_1.21"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-world-map",
          "version": {
            "requires": "1.39.12_Fabric_1.21"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.21.1-0.4.0-neo1.4.5.jar",
          "url": "touhoulittlemaid-fabric-1.21.1-0.4.0-neo1.4.5.jar",
          "size": 24621420,
          "sha512": "5ad3f98955a5bf008edc2f3b87f892fd65e226ce9b84779da6e47ca83da47bae09f745d12acb558436a1099b963607a5235b7a3a658d1ae757992246e5a863c7",
          "sha256": "f282afa684998a7a76a645394e08eb6d56c02bbfb4c86f936301cc2b8bec81c9",
          "sha1": "c60c4044a9bbf14471bf67ad6246c1f478e59519",
          "md5": "a9b677a9d863f4fdcb21ae814f7dded4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.21.1-0.4.0-neo1.4.5-sources.jar",
          "url": "touhoulittlemaid-fabric-1.21.1-0.4.0-neo1.4.5-sources.jar",
          "size": 20266855,
          "sha512": "8f2d3f2036bec1c7cdb8cbe42a422c728f65011293a6b1d8cb2b2aa3867a1866ff77d0729c576d8878dbb2f97c63cc03304049bc8a910c550512203b0de3edac",
          "sha256": "e7e6079a3d309fb2c475bcf1cdc714eac528927d3f0dc576e9461a812ecd3471",
          "sha1": "07ceac72029b8117aa25ceada475b00a02a13c4f",
          "md5": "4a243d884b34d3e5831cc7d60d1e4eed"
        }
      ]
    }
  ]
}
