{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.3.3-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.3-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.3-Resharped-1.8.61.jar",
          "size": 8548413,
          "sha512": "dcf94ffcbb48c4cee1b50a478c1a3ae42e7058ecbfedf7aeb1558daea4d441dc47b949d0b99323f303cedf16d925311787b24c7bbb70dc1227a401ea370f89ee",
          "sha256": "dec20121d9cfb1ceb8624af4afa57a28dc21f7f0c847e08df52b36e089bc1752",
          "sha1": "59e100ceaaf3debf16080fd3365370093a9896f2",
          "md5": "d0564ecf9f32678e3ed1782e010604af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.3-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.3-Resharped-1.8.61.jar",
          "size": 8548413,
          "sha512": "dcf94ffcbb48c4cee1b50a478c1a3ae42e7058ecbfedf7aeb1558daea4d441dc47b949d0b99323f303cedf16d925311787b24c7bbb70dc1227a401ea370f89ee",
          "sha256": "dec20121d9cfb1ceb8624af4afa57a28dc21f7f0c847e08df52b36e089bc1752",
          "sha1": "59e100ceaaf3debf16080fd3365370093a9896f2",
          "md5": "d0564ecf9f32678e3ed1782e010604af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.3-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.3-Resharped-1.8.61-sources.jar",
          "size": 3556327,
          "sha512": "f95498c8617e6e697fced81350d8849ed592bfc757029808882f77289a6680ab03bc066b6cbcfabd913afe22524fef2e8da222af950216275a6bbbba76981a8e",
          "sha256": "34c6f17898329b864d2110bf33d59523b5b2c63f3f26d3fbf14019a894419978",
          "sha1": "56fd882ef2fd66142605051bf73459b6485205db",
          "md5": "2ee64ca567bab831c92243028ecc8c1a"
        }
      ]
    }
  ]
}
