{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.3.0+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.3.0+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.3.0+mc1.20.1.jar",
          "size": 52633265,
          "sha512": "30db829c2df4f78598512e1fa07439b61c29fad4af7faf0b2c805ebaa937095f794828acff3f4442e62332fc96ba21e8b7162e59e47241206bcc51ddc564206e",
          "sha256": "bb8210c38e19085a9c7fd90450e99e21bc205c88298151f77b1e24c20fdec71c",
          "sha1": "6d7d679ad29f008c59d98a18c0da50f12ccf81db",
          "md5": "c57da15cab632664a824361fd1bb4f8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.4.0-Resharped-1.9.65"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.3.0+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.3.0+mc1.20.1.jar",
          "size": 52633265,
          "sha512": "30db829c2df4f78598512e1fa07439b61c29fad4af7faf0b2c805ebaa937095f794828acff3f4442e62332fc96ba21e8b7162e59e47241206bcc51ddc564206e",
          "sha256": "bb8210c38e19085a9c7fd90450e99e21bc205c88298151f77b1e24c20fdec71c",
          "sha1": "6d7d679ad29f008c59d98a18c0da50f12ccf81db",
          "md5": "c57da15cab632664a824361fd1bb4f8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.3.0+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.3.0+mc1.20.1-sources.jar",
          "size": 50197524,
          "sha512": "7b1393d2b9fccbbe0770b54aa07089aba8b5258f62317500f632da0570d5c192f49d8e1892affe8a8d96f7ec80110c35a58962e16f136b57d8ffdd7362c59700",
          "sha256": "d34b7af69fb473559d87b9ca6ce275a943786692756b90449b4a020a575afa73",
          "sha1": "0f245465d528dc2198c42242c6ab56fde427af21",
          "md5": "c04ad434465723dbdf78442cbd330c1f"
        }
      ]
    }
  ]
}
