{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "base",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "item_abilities",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gui_utils",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "config",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "loot",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "base-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "base-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 941119,
          "sha512": "5e1606c532a487c313ac27ce13508789acf2bd18fbbed0696207fa37777379592507ab731b75688a97004bb8f52194f368edbf0000ff03b8a76d1c1243f57eb3",
          "sha256": "c690f8f6c020b0f9335c2499bd12edd4b58897d4c62ea748ff3d74ca1b88ec7d",
          "sha1": "61c1ecefcd908ce407e30cbe8b181697ad7d1a8a",
          "md5": "c5d983500b2a0968d4acd0a852b1476c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "item_abilities",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gui_utils",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "config",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "loot",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "base-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 941119,
          "sha512": "5e1606c532a487c313ac27ce13508789acf2bd18fbbed0696207fa37777379592507ab731b75688a97004bb8f52194f368edbf0000ff03b8a76d1c1243f57eb3",
          "sha256": "c690f8f6c020b0f9335c2499bd12edd4b58897d4c62ea748ff3d74ca1b88ec7d",
          "sha1": "61c1ecefcd908ce407e30cbe8b181697ad7d1a8a",
          "md5": "c5d983500b2a0968d4acd0a852b1476c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "base-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 146033,
          "sha512": "010eaea003b571932b56ce48e78a62d0d4019792dde3fc3dfbeec3d6e3c240c55b8b0c72fa338c2699bfc12502575d5199a38dafd12e1596886526ff92c3c160",
          "sha256": "7b639aad318ea830aa1cc37d66410443c43eea249e15417eeefc8fb522ff8a1e",
          "sha1": "baa020b6cd9ce4ac6cd662f9fdc8b87ada10a8b1",
          "md5": "fa09e7b647a1cf80ee991e217c6e302c"
        }
      ]
    }
  ]
}
