{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.4+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.4+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.4+mc1.21.1.jar",
          "size": 50855505,
          "sha512": "7f56744caab55abcad454e2ec2eaeb8bcba10c4622868b429ddd76b0a3fd5ed4934d6eebbe7cad0eb854c27108f03644efaae045b65fa8a5b8a8b7f0d7d69f73",
          "sha256": "5fc18b588a229a330e722c62480bccc4b52226600fa6b6751e0b76e402d4a96a",
          "sha1": "5f24cee8b060bcba0c113251289879febe66b2bd",
          "md5": "f3a09fc53806d291b6214438e9b1c0b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.2-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.4+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.4+mc1.21.1.jar",
          "size": 50855505,
          "sha512": "7f56744caab55abcad454e2ec2eaeb8bcba10c4622868b429ddd76b0a3fd5ed4934d6eebbe7cad0eb854c27108f03644efaae045b65fa8a5b8a8b7f0d7d69f73",
          "sha256": "5fc18b588a229a330e722c62480bccc4b52226600fa6b6751e0b76e402d4a96a",
          "sha1": "5f24cee8b060bcba0c113251289879febe66b2bd",
          "md5": "f3a09fc53806d291b6214438e9b1c0b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.4+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.4+mc1.21.1-sources.jar",
          "size": 50564833,
          "sha512": "9da88e9660e842c98ca869fdeab9d068d96b42ca46e6bdf9e8a6796d01a751959940a9278dbe07aeb8717141c672ba7df40c08c1566c955afecd4eacabb09165",
          "sha256": "a08d4060825f677277c95e030ff6ca77bf25ae15aad2e364ce9ec351a9c1158e",
          "sha1": "cc28cd6b8e89f7dd4910ea3a5f36f6e930a55b15",
          "md5": "d1fbaf8a4632f97aefd9540fc1b5ee7a"
        }
      ]
    }
  ]
}
