{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "level_events",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "level_events-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "level_events-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 746263,
          "sha512": "ecaaed7b573034d5b626705219012aec321f08cf3d758472d80dcc9aaee9ba9d3c84cb22a08c65910f48021f26340907ec0905c7db818842f0888f9585b58ac3",
          "sha256": "667374e68dd663289f829432cc2edbd2b928afe45a488eff4955d4746be86c37",
          "sha1": "b62fb0894b7239a1c83a16b5d6b3f6fcd3d222d3",
          "md5": "9e0f6b192aa43ad699a9c52710192495"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "level_events-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "level_events-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 746263,
          "sha512": "ecaaed7b573034d5b626705219012aec321f08cf3d758472d80dcc9aaee9ba9d3c84cb22a08c65910f48021f26340907ec0905c7db818842f0888f9585b58ac3",
          "sha256": "667374e68dd663289f829432cc2edbd2b928afe45a488eff4955d4746be86c37",
          "sha1": "b62fb0894b7239a1c83a16b5d6b3f6fcd3d222d3",
          "md5": "9e0f6b192aa43ad699a9c52710192495"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "level_events-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "level_events-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 31309,
          "sha512": "3983aa86808a5c7324303dd70ba6b4a30f1c6de642d2a393b63da3439120982770fd6ba5b76bfc19963d592984553ff2c79660cd168adcda941a10117841dd2a",
          "sha256": "ca6a494fc1fc8a3f5d81257787e49ba34b4529e86a0c6041dca96d43d3676ff0",
          "sha1": "c1bd84b0707c2707a4c05d3f08924db19f348ecd",
          "md5": "ab1d5f17e4398af889e88671f538448d"
        }
      ]
    }
  ]
}
