{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.2.1-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.2.1-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.2.1-Resharped-1.8.61.jar",
          "size": 7135477,
          "sha512": "032639890b1c76e3e62dc2724ca2e4469b54b019970c17911d65ec363798a6fbebb6132dc85903d0d57a553525d263b9629d879957e349d0a555b1aa7d00c0de",
          "sha256": "62f61830ad366a6df752a632b4e7e69c063bfc4dca4c77157d48d9169610be80",
          "sha1": "e27ebcefa3bde7daf96ee9f90dac4b299acb1786",
          "md5": "26096824d7f0286ebcea5de673b3264d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.2.1-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.2.1-Resharped-1.8.61.jar",
          "size": 7135477,
          "sha512": "032639890b1c76e3e62dc2724ca2e4469b54b019970c17911d65ec363798a6fbebb6132dc85903d0d57a553525d263b9629d879957e349d0a555b1aa7d00c0de",
          "sha256": "62f61830ad366a6df752a632b4e7e69c063bfc4dca4c77157d48d9169610be80",
          "sha1": "e27ebcefa3bde7daf96ee9f90dac4b299acb1786",
          "md5": "26096824d7f0286ebcea5de673b3264d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.2.1-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.2.1-Resharped-1.8.61-sources.jar",
          "size": 3555990,
          "sha512": "1a368f185f600bdca979d8736a275eb36d92e47b5efe748be79f7c8a7e9becb6a9323f836f2ef184778431282a6725f08dffd848501b2654ec20b46faf77654a",
          "sha256": "414a4e4e1e98f48f680351bade28514d40e27940e526398f3edbc83e9688445e",
          "sha1": "43c366dff0d23990144d846063067c97984e1ef4",
          "md5": "3bcc158b86f56b51425322d16c5f78d2"
        }
      ]
    }
  ]
}
