{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "resources",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "resources-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "resources-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 841139,
          "sha512": "28182f4d74f8fd556a8028cebec3f894ee5ac1bc094f3b1f78966f473a7d44e748513308abd5ee4707ab65d4b6d3c11826fe05567c21dd0356b251345e2969a3",
          "sha256": "c21ce4b83ab0111f25a3a897160195f454d5cecad0f260cb09ec9dcfde83ca18",
          "sha1": "fe94b37bbbe1e6ef65bf799277769b8d5e6876f5",
          "md5": "f6cf3099f13f0a70fd8d39a3edcffe13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "resources-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "resources-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 841139,
          "sha512": "28182f4d74f8fd556a8028cebec3f894ee5ac1bc094f3b1f78966f473a7d44e748513308abd5ee4707ab65d4b6d3c11826fe05567c21dd0356b251345e2969a3",
          "sha256": "c21ce4b83ab0111f25a3a897160195f454d5cecad0f260cb09ec9dcfde83ca18",
          "sha1": "fe94b37bbbe1e6ef65bf799277769b8d5e6876f5",
          "md5": "f6cf3099f13f0a70fd8d39a3edcffe13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resources-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "resources-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 84703,
          "sha512": "45bd2576ecff37bd29b307bf3b8baed5bcfc668f8ffb2ceb2665706a810c0ce6920b1050cf010468b59867d866c569a6c8ee392c078d9a93860b2693f925a88f",
          "sha256": "8d7b2bf8bbc2d01b6ced02b5b5b398db91a6a6c3acb9e86531a57f742e2c8cd6",
          "sha1": "d90e6b83ed6cabce869e1062b9a184f1d0525c91",
          "md5": "7766b90cd92f66135e2e11c3771e6704"
        }
      ]
    }
  ]
}
