{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "tags",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "tags-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "tags-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 845143,
          "sha512": "0a0624a262d52671ef7c5bd8564c8389c27d0361be86b18b8a1283594b4a266db9122bad1384738b5e3a0eed99854c6ab647987b3263dcc520699f70f4589f9a",
          "sha256": "863a9a8a56eacc051f2ac5f087b82d82d933d797daeeac0e4a09538176a3f4e9",
          "sha1": "9c1fe5b1689b4fef601de9f9c1f61e83cb7a7266",
          "md5": "970a5e46954aa3ced88e9d209348944a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "tags-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "tags-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 845143,
          "sha512": "0a0624a262d52671ef7c5bd8564c8389c27d0361be86b18b8a1283594b4a266db9122bad1384738b5e3a0eed99854c6ab647987b3263dcc520699f70f4589f9a",
          "sha256": "863a9a8a56eacc051f2ac5f087b82d82d933d797daeeac0e4a09538176a3f4e9",
          "sha1": "9c1fe5b1689b4fef601de9f9c1f61e83cb7a7266",
          "md5": "970a5e46954aa3ced88e9d209348944a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tags-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "tags-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 152757,
          "sha512": "3ad14e5dedd0cd5c46d3b7c5a64184ffe77944bd9771da26b2b69e16fc3b66d3ead5ae617d7a962ec27022efa41299c78256d813dd6201c6b889bae29a443716",
          "sha256": "c0ffdfff6ab046b3f004fddb628eae90975a8978e66abb5a13614e899446406f",
          "sha1": "d7663d3d37fb98a2ad449a819343b8762176f6c0",
          "md5": "c96adfdbd44102a37532f3b285ed5c27"
        }
      ]
    }
  ]
}
