{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.20.1-1.0.2-Resharped-1.7.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.0.2-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.20.1-1.0.2-Resharped-1.7.55.jar",
          "size": 5313681,
          "sha512": "770198c985cdacea53242154947b6b27ebb75d65b537fbb7e007c19f887daa3b82ca3994580ae3aeecd0cdaaa1843b79fbf4385dcb9c3459dcceb6172864ba70",
          "sha256": "25a0855a810e7fbbd8f44920b190c3e1e345819f253ebffb1724a09f991b4cf3",
          "sha1": "962ea8cb9920700604c07fbc3bbb5e99028ad806",
          "md5": "d513e8740647021899bc8d324a31bc76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "attributes",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "emi-580555",
          "version": {
            "requires": "6420944"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6815736"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6608232"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.105"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180902"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "5984629"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-83-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.0.2-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.20.1-1.0.2-Resharped-1.7.55.jar",
          "size": 5313681,
          "sha512": "770198c985cdacea53242154947b6b27ebb75d65b537fbb7e007c19f887daa3b82ca3994580ae3aeecd0cdaaa1843b79fbf4385dcb9c3459dcceb6172864ba70",
          "sha256": "25a0855a810e7fbbd8f44920b190c3e1e345819f253ebffb1724a09f991b4cf3",
          "sha1": "962ea8cb9920700604c07fbc3bbb5e99028ad806",
          "md5": "d513e8740647021899bc8d324a31bc76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.0.2-Resharped-1.7.55-sources.jar",
          "url": "slashblade-refabricated-1.20.1-1.0.2-Resharped-1.7.55-sources.jar",
          "size": 3646133,
          "sha512": "fa9aace699cf9b57b9d981d41e8a95cc0e4dce0a882026b05760dc38e975a53bb102d57d1cf67fca5ccf198925111cf55d87cdb8426fc62f6f239a8db5d7353f",
          "sha256": "5d628d534d5bac544e74e5e10fc988a453c38d4466f9889667504cb519bd013e",
          "sha1": "7d11920a9516c5d80e89888b0e2854c97156e407",
          "md5": "8841c49a3395094813ef1ae2afe73a08"
        }
      ]
    }
  ]
}
