{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_data",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "model_data-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "model_data-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 680379,
          "sha512": "89fdf96d80cedf73a3b7b8a68d43b4f58c1a1993aaeea3c9d852c4fc97c94f830c3f7886e22a2dbf989e1a81404e11ab8fb583ff997b860182b0e1d87f5a0440",
          "sha256": "efb6ff88af3042cc9851f3e9805bad04a5bc386c75680a50221265b7be9f8710",
          "sha1": "26c7c6bf0e5006c5ab42dbe78d5bf3762d8c3ad2",
          "md5": "8975a25e4e60d4fa2fa03fab52823c9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "model_data-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "model_data-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 680379,
          "sha512": "89fdf96d80cedf73a3b7b8a68d43b4f58c1a1993aaeea3c9d852c4fc97c94f830c3f7886e22a2dbf989e1a81404e11ab8fb583ff997b860182b0e1d87f5a0440",
          "sha256": "efb6ff88af3042cc9851f3e9805bad04a5bc386c75680a50221265b7be9f8710",
          "sha1": "26c7c6bf0e5006c5ab42dbe78d5bf3762d8c3ad2",
          "md5": "8975a25e4e60d4fa2fa03fab52823c9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_data-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "model_data-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 4707,
          "sha512": "b5055248448b8ddf3a9c81ed0680aa319715e1bfd8f7dda766a983aeb90b1fa85d7cca30306592070d480572c59c9aa346a268675914e7e76e5e17fd62e8c8a3",
          "sha256": "ed645def9e917ba5f811c3c056792fbf0e10307c47da90f5f9c48673564965b8",
          "sha1": "050174e28e212aa7c0f5f0744632d8d7fdb9b8ba",
          "md5": "f12684941e02254267a1178d1dc8f0bc"
        }
      ]
    }
  ]
}
