{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "entity_data_serializers",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "entity_data_serializers-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "entity_data_serializers-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 680744,
          "sha512": "72bf63a03d3c920bf972a3ad45007de9eed1195004053aea583f9bfc8b3b7108eb9c0e103bd49c2cbe8a7d59523b0b64fe31c45b25b56daac2509fcff5f16409",
          "sha256": "d429d95fdd9eff394f2d28f711934044e1503af7e6f85033852baf99b0f3ed61",
          "sha1": "1259cc861f563bae2c15b8773bc516c11d4118a3",
          "md5": "e5411b05e2a10c9e4b34e19e85e273a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "entity_data_serializers-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "entity_data_serializers-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 680744,
          "sha512": "72bf63a03d3c920bf972a3ad45007de9eed1195004053aea583f9bfc8b3b7108eb9c0e103bd49c2cbe8a7d59523b0b64fe31c45b25b56daac2509fcff5f16409",
          "sha256": "d429d95fdd9eff394f2d28f711934044e1503af7e6f85033852baf99b0f3ed61",
          "sha1": "1259cc861f563bae2c15b8773bc516c11d4118a3",
          "md5": "e5411b05e2a10c9e4b34e19e85e273a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity_data_serializers-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "entity_data_serializers-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 4883,
          "sha512": "0b877d398e216cde381d4103b47895a91452c8cbbcb836de02ddcc643edb9fa257991f3f58bff7152f59d197a574ae35b67be7c5d964831fe0a99eb0e88f3bc1",
          "sha256": "945a44455f0546f3b9ca128ced8c2182a8b4aa9ab25284f928925dfcc60030df",
          "sha1": "9462889c27f6f3ede8b7d8b5e9c96a4ab2de611e",
          "md5": "74d3b84175936f8c0b53b3235db5ea29"
        }
      ]
    }
  ]
}
