{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "blocks",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "blocks-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 801717,
          "sha512": "07515f72f286215ee878c41df71dd8f0f0a048c15d9f5eb1d2b2acc81eab35e738f90cd7df6d57e5353fc55de27761832cd7b6737a75579805c11a1a0747bd27",
          "sha256": "75651db1453ba6461a396460a4939d5c9824a3a40b9c610d81b3ce013e6d641c",
          "sha1": "46c73121ca623558919a9882ae6b1f7b5a245cab",
          "md5": "8f378dd97d9504219921ba4ddbd170cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "blocks-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 801717,
          "sha512": "07515f72f286215ee878c41df71dd8f0f0a048c15d9f5eb1d2b2acc81eab35e738f90cd7df6d57e5353fc55de27761832cd7b6737a75579805c11a1a0747bd27",
          "sha256": "75651db1453ba6461a396460a4939d5c9824a3a40b9c610d81b3ce013e6d641c",
          "sha1": "46c73121ca623558919a9882ae6b1f7b5a245cab",
          "md5": "8f378dd97d9504219921ba4ddbd170cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "blocks-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 94334,
          "sha512": "7341dd9e974c2331989d3f1ef8eea1c19b5aed2cdac2f9aad7f9bd0c11ccb85b6cc66d3ca9aaa719f5de55345bb349825018da66fd37d0306715967e916224b8",
          "sha256": "7dbcf7ae641f65028ebe9da41c9f41406fddbb952a1ecb324a2dce5536362f0e",
          "sha1": "92340eee9c05a934c4eb5c4bb659101a9d8b952d",
          "md5": "facddc092710c1a39b05454f07803a01"
        }
      ]
    }
  ]
}
