{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_data",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "model_data-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "model_data-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 680377,
          "sha512": "a1fc0a50dbea5111653a9148a71277629c7fbb62f30d92f8d8a380c0fc10e9f21174578d2dcc4564cf492eaa542f1fd34b22f22a39ec6ed7599ee40671384d16",
          "sha256": "c8566dba3305dec03afd2b1a52cc24f9f27e9879b0b14b4edca808ebdf5f7371",
          "sha1": "2105f186bb6b9678389842364830aca10e47447a",
          "md5": "ebdb7ca1fc22b1bfef6f8c655ed54546"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "model_data-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "model_data-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 680377,
          "sha512": "a1fc0a50dbea5111653a9148a71277629c7fbb62f30d92f8d8a380c0fc10e9f21174578d2dcc4564cf492eaa542f1fd34b22f22a39ec6ed7599ee40671384d16",
          "sha256": "c8566dba3305dec03afd2b1a52cc24f9f27e9879b0b14b4edca808ebdf5f7371",
          "sha1": "2105f186bb6b9678389842364830aca10e47447a",
          "md5": "ebdb7ca1fc22b1bfef6f8c655ed54546"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_data-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "model_data-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 4707,
          "sha512": "f2727d3e7cae4b7f4f25d75dacb3f8e00b2432f211c9cf73a5845a2f89728b9c0ad05b29cb8219a7bf4e952df00b43c0d331fe2c861b66ae4673250d6f9d9d89",
          "sha256": "330ab9211c3a238fa1ed6758ccc7ed0cdbd4307c81b1d17e83cf7983bba6b18e",
          "sha1": "bfdeecb5b65695e82fd49d19f7ad8a76c4af23d4",
          "md5": "826869275f25f686f4705370ae1b8e82"
        }
      ]
    }
  ]
}
