{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "tlmo-additions",
    "version": "1.0.2+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tlmo-additions-1.0.2+mc1.20.1.jar",
          "url": "tlmo-additions-1.0.2+mc1.20.1.jar",
          "size": 446527,
          "sha512": "305b238d473932e3efa98cb77e3e640e20dff78f909510ac6fc3ce0360926efdd24e3a29cf5a6965fe6ad3d0818a911c84c6c8af8106415d22762a180d753c96",
          "sha256": "732868d8cb04bc68c271bcb1e667cb32170f5792cdd876b6999c8fd15392271d",
          "sha1": "07d1f65f8b8d53468ace3554f016e98e1945c29f",
          "md5": "d99717a08ba7ea58a2835298386e0370"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.7+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.6.4-forge1.5.0"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "explorers-compass-491794",
          "version": {
            "requires": "4712192"
          }
        },
        {
          "group": "curse.maven",
          "module": "natures-compass-252848",
          "version": {
            "requires": "4712188"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.136"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.1+build.1744-mc1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "create-connected-fabric-1005193",
          "version": {
            "requires": "7781316"
          }
        }
      ],
      "files": [
        {
          "name": "tlmo-additions-1.0.2+mc1.20.1.jar",
          "url": "tlmo-additions-1.0.2+mc1.20.1.jar",
          "size": 446527,
          "sha512": "305b238d473932e3efa98cb77e3e640e20dff78f909510ac6fc3ce0360926efdd24e3a29cf5a6965fe6ad3d0818a911c84c6c8af8106415d22762a180d753c96",
          "sha256": "732868d8cb04bc68c271bcb1e667cb32170f5792cdd876b6999c8fd15392271d",
          "sha1": "07d1f65f8b8d53468ace3554f016e98e1945c29f",
          "md5": "d99717a08ba7ea58a2835298386e0370"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tlmo-additions-1.0.2+mc1.20.1-sources.jar",
          "url": "tlmo-additions-1.0.2+mc1.20.1-sources.jar",
          "size": 261947,
          "sha512": "39ab021f616c99123f256a8623d6b703c83787cbc9b6a44aa23f66bb8fe9cfcd0149e114903de54d6e00777b592a0c914ddd91004e5dfc6e7b255a6809703cf4",
          "sha256": "047bc4f7354779a4b3cb7dd5b01af04f0594af89f5845ae65503ac723f2ad838",
          "sha1": "7715354616de91673dd6171571baf13c2d399bb8",
          "md5": "049863fef378fe7a4bb88dcdaee0cab0"
        }
      ]
    }
  ]
}
