{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "common",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "common-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 696493,
          "sha512": "ba7a8f95eda6c4860a54d15d0044b1468f65c355f6486bbd384d4f24f5a60ee38a2176d7d1c722bfc8ba8e8515211d2e88d1d24907b9ac3cd13ffc7fc8a29253",
          "sha256": "68d283fd641e5d1682c771b0fec38c41b54f8c73e9955a742b5640a3bd48e977",
          "sha1": "ca209d0f72bd90da4f594b50c71e7e6882d91418",
          "md5": "20c5618b67bab5b0edae8d7b40fa8a16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "common-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 696493,
          "sha512": "ba7a8f95eda6c4860a54d15d0044b1468f65c355f6486bbd384d4f24f5a60ee38a2176d7d1c722bfc8ba8e8515211d2e88d1d24907b9ac3cd13ffc7fc8a29253",
          "sha256": "68d283fd641e5d1682c771b0fec38c41b54f8c73e9955a742b5640a3bd48e977",
          "sha1": "ca209d0f72bd90da4f594b50c71e7e6882d91418",
          "md5": "20c5618b67bab5b0edae8d7b40fa8a16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "common-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 14572,
          "sha512": "65aedac597bd6b70f91f6d2465ed165f56ec0398f217558bc42cb92cf0b9e80adcbd7b08de1eed398dcc97d230f8f8c27bcf2a3ca0d1c9e5bd47561d269ff1ed",
          "sha256": "45aa4fb81193ba806ea30a19a5f4addd78f3a98d2844209276f30225ed21b086",
          "sha1": "bbe92be65c2cd686ed80d5a86229302b6881d230",
          "md5": "f00fb2a27a7c5c7a61ae769dd996b5b3"
        }
      ]
    }
  ]
}
