{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.20.1",
    "version": "0.5.1-forge1.1.7-hotfix2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.5.1-forge1.1.7-hotfix2.jar",
          "url": "TACZ-Refabricated-1.20.1-0.5.1-forge1.1.7-hotfix2.jar",
          "size": 52683794,
          "sha512": "52f10f1f4e35357e553c9930f57fc36a4825017d8d14870301cbbc179df440a804a4343295d36b7034e077fd13d45ac5d4c346161aae9e215974b38db69bd84d",
          "sha256": "516a8007f24aa634aea1c79fee549990eb89c9238b895b6b66fc3e01b7891c40",
          "sha1": "7961e56a9a1ec617f7763f31670ca2414b20bb97",
          "md5": "456e2731249f704a7286dfa7b500ec0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784146"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "1.20.X-1.2.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.8-1.20.1-alpha-fabric.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.104"
          }
        },
        {
          "group": "curse.maven",
          "module": "spark-361579",
          "version": {
            "requires": "4738953"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6902843"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826546"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.5.1-forge1.1.7-hotfix2.jar",
          "url": "TACZ-Refabricated-1.20.1-0.5.1-forge1.1.7-hotfix2.jar",
          "size": 52683794,
          "sha512": "52f10f1f4e35357e553c9930f57fc36a4825017d8d14870301cbbc179df440a804a4343295d36b7034e077fd13d45ac5d4c346161aae9e215974b38db69bd84d",
          "sha256": "516a8007f24aa634aea1c79fee549990eb89c9238b895b6b66fc3e01b7891c40",
          "sha1": "7961e56a9a1ec617f7763f31670ca2414b20bb97",
          "md5": "456e2731249f704a7286dfa7b500ec0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.5.1-forge1.1.7-hotfix2-sources.jar",
          "url": "TACZ-Refabricated-1.20.1-0.5.1-forge1.1.7-hotfix2-sources.jar",
          "size": 48832778,
          "sha512": "3cb9d15d08355f71c1da91156cb166c4f80e8b3fd9d8dab7837581da90cac82a2b67dffc7746773b79874c5a693cd1fffce1f5afd1262b7373328df8a047b45d",
          "sha256": "5b35d6f823e0d5a6bbe8b5c85eea387c1f95c40d7ac79e61afc61ad10e4dff70",
          "sha1": "fb9ddf000325e9598a81090f77c68d5db7c2b395",
          "md5": "f99061f7ffb1aa0ee8e1482a367b2a1a"
        }
      ]
    }
  ]
}
