{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "touhoulittlemaid-fabric-1.20.1",
    "version": "0.6.3-forge1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0.jar",
          "size": 28028818,
          "sha512": "0928cf7223aa52b7b3339ee5632766dc7e7ecc475b8bbd959b96b3ce2df6f56ebd091c962dd913ec8acf4d5f29ad81b1241808b37d831b8533f0a6b6418db5fe",
          "sha256": "c96fc73aa03b344482ddd4c29d42e22b160737d39a5f24de287cbcefb93c5332",
          "sha1": "e84c6ff9dda996be2d4a0b27d4acd4d709473e89",
          "md5": "d9372b559468ac906636fba8c70838aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.gagravarr",
          "module": "vorbis-java-core",
          "version": {
            "requires": "0.8"
          }
        },
        {
          "group": "io.github.jaredmdobson",
          "module": "concentus",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "libs",
          "module": "SlashBlade-Refabricated-1.20.1",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112-fabric"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.136"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "cyberanner-ironchest",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carry-on",
          "version": {
            "requires": "2.1.2.7-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patchouli",
          "version": {
            "requires": "1.20.1-84.1-fabric"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.4+kotlin.2.2.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "libipn",
          "version": {
            "requires": "fabric-1.20-4.0.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "inventory-profiles-next",
          "version": {
            "requires": "fabric-1.20.1-1.10.15"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "simple-hats",
          "version": {
            "requires": "SDPZOmWZ"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.16"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino-fabric",
          "version": {
            "requires": "2001.2.3-build.10"
          }
        },
        {
          "group": "net.conczin",
          "module": "immersive_melodies",
          "version": {
            "requires": "0.6.0+1.20.1+fabric"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Fabric-1.20.1",
          "version": {
            "requires": "1.0.83"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "kaleidoscope-cookery-refabricated",
          "version": {
            "requires": "1.2.0-fabric+mc1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "improved-mobs",
          "version": {
            "requires": "1.20.1-1.13.6-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tenshilib",
          "version": {
            "requires": "1.20.1-1.7.6-fabric"
          }
        },
        {
          "group": "libs",
          "module": "TACZ-Refabricated-1.20.1",
          "version": {
            "requires": "0.0.7-forge1.1.6-hotfix"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "OFIAZVy7"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patpat",
          "version": {
            "requires": "1.2.1+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "proxlib",
          "version": {
            "requires": "0.2.4+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "vectorwing",
          "module": "FarmersDelight",
          "version": {
            "requires": "1.20.1-2.4.1+refabricated"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "common-network",
          "version": {
            "requires": "1.0.5-1.20.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "just-more-cakes",
          "version": {
            "requires": "1.18.1-fabric,1.20.1"
          }
        },
        {
          "group": "io.github.cottonmc",
          "module": "LibGui",
          "version": {
            "requires": "8.1.1+1.20.1"
          }
        },
        {
          "group": "me.zeroeightsix",
          "module": "fiber",
          "version": {
            "requires": "0.23.0-SNAPSHOT"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-minimap",
          "version": {
            "requires": "25.2.10_Fabric_1.20"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-world-map",
          "version": {
            "requires": "1.39.12_Fabric_1.20"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0.jar",
          "size": 28028818,
          "sha512": "0928cf7223aa52b7b3339ee5632766dc7e7ecc475b8bbd959b96b3ce2df6f56ebd091c962dd913ec8acf4d5f29ad81b1241808b37d831b8533f0a6b6418db5fe",
          "sha256": "c96fc73aa03b344482ddd4c29d42e22b160737d39a5f24de287cbcefb93c5332",
          "sha1": "e84c6ff9dda996be2d4a0b27d4acd4d709473e89",
          "md5": "d9372b559468ac906636fba8c70838aa"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0-shadow.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0-shadow.jar",
          "size": 23381884,
          "sha512": "d4c289a9a438c8903d0756524930c9056dfd1c43a569b7077b260aca556a55f1d7961d5349a20919235c2de6b91b916d14b7c67c77b97f26a62e38291c389695",
          "sha256": "1fb82a6a434c280fc9005d0fd8ab69f79f58fcc63c93dcc1af1e86a521a33dcb",
          "sha1": "9d719ff3601f61fceafa88850f91e251fd741c1d",
          "md5": "a01df9cdeca5616ebc008ecd6f61da53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0-sources.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.3-forge1.5.0-sources.jar",
          "size": 21255596,
          "sha512": "522e06e57fa97f24f964b63cb26f8ea9e50176825d0a1f32a0c4c93723031fa7530d1ae206817e607048e8d25bee25b6440b7a56e66db16467256caa9d3b7be9",
          "sha256": "6b106fc837ff45ad6a629fce63b9a53329244cb67af86fe876d11a0f245092d5",
          "sha1": "9862d63546724cd63eccb31c74d02d7003484c2e",
          "md5": "9b6fde97690423df2788fe6480540395"
        }
      ]
    }
  ]
}
