{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.21.1",
    "version": "0.1.1-forge1.1.6-hotfix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.1.1-forge1.1.6-hotfix.jar",
          "url": "TACZ-Refabricated-1.21.1-0.1.1-forge1.1.6-hotfix.jar",
          "size": 47977014,
          "sha512": "e029e8c1bd310f3443067a10bcbecbff161fdbaeae73f287698f13bd3d4664c1872e795e670a939e3a39e3a7c6a7b92b6fb19b1028f1df86292adf69c7d85e8a",
          "sha256": "f350217b19aac48e34421ae20c697f4c80e32b6b8d4cef497c2d7135dc39db71",
          "sha1": "293dfee1dfe489e0eb5afbb5c1503d3b7105c3f4",
          "md5": "e859a39e0b343afc891fbfbf86ff4b51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.5+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784174"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6914081"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.21.59"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.21.9"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.744"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.1.1-forge1.1.6-hotfix.jar",
          "url": "TACZ-Refabricated-1.21.1-0.1.1-forge1.1.6-hotfix.jar",
          "size": 47977014,
          "sha512": "e029e8c1bd310f3443067a10bcbecbff161fdbaeae73f287698f13bd3d4664c1872e795e670a939e3a39e3a7c6a7b92b6fb19b1028f1df86292adf69c7d85e8a",
          "sha256": "f350217b19aac48e34421ae20c697f4c80e32b6b8d4cef497c2d7135dc39db71",
          "sha1": "293dfee1dfe489e0eb5afbb5c1503d3b7105c3f4",
          "md5": "e859a39e0b343afc891fbfbf86ff4b51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.1.1-forge1.1.6-hotfix-sources.jar",
          "url": "TACZ-Refabricated-1.21.1-0.1.1-forge1.1.6-hotfix-sources.jar",
          "size": 44163617,
          "sha512": "6d292d46bef4523184c1c74ba6fe3edd434e0a5305051c2d34de2420410965a71e32c700d7364f4e8d7f006ba47516fc7618795abfd0d149350c9c4073b56036",
          "sha256": "78b0dc32991d45499a4901d6aea77ebab94e589df6b6bd8a4ff0ae88b74b20a9",
          "sha1": "70c4e55959386ebd8d02e3ab11ab5214f99fa49a",
          "md5": "04d4ede81927f2724e66f7ff02afa99e"
        }
      ]
    }
  ]
}
