{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.3.0-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.0-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.0-Resharped-1.8.61.jar",
          "size": 7135675,
          "sha512": "b7cf35893dd93e18a77c9cd8834b85214c3ba260e620457a0f8f8e14f8b36bdb9f8fc7023099fd846d7800fecf6531a457161449c1c6254aca44911bf61c61aa",
          "sha256": "a4ce9355c058ea1bc30758e1bdeb1cabbab7da7313e471384324eee56a696ec6",
          "sha1": "b7659a5cea600b97e28245c9cfa48797f121b145",
          "md5": "e4b0bf711171dbe7d98e5bb1031889ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.0-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.0-Resharped-1.8.61.jar",
          "size": 7135675,
          "sha512": "b7cf35893dd93e18a77c9cd8834b85214c3ba260e620457a0f8f8e14f8b36bdb9f8fc7023099fd846d7800fecf6531a457161449c1c6254aca44911bf61c61aa",
          "sha256": "a4ce9355c058ea1bc30758e1bdeb1cabbab7da7313e471384324eee56a696ec6",
          "sha1": "b7659a5cea600b97e28245c9cfa48797f121b145",
          "md5": "e4b0bf711171dbe7d98e5bb1031889ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.0-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.0-Resharped-1.8.61-sources.jar",
          "size": 3556349,
          "sha512": "664da3b6c94392e477874cecd0fd624ec0de43dc0a91298e1302b493db83cad095b8b58f96e02383f55bb78677694e2e52cfdc1aa7ff54df5457cd6697eb0c5a",
          "sha256": "fd15640b71b3986d7919b6d2eef4af91c35784f901a79f81b48bd82803b1f084",
          "sha1": "20a0d679673d025bae027b8aa28e80871db09bac",
          "md5": "0462755afb106ba77e14fcf3c4e18057"
        }
      ]
    }
  ]
}
