{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.5+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.22.1.316"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.5+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.5+mc1.21.1.jar",
          "size": 6720397,
          "sha512": "d9ad8e2d4b2524cc382b1a80d1778c3ccf5ccbc17fb172578b4bcb73d3e55cd447b91d9acf596cb8746916db5ccc2ba97b16af2faf7f14afc1a47382e2a98a88",
          "sha256": "b3bd9e35f5e7b7f14d3a2bb3abc6d5c3ab9069fedfcd5edf47742da692581d87",
          "sha1": "df8066d94daa2f62935d83027d89392d24b92e59",
          "md5": "ad4d5a3b3dfac6943bde2efc5b5a3edc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.1.5-Resharped-1.8.60"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.5+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.5+mc1.21.1.jar",
          "size": 6720397,
          "sha512": "d9ad8e2d4b2524cc382b1a80d1778c3ccf5ccbc17fb172578b4bcb73d3e55cd447b91d9acf596cb8746916db5ccc2ba97b16af2faf7f14afc1a47382e2a98a88",
          "sha256": "b3bd9e35f5e7b7f14d3a2bb3abc6d5c3ab9069fedfcd5edf47742da692581d87",
          "sha1": "df8066d94daa2f62935d83027d89392d24b92e59",
          "md5": "ad4d5a3b3dfac6943bde2efc5b5a3edc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.5+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.5+mc1.21.1-sources.jar",
          "size": 3803091,
          "sha512": "1cf2d8b2e3951204072969744c6692581bece92fdb92dad849e0fe26f4cdfade81a0ea2caa048f475faf2fa37df7e20ba1134a7bd832909cce944937facb28f6",
          "sha256": "4b6e45e6dab2e4c8ecddcdd20061bcc92f27e2c0a5770008e8ed60f8fb0155f9",
          "sha1": "148085c4916ff2fbcce4ee1fee17af81fb0dec95",
          "md5": "455b2e24835f5084f3479fdb3dbb9d6f"
        }
      ]
    }
  ]
}
