{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "attributes",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "attributes-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "attributes-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 691360,
          "sha512": "352503b8010f5c199db4135cff30414a65081d3b04447d5d79e8f3c6de0c531afc3051fd62f79bc09e6db65c143fe699c02bea1811a590d54deb83aaf6b04ff9",
          "sha256": "f2b204d51079a57bcdb3113f9dd5dd34ae5533a2f72396fc448c8e6e7d4cb7ba",
          "sha1": "4cde30a9234d164e0a6d0f2ea191015cc26d06bf",
          "md5": "884763e179734e2f8b95eb45dfb2b44c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "attributes-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "attributes-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 691360,
          "sha512": "352503b8010f5c199db4135cff30414a65081d3b04447d5d79e8f3c6de0c531afc3051fd62f79bc09e6db65c143fe699c02bea1811a590d54deb83aaf6b04ff9",
          "sha256": "f2b204d51079a57bcdb3113f9dd5dd34ae5533a2f72396fc448c8e6e7d4cb7ba",
          "sha1": "4cde30a9234d164e0a6d0f2ea191015cc26d06bf",
          "md5": "884763e179734e2f8b95eb45dfb2b44c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "attributes-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "attributes-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 13495,
          "sha512": "4899bcf4b905e2e07c4a917d57040c99269ef150d7e0796d602e47aa4b099bb25a5498f0808608483b82f1adb79c8471a05557ed91abe8c312bcd38f058c2e04",
          "sha256": "617e9fb8f7bd6fb0f5e5ca7b57084007945b9a6ffb31dc38f8926022bba7b4c3",
          "sha1": "a23b6e38408149e76f1db70d93a52bbf7b33545c",
          "md5": "e5a7890609328bae59ade2cf5f6ab050"
        }
      ]
    }
  ]
}
