{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "chunk_loading",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "chunk_loading-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "chunk_loading-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 708830,
          "sha512": "b279183cc3eaacb2393b164b00dd8f801124669fdae423cad4c0606c4aec42fa456f28a6b47fcf54d29547463f578a2bac4598ee8976a889ca8066d9e47a8f43",
          "sha256": "d94ddc9712b35b9744df5faa9685ea519b8f1f35cc4ad3e6d57f7ca0cdf2815c",
          "sha1": "df1181abaea3d645210f3ab5a385fc454ca1c56f",
          "md5": "1c1db4f77d7f4dffff28f45d5079d6dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "chunk_loading-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "chunk_loading-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 708830,
          "sha512": "b279183cc3eaacb2393b164b00dd8f801124669fdae423cad4c0606c4aec42fa456f28a6b47fcf54d29547463f578a2bac4598ee8976a889ca8066d9e47a8f43",
          "sha256": "d94ddc9712b35b9744df5faa9685ea519b8f1f35cc4ad3e6d57f7ca0cdf2815c",
          "sha1": "df1181abaea3d645210f3ab5a385fc454ca1c56f",
          "md5": "1c1db4f77d7f4dffff28f45d5079d6dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chunk_loading-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "chunk_loading-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 20111,
          "sha512": "823f78979f8610fd31203f2455d2939b7ceb4afbcc09d3d93574eddf4a2d64f75180393f39d85ea8a957667a33f9a4100738555d2aaecd4f136970b2d175fddb",
          "sha256": "7e40449ab8fd18069c3f3cd4b0bdc3b2c8e1bc792b8e827aedc6bd2c669f6631",
          "sha1": "0a57d45dec6b23f355b49f4b7d4e0f40aeea40ba",
          "md5": "e01574f75025ea1f9a3f46147ae2a8ca"
        }
      ]
    }
  ]
}
