{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "item_abilities",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "level_events",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "item_abilities-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "item_abilities-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 752702,
          "sha512": "5fffa7cf4a2d2de4157db3a9c82afb4522e76eb9d5fe6cd42dbab02cc3488af925ddc3223ce367d64f798aefba176801f3ebef686f1ebbc835ba05e7eb6fb941",
          "sha256": "81688092eb87db101a4435506fff493bc2d5f629b335f97e692bc6f462d503eb",
          "sha1": "6cce8b021f788e5421be0d789f4202957c94371b",
          "md5": "177037e4fadba948b7674e5c98c8b699"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "level_events",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "item_abilities-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "item_abilities-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 752702,
          "sha512": "5fffa7cf4a2d2de4157db3a9c82afb4522e76eb9d5fe6cd42dbab02cc3488af925ddc3223ce367d64f798aefba176801f3ebef686f1ebbc835ba05e7eb6fb941",
          "sha256": "81688092eb87db101a4435506fff493bc2d5f629b335f97e692bc6f462d503eb",
          "sha1": "6cce8b021f788e5421be0d789f4202957c94371b",
          "md5": "177037e4fadba948b7674e5c98c8b699"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "item_abilities-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "item_abilities-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 59063,
          "sha512": "7cfa71266bb2867ac5b2975b692038199148337c68b7e9ac352888602b3cf359c26b4e2080217e95fcd667110116791f6c67924df714086b9d8adf55adc6eb61",
          "sha256": "a96eab0576e73f22c74226e8aeedb49f745a72c4fc19273a2d5a63eefab7a83e",
          "sha1": "e42431a643dd864ae927d4ac875643da614c1f18",
          "md5": "00faf957d35a50273f259b815b60ea05"
        }
      ]
    }
  ]
}
