{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "loot",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "resources",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "loot-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "loot-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 707652,
          "sha512": "df5710ecf1c3678d6c95e3b2b342ba570c0644c41b35bfd68560045b5f19f525a86e777aa53d9e99601b3f9c2aff139c862c6932b3450f2e79bcacd312956014",
          "sha256": "20bdfc9cea0acb5e1f6edd8975769f2a898acfb4e76acca2a845d45da7dbaba6",
          "sha1": "1a48406cb2b46161792db1e9056baa4efab6dab9",
          "md5": "5743b445498b6bab9d32e9f3b73977a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "resources",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "loot-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "loot-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 707652,
          "sha512": "df5710ecf1c3678d6c95e3b2b342ba570c0644c41b35bfd68560045b5f19f525a86e777aa53d9e99601b3f9c2aff139c862c6932b3450f2e79bcacd312956014",
          "sha256": "20bdfc9cea0acb5e1f6edd8975769f2a898acfb4e76acca2a845d45da7dbaba6",
          "sha1": "1a48406cb2b46161792db1e9056baa4efab6dab9",
          "md5": "5743b445498b6bab9d32e9f3b73977a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "loot-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "loot-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 19559,
          "sha512": "f372dfd272ae7ce9aae38d5d294dcc020e5f855f75c81c189b8d48703f2a3db1158209cb43798edcfff6efd4c3f54534da12acbf36e769d7fda959d62b46f38f",
          "sha256": "eeaabaa9f0b6491250820f9f7ba0f906a4c5d1d493e514f882d3efe25c43ce9b",
          "sha1": "7247f562d6a20008b22313536a9768990555e151",
          "md5": "77d93201e323ffd18cc814f08641eecd"
        }
      ]
    }
  ]
}
