{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "brewing",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "brewing-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "brewing-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 691397,
          "sha512": "5139ccc25aa365fb6c812676b661da325f8ab9472fdf196f234c52a8191d84ef198e9fd6d9411bf7bb030a2867c233ecbb32aa521e1c11a0acbf0869bda3e4ae",
          "sha256": "e169683cef73973f83d89246d26cef236154fcc78f70b1bfe1c9cf3f1284323b",
          "sha1": "987e7d777a7f906bd4905502a48b5951e69e934a",
          "md5": "58dbb74b6e2cf2c266e2497c39495e68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "brewing-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "brewing-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 691397,
          "sha512": "5139ccc25aa365fb6c812676b661da325f8ab9472fdf196f234c52a8191d84ef198e9fd6d9411bf7bb030a2867c233ecbb32aa521e1c11a0acbf0869bda3e4ae",
          "sha256": "e169683cef73973f83d89246d26cef236154fcc78f70b1bfe1c9cf3f1284323b",
          "sha1": "987e7d777a7f906bd4905502a48b5951e69e934a",
          "md5": "58dbb74b6e2cf2c266e2497c39495e68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brewing-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "brewing-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 12258,
          "sha512": "083ebb4f6e49cd587a4bf37c01e1e7d9a9838a4c032a527b8ef4cc2940277c451fdb38ebe6efdac2baf39a6c48c6b52ded345ecd3378f122db1d4e24cb1c2b5d",
          "sha256": "9a858dc80796bf272b92fc8b48530207c7cda89ab5620983b6dc21e02430b8fb",
          "sha1": "6aa2a07508a3733984107546afcdf94e25796225",
          "md5": "479bd669970d5beafe70b10aecedc8ae"
        }
      ]
    }
  ]
}
