{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "core",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "core-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 723270,
          "sha512": "2183a99401313ba1775feefa5caddd4250a7310fddeaec644d3f91a80d93ac9cb74e415f19c34955c5a54415f3d2e5decb18f66d4d8c721c106bd345ec8c395a",
          "sha256": "81adeb2db456368cbecdb60bc2f025ba1abfadd16724f86a237a385eb48d989e",
          "sha1": "b1098af84971204c0c40bae88f0fba34e392157d",
          "md5": "41d646a63b0ec91d4c481254387a456c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "core-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 723270,
          "sha512": "2183a99401313ba1775feefa5caddd4250a7310fddeaec644d3f91a80d93ac9cb74e415f19c34955c5a54415f3d2e5decb18f66d4d8c721c106bd345ec8c395a",
          "sha256": "81adeb2db456368cbecdb60bc2f025ba1abfadd16724f86a237a385eb48d989e",
          "sha1": "b1098af84971204c0c40bae88f0fba34e392157d",
          "md5": "41d646a63b0ec91d4c481254387a456c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "core-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 22226,
          "sha512": "2bbaca82cf98f977c1583a26f1126b5cddb2fd02f230cc8a0cc7729f9caf8275000f91267095fae637fe5c510ca4c0415e4a98f353b76974c079886ac25a11e5",
          "sha256": "076673bf504a88ac44ec3802b59862b5ea6f00a25af50053b73b89c07092b738",
          "sha1": "4419aeb270fea8956613236357201759f32c7d72",
          "md5": "1e19b74cf177604fb251ea60bf171a3b"
        }
      ]
    }
  ]
}
