{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.0+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.0+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.0+mc1.20.1.jar",
          "size": 6013454,
          "sha512": "9f3387c93420fe7a687ccb9601fedc9a5a41749f8bf1d1401ac4272a8e52b67ffca37abe5cb464a8a351553e9d67af15c9e3613916b78a988262cf68ca43a2d2",
          "sha256": "5eb140a78b1692f6065952aab8a24b564f5529d0198da439ab8127251b98f1a0",
          "sha1": "c56bb5ac308b382e600e5dd4ff4964f5b415d3e6",
          "md5": "7705781d738052b01a13f30c2cfedbe6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.0.0-Resharped-1.7.55"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.0+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.0+mc1.20.1.jar",
          "size": 6013454,
          "sha512": "9f3387c93420fe7a687ccb9601fedc9a5a41749f8bf1d1401ac4272a8e52b67ffca37abe5cb464a8a351553e9d67af15c9e3613916b78a988262cf68ca43a2d2",
          "sha256": "5eb140a78b1692f6065952aab8a24b564f5529d0198da439ab8127251b98f1a0",
          "sha1": "c56bb5ac308b382e600e5dd4ff4964f5b415d3e6",
          "md5": "7705781d738052b01a13f30c2cfedbe6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.0+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.0+mc1.20.1-sources.jar",
          "size": 3799663,
          "sha512": "24d7399bf06d32ffb759f0120f6503d02db7afdce54e5d8f6de9218bc93d9a1a5eb9e96b4c67d493eda166f07c1d00faf40a96466606555346815f78c7ca3f07",
          "sha256": "54540371402d6f46b528cced4628a85c74d86b02bdeeb45ae6bed9577f08503c",
          "sha1": "1cfb5ec5d654dc0b5fadb3b6fa19220e38fb3e4e",
          "md5": "52b6e1b18b2f12e2a0368792f7fb5626"
        }
      ]
    }
  ]
}
