{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "client_events",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "client_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "client_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 822415,
          "sha512": "957bb92acdd1ddf63c93b3f32797aeed6d3c3a6ed5516aa83cb4466c6b761cfa8f1f0e4271c4222bd03eb55bc5bb2b4c5393b7092a078a60ac0b9d5c3ee750e7",
          "sha256": "b660fa1e8ac0bb03fda1603a3da7737f7f45c1bdce3b6bff5987ff8c866a2f71",
          "sha1": "58435b5a822dd57133e95de52183dd7ca7a2bb72",
          "md5": "54c40702a800ceea8cbd3f13086e67a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        },
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        }
      ],
      "files": [
        {
          "name": "client_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "client_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 822415,
          "sha512": "957bb92acdd1ddf63c93b3f32797aeed6d3c3a6ed5516aa83cb4466c6b761cfa8f1f0e4271c4222bd03eb55bc5bb2b4c5393b7092a078a60ac0b9d5c3ee750e7",
          "sha256": "b660fa1e8ac0bb03fda1603a3da7737f7f45c1bdce3b6bff5987ff8c866a2f71",
          "sha1": "58435b5a822dd57133e95de52183dd7ca7a2bb72",
          "md5": "54c40702a800ceea8cbd3f13086e67a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client_events-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "client_events-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 39408,
          "sha512": "d78719368ff9de6ec080b51df845bcfe4232dca4603a3ec0e7c953d0347a9f8049de368029b82f8b9f19f27a2de803e60f43ec07a5de2c4990902aa592b01d89",
          "sha256": "6d2c98ee7b2e565dd11135174b44fefc4bd87d4dd02e94bfbef418aa3362faff",
          "sha1": "103ac8f2a607d5acfea15e225d163da3d9a1629e",
          "md5": "c77084f85acb35bb648f4c771449471f"
        }
      ]
    }
  ]
}
