{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.3+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.3+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.3+mc1.21.1.jar",
          "size": 50853735,
          "sha512": "88aad88084e8c8c5341f8a212ecf6e6468053bea6bcabd4b7c16c159639fd7924d11c54159e27d06153a7fb7b47f5928b9dafe0f486f82927cd15229aadd6fbc",
          "sha256": "389df7494df721603c786e95ea801cdcf176a5e350a16d1c90fa9280451a491d",
          "sha1": "fbfaca0f2515fbb7c30fc02ab844fc21537639be",
          "md5": "0c85901a9b9ed0921445d2907955a0e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.2-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.3+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.3+mc1.21.1.jar",
          "size": 50853735,
          "sha512": "88aad88084e8c8c5341f8a212ecf6e6468053bea6bcabd4b7c16c159639fd7924d11c54159e27d06153a7fb7b47f5928b9dafe0f486f82927cd15229aadd6fbc",
          "sha256": "389df7494df721603c786e95ea801cdcf176a5e350a16d1c90fa9280451a491d",
          "sha1": "fbfaca0f2515fbb7c30fc02ab844fc21537639be",
          "md5": "0c85901a9b9ed0921445d2907955a0e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.3+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.3+mc1.21.1-sources.jar",
          "size": 50563725,
          "sha512": "d2c6c7d0b7e2509ed29834e769b2a26a6add8cefd9c5ca0f10d1214c1bda594b2107271f08ba9cf7be820d9788ddf9f3366cebfc5d5ec85b5da65a263500a731",
          "sha256": "a1163eaea52f11e3a96df5916e7cf2c990231583423eb154f2f2bff2193be456",
          "sha1": "254e3e390c0338d26b2143911fe6d8a3172152ab",
          "md5": "03efacd5b6947cdcc96766aab3fc2252"
        }
      ]
    }
  ]
}
