{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "render_types",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "render_types-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "render_types-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 690451,
          "sha512": "9836a8d09fff81d79cca328d36bfd99d9cd257a8d194dcf1e901419ea94108351c96b171ccda3c262be7bfb60ead573477a474c22d267a777695594416bfaca6",
          "sha256": "3fd2650930d5a9286be34793a3409eb01c1e52d713bd3229385c0524d1f068c2",
          "sha1": "7796cc9db030aaea28b1cfee7d8921788a96b97d",
          "md5": "00665cfa9f317cd18a7615fbe5754c41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "render_types-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "render_types-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 690451,
          "sha512": "9836a8d09fff81d79cca328d36bfd99d9cd257a8d194dcf1e901419ea94108351c96b171ccda3c262be7bfb60ead573477a474c22d267a777695594416bfaca6",
          "sha256": "3fd2650930d5a9286be34793a3409eb01c1e52d713bd3229385c0524d1f068c2",
          "sha1": "7796cc9db030aaea28b1cfee7d8921788a96b97d",
          "md5": "00665cfa9f317cd18a7615fbe5754c41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "render_types-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "render_types-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 9907,
          "sha512": "cb8e4924423233b3315993aee3a74046d0cbd4d5723a31b8a4420274d58032eb0bce6886da588e96946d8d6b4d6640622b341295f64039c6a2a740441d8e234e",
          "sha256": "7dc49c8623bfe964b460cefaa1c3be94d558063f8e63b9eab55a4171ea3d0d61",
          "sha1": "f021823e9f16d85ed33489f6ce1c68f2183eed2a",
          "md5": "f13488cb02d526e5a2b01b2ca9d63c78"
        }
      ]
    }
  ]
}
