{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "models",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "models-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "models-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 901252,
          "sha512": "c2ec8e7833de1a8c1dd3d0628a0fa6f9abfb5bd01aead79036ee4611d612f43d7837f1086f5e6e96cbb268db514edf95035b5c4352a0ba8629129eff73574848",
          "sha256": "5339c9a58736a53fd33f6b9ffbba78596dc0647a4d95dbcb5626719d3714c46f",
          "sha1": "e389be036281631e4de06e75338f6808c5a18dee",
          "md5": "04c1129a9af685295f319896b602a28a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "models-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "models-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 901252,
          "sha512": "c2ec8e7833de1a8c1dd3d0628a0fa6f9abfb5bd01aead79036ee4611d612f43d7837f1086f5e6e96cbb268db514edf95035b5c4352a0ba8629129eff73574848",
          "sha256": "5339c9a58736a53fd33f6b9ffbba78596dc0647a4d95dbcb5626719d3714c46f",
          "sha1": "e389be036281631e4de06e75338f6808c5a18dee",
          "md5": "04c1129a9af685295f319896b602a28a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "models-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "models-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 104557,
          "sha512": "c2a2951b4caccf9d9bbb1018c5d6c486f15a4132fdfed8d8a4908a97682975d209c61c4cdd0a8a3d86933a492e6547123579a55ac5b90ae652ba4ec03f4df6eb",
          "sha256": "3fccb5ecef6ccbe016e33180bb5544a44eeb2b3d95b62c0b4f2370aee0d19566",
          "sha1": "aa6446beeb43ebfe7d26da2dc42d30e859af5b35",
          "md5": "a2a32562efad4f674c1ec6979474c09a"
        }
      ]
    }
  ]
}
