{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.5+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.5+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.5+mc1.20.1.jar",
          "size": 52633168,
          "sha512": "7c90d9a6ba28d9759c9986bd8e24a58f1a499f0df4f2ccae08f5ad17b28a4d415eba2617835d4b86e8e4ce97d2f0268c377285f60dbf539e2b09628304cadb07",
          "sha256": "85fe23e9b672ce7cecb4f5198d69787977ef34b17441c088ed02913c87fc5767",
          "sha1": "1f24ed7c091c3e6cf79b85ba329028fd044f69c1",
          "md5": "ab686517710f5a4e0f0c4f53265090a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.0-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.5+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.5+mc1.20.1.jar",
          "size": 52633168,
          "sha512": "7c90d9a6ba28d9759c9986bd8e24a58f1a499f0df4f2ccae08f5ad17b28a4d415eba2617835d4b86e8e4ce97d2f0268c377285f60dbf539e2b09628304cadb07",
          "sha256": "85fe23e9b672ce7cecb4f5198d69787977ef34b17441c088ed02913c87fc5767",
          "sha1": "1f24ed7c091c3e6cf79b85ba329028fd044f69c1",
          "md5": "ab686517710f5a4e0f0c4f53265090a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.5+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.5+mc1.20.1-sources.jar",
          "size": 50197250,
          "sha512": "56bd6524d3b8185bd4a4d948b641ef317b0714aa95e579792bb2ee9cfc00f03fc0fc69403e2089fb9f23202cf824b8e54c71e3d2ceec374547cf5d695b72f0f4",
          "sha256": "f9698d3d48d5918b90644f5fc39b0fdc76b1e5f6451cc1577bdbda86600a9616",
          "sha1": "0b9671f48f70725f67df52df2bc78a5918d2784f",
          "md5": "d80406660416575d12b5006933d63fe1"
        }
      ]
    }
  ]
}
