{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.2+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.22.1.316"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.2+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.2+mc1.21.1.jar",
          "size": 50495313,
          "sha512": "a23548cdd337c9079b2b53e0702a017004559511c0d4994d3bfeae1a512b14ea4daf7419b8563af8b2d4355180f964f594220b05b98cc82468d6036951ab8da2",
          "sha256": "b3fe9a3e644cfa2b411fdf2323dd501fbae9067a990fb1303c647402c1908015",
          "sha1": "23bc0ef32bb46441d1818d8ea14c7950b162f0d1",
          "md5": "1b8ff7f465fb06c9171ef8e8e22269d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.2-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.2+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.2+mc1.21.1.jar",
          "size": 50495313,
          "sha512": "a23548cdd337c9079b2b53e0702a017004559511c0d4994d3bfeae1a512b14ea4daf7419b8563af8b2d4355180f964f594220b05b98cc82468d6036951ab8da2",
          "sha256": "b3fe9a3e644cfa2b411fdf2323dd501fbae9067a990fb1303c647402c1908015",
          "sha1": "23bc0ef32bb46441d1818d8ea14c7950b162f0d1",
          "md5": "1b8ff7f465fb06c9171ef8e8e22269d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.2+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.2+mc1.21.1-sources.jar",
          "size": 50205303,
          "sha512": "ceb5141065aed156cac61342f7437e958cab198cfe877c0bcc734e7c5ed5e5c965158ed07630a9597cb3c5312056d0b6aafd5336a91ee322349167b729d4321c",
          "sha256": "04e2ab63616165f81445d8d65601fb0431c2b55d253fafcc1204834e920ab6bb",
          "sha1": "d732656e0609de8e1555846d5b5d76cbe7085e3b",
          "md5": "fbce1d48e2c5894b42fcec35d6c4ec55"
        }
      ]
    }
  ]
}
