{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.3+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.3+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.3+mc1.20.1.jar",
          "size": 52631628,
          "sha512": "84d7bf725f9ed7dc33c0aefd3879cd3e6617413856ccd306ab081f752df370abba7d597f7f80c000822c8297996b7ef6d8ee95ed3c7f6b62b5b8e7c124678d7c",
          "sha256": "8ca09ea72ebe20cd1b9247a2b3d205a39fcb20becefe4215b3c88c89f408767d",
          "sha1": "ce72cb26ad0e5ead531eb038fd548d2f6d9c50b8",
          "md5": "92c26aa876bb3a9d21600162dd5a1a1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.0-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.3+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.3+mc1.20.1.jar",
          "size": 52631628,
          "sha512": "84d7bf725f9ed7dc33c0aefd3879cd3e6617413856ccd306ab081f752df370abba7d597f7f80c000822c8297996b7ef6d8ee95ed3c7f6b62b5b8e7c124678d7c",
          "sha256": "8ca09ea72ebe20cd1b9247a2b3d205a39fcb20becefe4215b3c88c89f408767d",
          "sha1": "ce72cb26ad0e5ead531eb038fd548d2f6d9c50b8",
          "md5": "92c26aa876bb3a9d21600162dd5a1a1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.3+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.3+mc1.20.1-sources.jar",
          "size": 50196170,
          "sha512": "d5e0ec24d88eab01a3f9200ee32a3d88a47b5bd23d9276c82144b1ce2e5c2c55e57b6ac809ddb2b9efbf6aad6538433632f9b5e8cd074081710ccfe0f546d1bc",
          "sha256": "611b27932a285375ed588b2147a5bed07a905c1c102616c088ba5032eb00f1db",
          "sha1": "6df40ef0dc09e741f128a26857541e740c4f63ed",
          "md5": "29793cc9c94dd6f7399bd8e6ce5aebfe"
        }
      ]
    }
  ]
}
