{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.21.1",
    "version": "0.2.4-forge1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.4-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.4-forge1.1.7.jar",
          "size": 52657282,
          "sha512": "abe867f06365afc09b5b03fd7211e6b1ee6ce78bc42325a331164812673f26fd79cda4b90c464644b4201fa7d826318f6869e9879e25e54c1969b5fc991bb07d",
          "sha256": "52f64080a638b9acaac1e78fba7f60c98e14b2789b63cc133a299ebafe651351",
          "sha1": "9b9b09225480931e5301d42af53bce5a5234684a",
          "md5": "a07e85b7d2d1f91e1c431f81e169a660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.5+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784174"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6914081"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.21.59"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.21.9"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.744"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "flashback",
          "version": {
            "requires": "pOGQFvgK"
          }
        },
        {
          "group": "com.moulberry",
          "module": "lattice",
          "version": {
            "requires": "1.2.18"
          },
          "attributes": {
            "earth.terrarium.cloche.modLoader": "fabric"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.4-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.4-forge1.1.7.jar",
          "size": 52657282,
          "sha512": "abe867f06365afc09b5b03fd7211e6b1ee6ce78bc42325a331164812673f26fd79cda4b90c464644b4201fa7d826318f6869e9879e25e54c1969b5fc991bb07d",
          "sha256": "52f64080a638b9acaac1e78fba7f60c98e14b2789b63cc133a299ebafe651351",
          "sha1": "9b9b09225480931e5301d42af53bce5a5234684a",
          "md5": "a07e85b7d2d1f91e1c431f81e169a660"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.4-forge1.1.7-sources.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.4-forge1.1.7-sources.jar",
          "size": 48888767,
          "sha512": "2f5ad8f5e09a0b011061c4357f5047c5a08f9f5f99236a89e977d9315b7189d290d2fbc69075f64265be2dac8e49cd2a27689d000c32294e1d347f449cbcf328",
          "sha256": "5bdacd1ce178c1ce449f8bfa57844ad5a39bb207f33d2476a126150ca2410cbc",
          "sha1": "36d71092dfaee14d9557899c3668801df1031c8c",
          "md5": "a3d37cfffbb3275e3fb616a1217b0de6"
        }
      ]
    }
  ]
}
