{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "resources",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "resources-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "resources-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 841137,
          "sha512": "2745416e1dbbeed242968629badc2c4f0bc52101aac38124d9908d04947d43cdd3719dd0d8cd33454d9a83b2c6b8a337b712207c13357f607692abac36d6bae6",
          "sha256": "c649c64f26d5cdf8855f3b55e1a5af118c5171062af2f4b98e361f563fb67144",
          "sha1": "881740ced7606c8e3951aca899c44ab9681d793a",
          "md5": "40d2c741b4054ca25f80a698eb0c6091"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "registry",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "resources-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "resources-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 841137,
          "sha512": "2745416e1dbbeed242968629badc2c4f0bc52101aac38124d9908d04947d43cdd3719dd0d8cd33454d9a83b2c6b8a337b712207c13357f607692abac36d6bae6",
          "sha256": "c649c64f26d5cdf8855f3b55e1a5af118c5171062af2f4b98e361f563fb67144",
          "sha1": "881740ced7606c8e3951aca899c44ab9681d793a",
          "md5": "40d2c741b4054ca25f80a698eb0c6091"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resources-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "resources-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 84703,
          "sha512": "ccc91d2afa232a19cf76d014848b06a91fff5c6fcb3b2b07970c2072cc04786ac5276e779f3967835a4a3b451ecdb5c5d5baaf7024126f387b97710ede2c801e",
          "sha256": "97ba89ef2d14bbf06da63ea8c7475ca9641980bddfd906083c1eae70a5d7b299",
          "sha1": "60a8c721d36dd21270e67f97762e42af66861765",
          "md5": "cf8ab3b3cf247ed5b31350ac5fc75104"
        }
      ]
    }
  ]
}
