{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.20.1",
    "version": "0.5.0-forge1.1.7-hotfix2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.5.0-forge1.1.7-hotfix2.jar",
          "url": "TACZ-Refabricated-1.20.1-0.5.0-forge1.1.7-hotfix2.jar",
          "size": 52683766,
          "sha512": "8342c08cb48dbf5aa2ef9216b9bbebe427d5a9977e52eba1a823b70a691dd91a2e94fcffb16276215367cfb8b63252f9913b4fa8f98e54ad55de6beb3ff3aff7",
          "sha256": "ee76ba0941932f465e4bd8670f22920c1ffe34bf69a3d114732c460690c270be",
          "sha1": "cf307f84b468c4fd83d76349a2b547cd9f31ce6f",
          "md5": "1bd6e810dd24212d5561d3b15d84dae4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784146"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "1.20.X-1.2.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.8-1.20.1-alpha-fabric.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.104"
          }
        },
        {
          "group": "curse.maven",
          "module": "spark-361579",
          "version": {
            "requires": "4738953"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6902843"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826546"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.5.0-forge1.1.7-hotfix2.jar",
          "url": "TACZ-Refabricated-1.20.1-0.5.0-forge1.1.7-hotfix2.jar",
          "size": 52683766,
          "sha512": "8342c08cb48dbf5aa2ef9216b9bbebe427d5a9977e52eba1a823b70a691dd91a2e94fcffb16276215367cfb8b63252f9913b4fa8f98e54ad55de6beb3ff3aff7",
          "sha256": "ee76ba0941932f465e4bd8670f22920c1ffe34bf69a3d114732c460690c270be",
          "sha1": "cf307f84b468c4fd83d76349a2b547cd9f31ce6f",
          "md5": "1bd6e810dd24212d5561d3b15d84dae4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.5.0-forge1.1.7-hotfix2-sources.jar",
          "url": "TACZ-Refabricated-1.20.1-0.5.0-forge1.1.7-hotfix2-sources.jar",
          "size": 48832738,
          "sha512": "d860ad7d4454e20262f77e1545656c3f301c7ea8a7203b5162477070f0c15b92b9fe430aa0bc6460fa57fe404a99b57d2527776152ceec87b91c31e5afe79a44",
          "sha256": "3414cf252772fbd66e1f2f8054bbe1326e3172aadfa37460a38a4c005fcdbd03",
          "sha1": "2bf3c68f30c7a340404a1293524f1f641805ea1f",
          "md5": "120b6760c65a69e947deddeda6e5ac5f"
        }
      ]
    }
  ]
}
