{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.4+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "size": 6014547,
          "sha512": "1646e7dd49c0cf4739a0d7d2fcefee2a5e4728e7b2424087e0c64ccbc63ee2c5c22271c6d43010122581a5983dc99a5fbe0396f987bfa7b553e9f5fe14f6ff1e",
          "sha256": "e27e8e6d223224cac6e39aa1092d25de5020e531957ba470a080c0ec4a6a01da",
          "sha1": "2831a2b6caee4147f36fb8580b85188dca305b9b",
          "md5": "f9c7eed99073de1c907a911c04fccf3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.1.3-Resharped-1.8.60"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "size": 6014547,
          "sha512": "1646e7dd49c0cf4739a0d7d2fcefee2a5e4728e7b2424087e0c64ccbc63ee2c5c22271c6d43010122581a5983dc99a5fbe0396f987bfa7b553e9f5fe14f6ff1e",
          "sha256": "e27e8e6d223224cac6e39aa1092d25de5020e531957ba470a080c0ec4a6a01da",
          "sha1": "2831a2b6caee4147f36fb8580b85188dca305b9b",
          "md5": "f9c7eed99073de1c907a911c04fccf3a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.20.1-sources.jar",
          "size": 3801116,
          "sha512": "c32cce707ff18229d8692258fb0ef8291e26b2fbe7505abeb63e70c34555de2fc40da005f03d0c2f8f4d45c0b5aceceed93a1b5eaf31bc49bbe7e60fc69c3b55",
          "sha256": "a502ef71241189118097daaa6c6dbc3aeef04281ebffde88fe2a48a20eee2c7d",
          "sha1": "cbd352abf64347c7d2f162c181cd080a146f1c12",
          "md5": "17c3e2da08addf5c91c70c65eeb7db95"
        }
      ]
    }
  ]
}
