{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.4+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "size": 6014400,
          "sha512": "58497946430f7a52a04c4fca1e93400d74236a775791122c13392dfe4a2be3ce170b4a98b2370d89b3d6086760d85f5475395b1ca41c6092bfc885eb3edfe5c8",
          "sha256": "25bf26c1c1238684fb64b8cdff31fdf308cc5ca5da99bbeb8a789bb086200442",
          "sha1": "175f42b1bf7ee194eeac10cdcb02277ca2039528",
          "md5": "62ef453b3233a9a927097404840397bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.1.3-Resharped-1.8.60"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.20.1.jar",
          "size": 6014400,
          "sha512": "58497946430f7a52a04c4fca1e93400d74236a775791122c13392dfe4a2be3ce170b4a98b2370d89b3d6086760d85f5475395b1ca41c6092bfc885eb3edfe5c8",
          "sha256": "25bf26c1c1238684fb64b8cdff31fdf308cc5ca5da99bbeb8a789bb086200442",
          "sha1": "175f42b1bf7ee194eeac10cdcb02277ca2039528",
          "md5": "62ef453b3233a9a927097404840397bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.4+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.4+mc1.20.1-sources.jar",
          "size": 3801077,
          "sha512": "e1e26093d5e215d46ba873b169a83ed54e642ebc045bd30e4d0058f23027da6cf25ca51341160146f9882dea236a8a1d36ec6e49efd63edd847b632e776f034a",
          "sha256": "8400ceb51b400335aabe040d180221bbdc71ec8190df64da39b42a0247ade5ed",
          "sha1": "ae855d467764f9d4278b37a38b938d7851b2c67a",
          "md5": "52a0e3c28563bdb1e12ad99af713a76b"
        }
      ]
    }
  ]
}
