{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.3.2-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.2-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.2-Resharped-1.8.61.jar",
          "size": 8548487,
          "sha512": "0699ebcf27c214c9b20a65158998a1fc19d97f5da71d8f9f67203c1e43dcb80b8e1ea01c844ffc0a253dc303265ebce13d4cb7f1c2a58c01c4623a033a25ae87",
          "sha256": "9a420ef70fefd1bb81fbbb6189d6735bdcfb9b0f7acf29f4a1e76f1b1585c127",
          "sha1": "6e1f88547a6c4d711b3181de598e405fbba847ea",
          "md5": "7de303d7e3e0b07c8868460250e6e40e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.2-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.2-Resharped-1.8.61.jar",
          "size": 8548487,
          "sha512": "0699ebcf27c214c9b20a65158998a1fc19d97f5da71d8f9f67203c1e43dcb80b8e1ea01c844ffc0a253dc303265ebce13d4cb7f1c2a58c01c4623a033a25ae87",
          "sha256": "9a420ef70fefd1bb81fbbb6189d6735bdcfb9b0f7acf29f4a1e76f1b1585c127",
          "sha1": "6e1f88547a6c4d711b3181de598e405fbba847ea",
          "md5": "7de303d7e3e0b07c8868460250e6e40e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.2-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.2-Resharped-1.8.61-sources.jar",
          "size": 3556349,
          "sha512": "5db08f7e9ea617e71afdb3ae2d75a2ae21fa68ea9480b4b6869e749e39be4de30c6e06a914791c3dbfbdeef90e5a6052c64acec67097839c9ef6670a6636f036",
          "sha256": "e456ebd31313d0d29fd36db0a92555d7ae220c365eee5c8fc993e289ff7288aa",
          "sha1": "9842c65cf53836713e4c01565925d03686587ba3",
          "md5": "bcdc5134484eb3e925118fe8ec9d2de3"
        }
      ]
    }
  ]
}
