{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "tlmo-additions",
    "version": "1.0.1+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tlmo-additions-1.0.1+mc1.20.1.jar",
          "url": "tlmo-additions-1.0.1+mc1.20.1.jar",
          "size": 443092,
          "sha512": "c922a2e79d227c7a48736ffdbd808dfd4ee109212c3aa248e29eee4d3c8cc720a76c876cb6de61e566938ee674c88fa5af788ce9db444bd816d7d8dd031ee42d",
          "sha256": "f7e4657fd0d3a0ef95ed921644c248d11e730143ab05ac84578ec91e61722521",
          "sha1": "dcd181703002a1d52f648d7b8b312200c1f5184a",
          "md5": "20df1f61a7a4782494683a99c94cbb3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.7+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.6.4-forge1.5.0"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "explorers-compass-491794",
          "version": {
            "requires": "4712192"
          }
        },
        {
          "group": "curse.maven",
          "module": "natures-compass-252848",
          "version": {
            "requires": "4712188"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.136"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric",
          "version": {
            "requires": "6.0.8.1+build.1744-mc1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "tlmo-additions-1.0.1+mc1.20.1.jar",
          "url": "tlmo-additions-1.0.1+mc1.20.1.jar",
          "size": 443092,
          "sha512": "c922a2e79d227c7a48736ffdbd808dfd4ee109212c3aa248e29eee4d3c8cc720a76c876cb6de61e566938ee674c88fa5af788ce9db444bd816d7d8dd031ee42d",
          "sha256": "f7e4657fd0d3a0ef95ed921644c248d11e730143ab05ac84578ec91e61722521",
          "sha1": "dcd181703002a1d52f648d7b8b312200c1f5184a",
          "md5": "20df1f61a7a4782494683a99c94cbb3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tlmo-additions-1.0.1+mc1.20.1-sources.jar",
          "url": "tlmo-additions-1.0.1+mc1.20.1-sources.jar",
          "size": 259715,
          "sha512": "9c2158e379ec48cd8a45ea986d301a2abf9a7779810350a58bc7dd53c2ace93535b3720b7ff757fd6331a34ec8617ab5c66a3371caac97b37946fead94429adf",
          "sha256": "7a9c122c3706d54cfa5350a6e2acbd00bc08cc97e0f5c466805f8f9054e854fb",
          "sha1": "9347506dd5a7f3eea8ce66b6115eb64bec2df15c",
          "md5": "5ba6d392dd96430366d8edac97543d55"
        }
      ]
    }
  ]
}
