{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.1+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.22.1.316"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.1+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.1+mc1.21.1.jar",
          "size": 51380964,
          "sha512": "fa1d85e7e7deceaf282ed89fc5c6493ff523fa85e24741ee509b6e6cc24ddee2f359d2a5333554865ecd2d9b379a8813921942c22200debbe318fa8feacaf313",
          "sha256": "0e604845ee6a996dfaa1c2bf24d7d4d27ef3f1fa96a1c8ad87bf7ee17ddaa014",
          "sha1": "d484747fb49e18397e0fe0c71554ba260c275942",
          "md5": "32cb663442cbf7ec50fcb2f950219aab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.0-Resharped-1.8.61"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.79+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.79+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.1+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.1+mc1.21.1.jar",
          "size": 51380964,
          "sha512": "fa1d85e7e7deceaf282ed89fc5c6493ff523fa85e24741ee509b6e6cc24ddee2f359d2a5333554865ecd2d9b379a8813921942c22200debbe318fa8feacaf313",
          "sha256": "0e604845ee6a996dfaa1c2bf24d7d4d27ef3f1fa96a1c8ad87bf7ee17ddaa014",
          "sha1": "d484747fb49e18397e0fe0c71554ba260c275942",
          "md5": "32cb663442cbf7ec50fcb2f950219aab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.1+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.1+mc1.21.1-sources.jar",
          "size": 50205303,
          "sha512": "3bce1a17a8c955bb1dbf7ddec10c3d0125f5b4fd83ab5dc774df5db7a7117c40d00ca80c5279c762f2d980553fd9df669a1a4a969ac315a816f6e2c77616ec30",
          "sha256": "fcab596a47185b63dbdb64ade505281326793e833dc1927bfc6d240603b8023c",
          "sha1": "bc4e1afbcb53bc1638573cbbe0692197fe6bdc60",
          "md5": "5f5524385fcb1c352899e0ad55b6627a"
        }
      ]
    }
  ]
}
