{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.21.1",
    "version": "0.2.1-forge1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.1-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.1-forge1.1.7.jar",
          "size": 52553466,
          "sha512": "f10eba43826e39270fefb9311acb1e31665c8a3c99f4796986915183412f82197be9bb2ad5c41ad16566a2d299f07dd3827cbdfbcad1b7b33f6a6d04f1cbeff7",
          "sha256": "9072551fbf4b914048cbcb6f129ba6ed573727e420daeb93c3baf88dcb0c587c",
          "sha1": "dcc73475ec210bbeaadc44b516163b7d0181514e",
          "md5": "27cd0f80faa2394254fa990c2da27bfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.5+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784174"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6914081"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.21.59"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.21.9"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.744"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "flashback",
          "version": {
            "requires": "pOGQFvgK"
          }
        },
        {
          "group": "com.moulberry",
          "module": "lattice",
          "version": {
            "requires": "1.2.18"
          },
          "attributes": {
            "earth.terrarium.cloche.modLoader": "fabric"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.1-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.1-forge1.1.7.jar",
          "size": 52553466,
          "sha512": "f10eba43826e39270fefb9311acb1e31665c8a3c99f4796986915183412f82197be9bb2ad5c41ad16566a2d299f07dd3827cbdfbcad1b7b33f6a6d04f1cbeff7",
          "sha256": "9072551fbf4b914048cbcb6f129ba6ed573727e420daeb93c3baf88dcb0c587c",
          "sha1": "dcc73475ec210bbeaadc44b516163b7d0181514e",
          "md5": "27cd0f80faa2394254fa990c2da27bfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.1-forge1.1.7-sources.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.1-forge1.1.7-sources.jar",
          "size": 48756802,
          "sha512": "a2668ad61c2897fc326fec40503119158ebf3f7fa4a09bf87b4393b9e278c4cc4f3f0f689722956010d07a6c9e740d502627fb0f685992834da903bf8b6dd55b",
          "sha256": "d1f5e0b974b0887c7ffd70d0b9a440615897f23d1e7af9d9bc956baca143b1d3",
          "sha1": "566c466c28cda82486d83386e6863c4aec27aaf6",
          "md5": "2c3b4bbe3478dbb37b6074b19223ea7a"
        }
      ]
    }
  ]
}
