{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.4.0-Resharped-1.9.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "size": 9217764,
          "sha512": "7c1f301c1966b0f9360ba376658e0fe8034210c92982fbf2b01b8fd16fbd7222601e2b8a71f5e8d4333e5a0bda1424905db2706e1dcadde10fde91c6aa8886a2",
          "sha256": "dbd7601a6ec6e9e3fb0f58bca2cb5970b1132e6643f76f015d95977faa93191a",
          "sha1": "38f29a88f7db0e371aabe197c3d316a09b70ccce",
          "md5": "59b55f97639229b425a4e236a2e457eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "size": 9217764,
          "sha512": "7c1f301c1966b0f9360ba376658e0fe8034210c92982fbf2b01b8fd16fbd7222601e2b8a71f5e8d4333e5a0bda1424905db2706e1dcadde10fde91c6aa8886a2",
          "sha256": "dbd7601a6ec6e9e3fb0f58bca2cb5970b1132e6643f76f015d95977faa93191a",
          "sha1": "38f29a88f7db0e371aabe197c3d316a09b70ccce",
          "md5": "59b55f97639229b425a4e236a2e457eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65-sources.jar",
          "size": 3555516,
          "sha512": "066534e29656afe4b1357fa27e59cee5ea981150acdf2f05ebcc3d02cf6238e4514a971be538dad2b3a8713bf1472c34ee38fb43979ceb28449871ba810a1524",
          "sha256": "204631166247f66f774c62587d75d59bd7517f41998a6cf2965f8db212b6ed7a",
          "sha1": "88cc4463f0941b65f05c1b20493e6a9c591ddc7c",
          "md5": "6d7d070bfd86763b8ea9a45ae090cc20"
        }
      ]
    }
  ]
}
