{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.4.0-Resharped-1.9.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "size": 9217764,
          "sha512": "e47a9ddbc89092219c16add9ba0f742bce0c3011471f2a49b9dc00959411ac2415c1ae291b5affc3f807801d5ed431d65af76c5a6364c5958806cf2b37c6df1f",
          "sha256": "689bb0c0ff3379c528e56b34d0805f307c2e59f53f6d14845e184855bed65649",
          "sha1": "9ecaf1874f65c6ce06af83c4b8d0b3d70cbeb6a3",
          "md5": "04a74a464866c380e5aa8de66c25ea8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65.jar",
          "size": 9217764,
          "sha512": "e47a9ddbc89092219c16add9ba0f742bce0c3011471f2a49b9dc00959411ac2415c1ae291b5affc3f807801d5ed431d65af76c5a6364c5958806cf2b37c6df1f",
          "sha256": "689bb0c0ff3379c528e56b34d0805f307c2e59f53f6d14845e184855bed65649",
          "sha1": "9ecaf1874f65c6ce06af83c4b8d0b3d70cbeb6a3",
          "md5": "04a74a464866c380e5aa8de66c25ea8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.0-Resharped-1.9.65-sources.jar",
          "size": 3555518,
          "sha512": "83441d5542aca3f47abdbdbe1aa904d5dcfd177ffe778fd306215194530534afbaf7bf211666e81b885469837d594acce2a9b2334a831d01da6d7775c7189a0f",
          "sha256": "c259b44cab261824160ab74293a0f253d36cbd2169559ab8dfa6b800b73b23a2",
          "sha1": "0ff95946ab191249eb6a0b9ff94a539e808ea578",
          "md5": "b688493c2464a6b01b349a3aea2f3815"
        }
      ]
    }
  ]
}
