{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "transfer",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "transfer-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 775502,
          "sha512": "435dc4c0b67aec7e53a659a7ed6438f79c5feb48d6b9ce979a55f17b673b5a4801537fd8a1f7e8a9641a25c3d55a3fe7e03119f629bb71c05f666cc479def34f",
          "sha256": "e7fab16b6d1e1bead3c78b62db897775dfa4fda2ce659ceade1332ddaf53cccf",
          "sha1": "7c1c7f6648dcaec457d101f0978b33fdb36dfe41",
          "md5": "bbbd05700aa38abc946b8f80d1dec8e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "transfer-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 775502,
          "sha512": "435dc4c0b67aec7e53a659a7ed6438f79c5feb48d6b9ce979a55f17b673b5a4801537fd8a1f7e8a9641a25c3d55a3fe7e03119f629bb71c05f666cc479def34f",
          "sha256": "e7fab16b6d1e1bead3c78b62db897775dfa4fda2ce659ceade1332ddaf53cccf",
          "sha1": "7c1c7f6648dcaec457d101f0978b33fdb36dfe41",
          "md5": "bbbd05700aa38abc946b8f80d1dec8e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transfer-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "transfer-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 65601,
          "sha512": "2164dc3ffab63227f8fb8eb242e9bbfbd276ba1462ca4e885745432ccafb78721bfcbbe3d295b3e63708927160922bfaa81ab2c6345e80d5f2f0b8e7e6b5d4fe",
          "sha256": "b5f7ebc1a4e1669fbe32e454ed382527d6ace4f2335493e4b29b57342f9d1e5f",
          "sha1": "8b813d8a851938835e2ef849d5eec34a54e69d81",
          "md5": "0d6d805e189c452ce5a8e1683cdc865b"
        }
      ]
    }
  ]
}
