{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.20.1-1.1.3-Resharped-1.8.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.1.3-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.20.1-1.1.3-Resharped-1.8.60.jar",
          "size": 7984722,
          "sha512": "ebfa42da22628b04ce2edbfcffa8b5cbac09ba9ee1c722c8d872c4de7fbb6ad95a86fc96b5fd45a5df734d63288a493329a5f0aaf69f2b4da9ca8339c9be763b",
          "sha256": "76307c2d78b0a10a3c9d0af1feb235b6c62173905c0122649738cf566ba19ca2",
          "sha1": "fd2cd6c9b7eb8d27ce5eead3e8a079902ba7a0a2",
          "md5": "f3aa65eae6a3886912973f01464af0da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "attributes",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "emi-580555",
          "version": {
            "requires": "6420944"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5.1-1.20.1-alpha-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6815736"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6608232"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.105"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180902"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "5984629"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-83-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.1.3-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.20.1-1.1.3-Resharped-1.8.60.jar",
          "size": 7984722,
          "sha512": "ebfa42da22628b04ce2edbfcffa8b5cbac09ba9ee1c722c8d872c4de7fbb6ad95a86fc96b5fd45a5df734d63288a493329a5f0aaf69f2b4da9ca8339c9be763b",
          "sha256": "76307c2d78b0a10a3c9d0af1feb235b6c62173905c0122649738cf566ba19ca2",
          "sha1": "fd2cd6c9b7eb8d27ce5eead3e8a079902ba7a0a2",
          "md5": "f3aa65eae6a3886912973f01464af0da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.1.3-Resharped-1.8.60-sources.jar",
          "url": "slashblade-refabricated-1.20.1-1.1.3-Resharped-1.8.60-sources.jar",
          "size": 3648044,
          "sha512": "b7ccb3db196f152c0412acc8deb81d5a36f7d8642dcea487b824dedf5dd045645bd468f22a3e41111d4d9240ad7132ad4ded172915ed288697e2ad8f3110164a",
          "sha256": "d65dd711c2259688d8130798bafbd707fe2d0ceb079d264d28cf1c7ca6585155",
          "sha1": "81c69191751f71a6f7d849c7a8aa1659b1835501",
          "md5": "2fc30dc99f3c932a0c32ef3078b92cfb"
        }
      ]
    }
  ]
}
