{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.6-Resharped-1.8.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.6-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.6-Resharped-1.8.60.jar",
          "size": 7133474,
          "sha512": "21fc918274a70b27b5a345dd265bd64a113db9d894baddbc3cc4ca4142d179458661c28ca92230210f67924c5deb0d8bdbbf4baa3fc5930116555d862297696a",
          "sha256": "aea0663a3837d54073844fcc1deeb1bedff74aa9b6c7298e96a84320aa664afd",
          "sha1": "c9ac946485abe31d62d4922bf77d45096fedcd49",
          "md5": "b0de2271c18227673e80bb3fc1831c0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.6-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.6-Resharped-1.8.60.jar",
          "size": 7133474,
          "sha512": "21fc918274a70b27b5a345dd265bd64a113db9d894baddbc3cc4ca4142d179458661c28ca92230210f67924c5deb0d8bdbbf4baa3fc5930116555d862297696a",
          "sha256": "aea0663a3837d54073844fcc1deeb1bedff74aa9b6c7298e96a84320aa664afd",
          "sha1": "c9ac946485abe31d62d4922bf77d45096fedcd49",
          "md5": "b0de2271c18227673e80bb3fc1831c0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.6-Resharped-1.8.60-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.6-Resharped-1.8.60-sources.jar",
          "size": 3555614,
          "sha512": "91c866059cc2dfef31b7c6474a9cc18ef34bea331c3287df51861a14a9dff7b55de6b6158d94cb89cfc0d6f402e6f8ad9892e07b5effb7bb7f2b1360050671bd",
          "sha256": "f4c060990558b15398ca8e58efa55f7228f0a708e0081e67842546423a458838",
          "sha1": "41e3e062cd645cadaddca5222e9180c9ce69c346",
          "md5": "0a34d9c175cb94b347b78ce2d6deda7d"
        }
      ]
    }
  ]
}
