{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.7+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.7+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.7+mc1.21.1.jar",
          "size": 50855530,
          "sha512": "90af1ef6f9cebded5a76bfdbdbbc406b09c86614f22394343f469768abc2ab50922cddf5d9d19151608c21afed4a45f78944d5cf0e2c29b66ae2a5a6eab67941",
          "sha256": "abf09ecf973e37c6e5e81e19bdb711693622683f939dec39842f582a78735e77",
          "sha1": "5b24a5aab4a0beb724f7f57ad0e3f6cc5ab12863",
          "md5": "d4fd3808abd7020bcb9719f1d603ed9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.3-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.7+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.7+mc1.21.1.jar",
          "size": 50855530,
          "sha512": "90af1ef6f9cebded5a76bfdbdbbc406b09c86614f22394343f469768abc2ab50922cddf5d9d19151608c21afed4a45f78944d5cf0e2c29b66ae2a5a6eab67941",
          "sha256": "abf09ecf973e37c6e5e81e19bdb711693622683f939dec39842f582a78735e77",
          "sha1": "5b24a5aab4a0beb724f7f57ad0e3f6cc5ab12863",
          "md5": "d4fd3808abd7020bcb9719f1d603ed9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.7+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.7+mc1.21.1-sources.jar",
          "size": 50564923,
          "sha512": "902d1db3588862c4fb4f5993f0a94c9c4ab75a39d722df42b4f4e6fa42a6917e7207fb68d9b0428b9fff534fd49cf8dad2158673bf652d2dc082f3303820a644",
          "sha256": "e9a26fb239bbbc7c92384b748526fe3e94dd7e1c4cd9b1d58aa773abd8830cd8",
          "sha1": "5b69b24db5b6be39a00fb0d3313b53d9cf25091d",
          "md5": "f9a3fafafeaeaf68cb9e4bc6e4ec180c"
        }
      ]
    }
  ]
}
