{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "obj_loader",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "obj_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "obj_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 710114,
          "sha512": "95d9779d80ff08e324637fe02d775572116ee1245061b4bd0c4bdfbdeef168a83bc4cd9e6efec8b70b076f75d46e7c0894b2fe765e63dc8055eb07a887184236",
          "sha256": "a0a1ac0322a6ab962926f9fb602d92e8caaacc99616868089ee0f47df6629b8c",
          "sha1": "e96c065125d0611ca0c3b030984d5329cee0784f",
          "md5": "e177547d248e1f904a348386e964678c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "obj_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "obj_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 710114,
          "sha512": "95d9779d80ff08e324637fe02d775572116ee1245061b4bd0c4bdfbdeef168a83bc4cd9e6efec8b70b076f75d46e7c0894b2fe765e63dc8055eb07a887184236",
          "sha256": "a0a1ac0322a6ab962926f9fb602d92e8caaacc99616868089ee0f47df6629b8c",
          "sha1": "e96c065125d0611ca0c3b030984d5329cee0784f",
          "md5": "e177547d248e1f904a348386e964678c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "obj_loader-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "obj_loader-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 14139,
          "sha512": "2cfd1409c0b1425ae71e8370aeea27c1d0a99a1cc070c8e098d2d188df18eae2d22abddd811f28ad9205969e2345baa421048902bc5bb34d1a86a94ec5b39bcc",
          "sha256": "3dafc622a31d3de41f32e3ef88819cb58b47b8d4c897b3e51b8cb22d96b336c1",
          "sha1": "0a43810547df5bb7867b51801c3f9fa209b2e88e",
          "md5": "3d0acd796cdf6aeb7e19a3e318beb3de"
        }
      ]
    }
  ]
}
