{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.4-Resharped-1.8.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.4-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.4-Resharped-1.8.60.jar",
          "size": 7134251,
          "sha512": "5decbe1cef16881e09011bb0f3b005ff11337c3ef2112fff69b813482679aa933591531b162a5426a2a0f067b64db69be10ad162de67f6831a47f7d34037d876",
          "sha256": "1beaa6a216c717537c3e021880ba1701dbfceb84ea6887d0ebe45d7e9c0606c9",
          "sha1": "eb2bc192cff3dc0ea94a60ce63acd4950ae11925",
          "md5": "c55992d1a496d1a15d46d98acb4341b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.4-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.4-Resharped-1.8.60.jar",
          "size": 7134251,
          "sha512": "5decbe1cef16881e09011bb0f3b005ff11337c3ef2112fff69b813482679aa933591531b162a5426a2a0f067b64db69be10ad162de67f6831a47f7d34037d876",
          "sha256": "1beaa6a216c717537c3e021880ba1701dbfceb84ea6887d0ebe45d7e9c0606c9",
          "sha1": "eb2bc192cff3dc0ea94a60ce63acd4950ae11925",
          "md5": "c55992d1a496d1a15d46d98acb4341b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.4-Resharped-1.8.60-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.4-Resharped-1.8.60-sources.jar",
          "size": 3555886,
          "sha512": "ecae8385b200883f55a5c2cb4e1d1717012ebe8e3561f6eb8f64eaaf8f3ff8fe75bf4099b80fc89c2b7e432ff05fe948a97296b945ee4a1440bedbf55dc4b49b",
          "sha256": "435ab1010b9524d32c525ece8e89c99aa46aa9da9a4a7f1244363236ac9eeb13",
          "sha1": "42e4aa4207f99aa4ff5fad7722dfc1b5ec57dff6",
          "md5": "13a1602c4321fc867e2ecf63132f7a8b"
        }
      ]
    }
  ]
}
