{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.21.1",
    "version": "0.2.0-forge1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.0-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.0-forge1.1.7.jar",
          "size": 52580357,
          "sha512": "a546d00e59ae9a7724b85d8256ec6636efb456ca93afdc733db2cfc494d6385cf4cc5dbc936ce3ab667630fa0e23252aa5e5829df5bf781fed4358c7bfbc4dd4",
          "sha256": "e36f987e46f68b02d8ad28a7cec1430ff4076b333e39b31e145b55a03fc7d385",
          "sha1": "4811e1ea8f9e977de23cc569e96cebbc32253c83",
          "md5": "0cc3ac5183aac60cbb46e9b49878035f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.5+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784174"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6914081"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.21.59"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.21.9"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.744"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "flashback",
          "version": {
            "requires": "pOGQFvgK"
          }
        },
        {
          "group": "com.moulberry",
          "module": "lattice",
          "version": {
            "requires": "1.2.18"
          },
          "attributes": {
            "earth.terrarium.cloche.modLoader": "fabric"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.0-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.0-forge1.1.7.jar",
          "size": 52580357,
          "sha512": "a546d00e59ae9a7724b85d8256ec6636efb456ca93afdc733db2cfc494d6385cf4cc5dbc936ce3ab667630fa0e23252aa5e5829df5bf781fed4358c7bfbc4dd4",
          "sha256": "e36f987e46f68b02d8ad28a7cec1430ff4076b333e39b31e145b55a03fc7d385",
          "sha1": "4811e1ea8f9e977de23cc569e96cebbc32253c83",
          "md5": "0cc3ac5183aac60cbb46e9b49878035f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.0-forge1.1.7-sources.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.0-forge1.1.7-sources.jar",
          "size": 48789777,
          "sha512": "538fc7e1851d6aba713e95ac1a2246457722426e1ce9f3f77427918788b23d6f052e35148cac68c2830ed6aa6eaf4883d26c4e539bca3cbde70f029bea7bcd6e",
          "sha256": "a6ca1b378d7cf8a22a7b309f5b28f6ed3c0be6b0b37bd1abd3948fd346660d9b",
          "sha1": "f7301d9cdc1e099d028ba861acdcb5117f8ba2dc",
          "md5": "7b63e2f860f6fb70096c9e1851564622"
        }
      ]
    }
  ]
}
