{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "client_extensions",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "client_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "client_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 689089,
          "sha512": "c17ffcc3831645092bf1b7b759b28a0e435c06c8e393bdf7da8f22eb33d62c5ad331d714678fd4ee0abbb202b62e9dda35a02678197a646abb7b723994940f91",
          "sha256": "c5edfc2d1e2a8863157188c2a7067f64642aac7e82ed09119c3cc1d10b2a53dc",
          "sha1": "a248edbec65b2d8438c1dd7a7a3972e47db36af6",
          "md5": "6ec2dffc5d988d9179d66fc73c269dee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "client_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "client_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 689089,
          "sha512": "c17ffcc3831645092bf1b7b759b28a0e435c06c8e393bdf7da8f22eb33d62c5ad331d714678fd4ee0abbb202b62e9dda35a02678197a646abb7b723994940f91",
          "sha256": "c5edfc2d1e2a8863157188c2a7067f64642aac7e82ed09119c3cc1d10b2a53dc",
          "sha1": "a248edbec65b2d8438c1dd7a7a3972e47db36af6",
          "md5": "6ec2dffc5d988d9179d66fc73c269dee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client_extensions-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "client_extensions-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 9193,
          "sha512": "076056ea5c90d06738deadae3a2731a53fadf673543e1527400c69eaee7b425d70ddaf1e8afe0d66e8e931eff84617117ef6911cf5049dbf1047c71421384a1d",
          "sha256": "2d3691827006b333da0208bb94ccfbafd0951a410397cd9b3c7b74bd9f065a96",
          "sha1": "912a7d479eafcc485c396392fb51d3c5c73785dc",
          "md5": "05c7968d80b0a9e8d05bbc5c8e3b0d7f"
        }
      ]
    }
  ]
}
