{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.20.1-1.1.2-Resharped-1.8.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.1.2-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.20.1-1.1.2-Resharped-1.8.57.jar",
          "size": 7983962,
          "sha512": "0a3e9272a456fead2bed364eea7137bd1fa8f6075ca5c8dadaa2cbdfc53d31d62cca4f464b624b0f2268814f5e1feaee8c72a57b6f7dce2a1a2944459a46e98e",
          "sha256": "5bc968eb4963f82e35d11c0c6d411243b2fdf6338a476a9ce1682547dc254707",
          "sha1": "c96207778e90d91904c4136bc0ca7d652a54a724",
          "md5": "2afa02e0fe61f2006b584a724f93f39b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "attributes",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "emi-580555",
          "version": {
            "requires": "6420944"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5.1-1.20.1-alpha-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6815736"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6608232"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.105"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180902"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "5984629"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-83-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.1.2-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.20.1-1.1.2-Resharped-1.8.57.jar",
          "size": 7983962,
          "sha512": "0a3e9272a456fead2bed364eea7137bd1fa8f6075ca5c8dadaa2cbdfc53d31d62cca4f464b624b0f2268814f5e1feaee8c72a57b6f7dce2a1a2944459a46e98e",
          "sha256": "5bc968eb4963f82e35d11c0c6d411243b2fdf6338a476a9ce1682547dc254707",
          "sha1": "c96207778e90d91904c4136bc0ca7d652a54a724",
          "md5": "2afa02e0fe61f2006b584a724f93f39b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.1.2-Resharped-1.8.57-sources.jar",
          "url": "slashblade-refabricated-1.20.1-1.1.2-Resharped-1.8.57-sources.jar",
          "size": 3647593,
          "sha512": "ea1d050860c01703254157fb09a635ce3e4fcdb7ccb945ccea3f84dde48f2c8520d84d37da3038ce474a67b2536f9674b2dbdddefc6059f1b20afe789e6f41f9",
          "sha256": "ef405b4736caf05b15c309a44ce06a28987cb24ca0a17242b605695c098e6d39",
          "sha1": "68a2cf7b38a0dbbe67d946d2e0c92bf464048274",
          "md5": "c1f65a8d43df937e771af0dd76632af7"
        }
      ]
    }
  ]
}
