{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.21.1",
    "version": "0.2.3-forge1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.3-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.3-forge1.1.7.jar",
          "size": 52655212,
          "sha512": "5a25d8cbd2ec7693ceee930296e1cc01edb9925f2f899637e6dc4f5de467716dd8fe54cf6431bb7e56013a6f260f6409e475751331daee7851ac098abf4bce3e",
          "sha256": "80ee064b9694ec24f82491e1e48ee201bb1811155b149b710477669bd3d8c10b",
          "sha1": "841c4802649aa3f096367ef67baed61ef240a868",
          "md5": "53854fed439fb06dcbc53e10f31252f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.5+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784174"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6914081"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.21.59"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.21.9"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.744"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "flashback",
          "version": {
            "requires": "pOGQFvgK"
          }
        },
        {
          "group": "com.moulberry",
          "module": "lattice",
          "version": {
            "requires": "1.2.18"
          },
          "attributes": {
            "earth.terrarium.cloche.modLoader": "fabric"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.3-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.3-forge1.1.7.jar",
          "size": 52655212,
          "sha512": "5a25d8cbd2ec7693ceee930296e1cc01edb9925f2f899637e6dc4f5de467716dd8fe54cf6431bb7e56013a6f260f6409e475751331daee7851ac098abf4bce3e",
          "sha256": "80ee064b9694ec24f82491e1e48ee201bb1811155b149b710477669bd3d8c10b",
          "sha1": "841c4802649aa3f096367ef67baed61ef240a868",
          "md5": "53854fed439fb06dcbc53e10f31252f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.2.3-forge1.1.7-sources.jar",
          "url": "TACZ-Refabricated-1.21.1-0.2.3-forge1.1.7-sources.jar",
          "size": 48887119,
          "sha512": "6ad581b9e5151b00731f9bcd318432e8be67189eded38726a0f40fb971f7292911425a8cc410a6db75e4d6b2685329ac49a9365d78031c6b3f904e42a11480f1",
          "sha256": "39f29d9925b8682b83ca14953645bbe42434769976a66ddf69680140c80d8ad1",
          "sha1": "8289fb7a59321208311cef4688a508825156384b",
          "md5": "7c09e8c16734689ac744e5b7b0b6d9c7"
        }
      ]
    }
  ]
}
