{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "client_events",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "client_events-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "client_events-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 822413,
          "sha512": "ede97b65c05db6e088163b9b60511773c54ebdcb495634e84bd76b18eb3e8139fd1dfefcf6bfdb3bb770f72977854e93e7554cc334754627e3227f5fe38c834f",
          "sha256": "7d2dcce9ff0db31ee568780b92f2c2a4320aa6bdb4b2924c3aa7d05828e2646d",
          "sha1": "c20fa3e8faad2cd2c0f9bd35cfdd4b31f5ffc2b9",
          "md5": "356c54a71bb587903daf9e590df3c1a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        },
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        }
      ],
      "files": [
        {
          "name": "client_events-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "client_events-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 822413,
          "sha512": "ede97b65c05db6e088163b9b60511773c54ebdcb495634e84bd76b18eb3e8139fd1dfefcf6bfdb3bb770f72977854e93e7554cc334754627e3227f5fe38c834f",
          "sha256": "7d2dcce9ff0db31ee568780b92f2c2a4320aa6bdb4b2924c3aa7d05828e2646d",
          "sha1": "c20fa3e8faad2cd2c0f9bd35cfdd4b31f5ffc2b9",
          "md5": "356c54a71bb587903daf9e590df3c1a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client_events-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "client_events-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 39408,
          "sha512": "bd3b3b90dd90d218062b1c71c20282b62da2840a15b5da37fa585c75743d5d674febff23906707c000b118792a95decfc4516d5cfa6eb9ebf29f0cb9a9e156b3",
          "sha256": "a48c3631e35ef1d61ae83833fbb91ea29b6be1fa7524d5219dbd0f8d67012e64",
          "sha1": "ece9b3481042fd726f8e575c3ed38d072e7c3006",
          "md5": "8c93aca585c5580d171f9d41d39cde1b"
        }
      ]
    }
  ]
}
