{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.3+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.3+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.3+mc1.20.1.jar",
          "size": 6014336,
          "sha512": "47a51122a189286a436fae09475cfde5e81e896e8e50c0c9859f0ea99ea94aa9c7d0afc9179dec824efeaffcb22e2c3c87b1090c0557deab6d49ba06691cc7f1",
          "sha256": "e9480c17a5d2653db5a2f2f487c57086e69848526a7c27036f31490d3c07ca49",
          "sha1": "a2df67c218ba74231ab6183c7f0ca5a312b5391d",
          "md5": "7531f331781fce79af2e8063af0d0b34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.1.1-Resharped-1.8.57"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.3+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.1.3+mc1.20.1.jar",
          "size": 6014336,
          "sha512": "47a51122a189286a436fae09475cfde5e81e896e8e50c0c9859f0ea99ea94aa9c7d0afc9179dec824efeaffcb22e2c3c87b1090c0557deab6d49ba06691cc7f1",
          "sha256": "e9480c17a5d2653db5a2f2f487c57086e69848526a7c27036f31490d3c07ca49",
          "sha1": "a2df67c218ba74231ab6183c7f0ca5a312b5391d",
          "md5": "7531f331781fce79af2e8063af0d0b34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.3+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.3+mc1.20.1-sources.jar",
          "size": 3801075,
          "sha512": "9fe058c51249fb348affbbf27f18c2bf6992c4dc637a01a562d54271d932f1f2775adbd8f8072bc123393dc4f55b232c2e76e0ba7ddd861249807131b8f3593b",
          "sha256": "f1fe43c53124415ca33cba3f88320b0519c90799baf604713d1dc279f8f88f94",
          "sha1": "c113903d62aea87ffe2f6d2eb7edde0506cae656",
          "md5": "70a7068630236d278c4129cca5de5b19"
        }
      ]
    }
  ]
}
