{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.0.0-Resharped-1.7.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.0.0-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.21.1-1.0.0-Resharped-1.7.55.jar",
          "size": 7122885,
          "sha512": "73fe997c60fc1841061a23a9d8b678a29d95b90a8c0a93415aa28a0dc3d35b1b69a03f6c1769c95c0721199970a4b742d3f520e1ad651fc414c45ca9b1f6f6f0",
          "sha256": "59fd757a6fca8a00e16e176d0cb8c939b261929786c0c6e975acb9e93e282d95",
          "sha1": "5978151284c6df4858b7d51f6f975cd976549ef6",
          "md5": "974316bfbdc0ae041eb747f42a94126a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.0.0-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.21.1-1.0.0-Resharped-1.7.55.jar",
          "size": 7122885,
          "sha512": "73fe997c60fc1841061a23a9d8b678a29d95b90a8c0a93415aa28a0dc3d35b1b69a03f6c1769c95c0721199970a4b742d3f520e1ad651fc414c45ca9b1f6f6f0",
          "sha256": "59fd757a6fca8a00e16e176d0cb8c939b261929786c0c6e975acb9e93e282d95",
          "sha1": "5978151284c6df4858b7d51f6f975cd976549ef6",
          "md5": "974316bfbdc0ae041eb747f42a94126a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.0.0-Resharped-1.7.55-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.0.0-Resharped-1.7.55-sources.jar",
          "size": 3547512,
          "sha512": "466810bcafa8801273fdc7100296e803116689c8d34686afefb2da90ae05e49cabf80a97fdabfa1f8a1f8814a296ada6fb2e1bb4cc072a545b4c828573f55695",
          "sha256": "1401aabc5394a730b25df796ca9f2b620fe8286a3aab4b5c821c876d1da8220b",
          "sha1": "af5927a7398f02a1edb5d60055b5a2ab80ea5360",
          "md5": "46195bef33791812055d7269045bfcc2"
        }
      ]
    }
  ]
}
