{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "goety-fabric",
    "version": "0.0.2-forge2.5.51.0+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "goety-fabric-0.0.2-forge2.5.51.0+mc1.20.1.jar",
          "url": "goety-fabric-0.0.2-forge2.5.51.0+mc1.20.1.jar",
          "size": 76331792,
          "sha512": "d7392949af7c50477bfde96c0cb62abc7312e91de6ffd3b8012739c0d26ea8a6ec8c7a230b7c5169cd7a2c2f74b78ea59320ce83a93e29c565dd03c946df00e2",
          "sha256": "c0608077c2d0275cde42feeacd0b82ec27e3be68b7af35caa4d97e4b13b0f399",
          "sha1": "f939059af04375c9723e7848cdac1b1007afde3f",
          "md5": "0ebd8378db1863026d072d08b0e02f22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.7+1.20.1"
          }
        },
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.15+1.20.1"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.github.emilyploszaj",
          "module": "step-height-entity-attribute",
          "version": {
            "requires": "v1.2.0"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-81-FABRIC"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "goety-fabric-0.0.2-forge2.5.51.0+mc1.20.1.jar",
          "url": "goety-fabric-0.0.2-forge2.5.51.0+mc1.20.1.jar",
          "size": 76331792,
          "sha512": "d7392949af7c50477bfde96c0cb62abc7312e91de6ffd3b8012739c0d26ea8a6ec8c7a230b7c5169cd7a2c2f74b78ea59320ce83a93e29c565dd03c946df00e2",
          "sha256": "c0608077c2d0275cde42feeacd0b82ec27e3be68b7af35caa4d97e4b13b0f399",
          "sha1": "f939059af04375c9723e7848cdac1b1007afde3f",
          "md5": "0ebd8378db1863026d072d08b0e02f22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "goety-fabric-0.0.2-forge2.5.51.0+mc1.20.1-sources.jar",
          "url": "goety-fabric-0.0.2-forge2.5.51.0+mc1.20.1-sources.jar",
          "size": 71140670,
          "sha512": "116b14e955ba21c4e61f18380f1cb232fe8a032cfb8b887e3c52c049de36a7a69dfc53e1066430e50b862189533ef40db632c79891f14023120775ba0097314d",
          "sha256": "ffb4b4908f4ee850390ba117a87068c08d24c41a91d5035d945e64851a619df7",
          "sha1": "128e872ff12ca6e4c3b6f1e860fc0ad96845eac0",
          "md5": "fd4ba66f49f616a1b4fa7df602f4a662"
        }
      ]
    }
  ]
}
