{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "items",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "items-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "items-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 770421,
          "sha512": "c595b565dfce836c5154f6380332f7a6dad6bbb425faae415c13488162208642bfe490d30f85045fa562930dced830bcb6dcfafb138c8f7755065c49c02446f2",
          "sha256": "5269bcc440dc96f393c78cde2f37f5ca72ca9f863079436a63ef1a1cd816ff04",
          "sha1": "321ec4e2529c94dfb94cd5717de1ae4df51644d6",
          "md5": "4ca49f5d8be0346d65ce851fafad4353"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "items-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "items-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 770421,
          "sha512": "c595b565dfce836c5154f6380332f7a6dad6bbb425faae415c13488162208642bfe490d30f85045fa562930dced830bcb6dcfafb138c8f7755065c49c02446f2",
          "sha256": "5269bcc440dc96f393c78cde2f37f5ca72ca9f863079436a63ef1a1cd816ff04",
          "sha1": "321ec4e2529c94dfb94cd5717de1ae4df51644d6",
          "md5": "4ca49f5d8be0346d65ce851fafad4353"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "items-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "items-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 67026,
          "sha512": "869108cf428f94a8430a00403d370024fc97a053a8e1185d9d7a956aee4b524285f2639dd484babda638d4877e2101f872c0ed6bbd2856d209a213914a662d63",
          "sha256": "eb761665217bc99e71830ac256130f3cbba4092c486737c086f5147464b0cb81",
          "sha1": "ccee89473a0dd1c1fa9db11f8ab637abed9d2cc0",
          "md5": "63225045da5ad5445035033d38622b6c"
        }
      ]
    }
  ]
}
