{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.10+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.10+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.10+mc1.20.1.jar",
          "size": 52633187,
          "sha512": "de94ccc8a4d1c2335928b69a233a5bb03f90795d98285e68c80ffe85a31e56c31c055bd966061dfbacf4cab8e485b37789a9b887608f61073d2ddb4df89f2532",
          "sha256": "13768da74d9c8575a206cdfb53f143aa9d884a2568c4720dc74ef79a86a32289",
          "sha1": "96bb25c664a60b3943e3abce3f3921d36b4b57eb",
          "md5": "2bffb6e33ea949faba0de37b80b06cf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.4-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.10+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.10+mc1.20.1.jar",
          "size": 52633187,
          "sha512": "de94ccc8a4d1c2335928b69a233a5bb03f90795d98285e68c80ffe85a31e56c31c055bd966061dfbacf4cab8e485b37789a9b887608f61073d2ddb4df89f2532",
          "sha256": "13768da74d9c8575a206cdfb53f143aa9d884a2568c4720dc74ef79a86a32289",
          "sha1": "96bb25c664a60b3943e3abce3f3921d36b4b57eb",
          "md5": "2bffb6e33ea949faba0de37b80b06cf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.10+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.10+mc1.20.1-sources.jar",
          "size": 50197285,
          "sha512": "eb1c7304da3e9e86e7f8c847e54b0f899195390d7912918911f5301e7243a407c76a7ca6c0f0e88fe3f491ba7ca75c12720e43cfaff6df566dd864c693fdca89",
          "sha256": "2061d8ec0f099250adc1f9b8458d1a2e38a888dea2b49d1c32a4e945402af469",
          "sha1": "3d4186827da470f1d4f6d59a06f26324e1402b0f",
          "md5": "e27b64dd33e32391d2bd08e5043d1ff6"
        }
      ]
    }
  ]
}
