{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.5-Resharped-1.8.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.5-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.5-Resharped-1.8.60.jar",
          "size": 7134431,
          "sha512": "4c69f433686c6be55c612a78b16e86a9dc1dfe0b17fcf4a5d3b48fc370f5092688779a1c3448e7ab7e8ad0692048d5785e9964d90b2bd6248b52313707f52a49",
          "sha256": "4ac7debddbcc5d1041a4d936c5887561f53308a673ea52ae1b93a34e69ca07df",
          "sha1": "f3381ec42539bdcba879e90dd7d367d8a119f04c",
          "md5": "c6c1c948f42181f0e1e44367469bb061"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.5-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.5-Resharped-1.8.60.jar",
          "size": 7134431,
          "sha512": "4c69f433686c6be55c612a78b16e86a9dc1dfe0b17fcf4a5d3b48fc370f5092688779a1c3448e7ab7e8ad0692048d5785e9964d90b2bd6248b52313707f52a49",
          "sha256": "4ac7debddbcc5d1041a4d936c5887561f53308a673ea52ae1b93a34e69ca07df",
          "sha1": "f3381ec42539bdcba879e90dd7d367d8a119f04c",
          "md5": "c6c1c948f42181f0e1e44367469bb061"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.5-Resharped-1.8.60-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.5-Resharped-1.8.60-sources.jar",
          "size": 3555954,
          "sha512": "a2f14a4d188a8e23c09776ffb3b51ce5c380a12641876c5643a46f63ec2e5adba0abfbeae95c33ae53d243c02d1e45ddd1166efa38086dfc3c7e98b96d172a1c",
          "sha256": "22b733f75e729fcbca2b74c18b4c7739931c49dd2e25c8d06b5d9e686e929424",
          "sha1": "a70227bf6f9c85b9b36332df516e64b017f494ef",
          "md5": "34fbe48ac275f86e1413296881d6e8c4"
        }
      ]
    }
  ]
}
