{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "mixin_extensions",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "mixin_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "mixin_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 688555,
          "sha512": "6f33c5f59631734f00997b67215a0a3eae85764363a04696d80512ac167c4175d272b07f7db13713f88b852d1b3a617596317f425212d2e9b7699943c60cd799",
          "sha256": "ebd8f9bc2179ea14aab3e6163b1c345035ca493e764585a18ec9878048d38d88",
          "sha1": "054a2b4335f7261affc006af815e5855d7c5d78e",
          "md5": "db033e006af29c3fe348045889811487"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "mixin_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "mixin_extensions-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 688555,
          "sha512": "6f33c5f59631734f00997b67215a0a3eae85764363a04696d80512ac167c4175d272b07f7db13713f88b852d1b3a617596317f425212d2e9b7699943c60cd799",
          "sha256": "ebd8f9bc2179ea14aab3e6163b1c345035ca493e764585a18ec9878048d38d88",
          "sha1": "054a2b4335f7261affc006af815e5855d7c5d78e",
          "md5": "db033e006af29c3fe348045889811487"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mixin_extensions-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "mixin_extensions-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 11045,
          "sha512": "6e08b993277fec2fc73fdf2a79280fe1737f25f57b69158dad7d14dab6913c9bafdb1b387644cc7f0a128442caaf566cc47b291d079f8a872550298921b813b1",
          "sha256": "45c25cc86b846adf63f9a6d9a4ae42dd1a0ff8ed256e034e4521ae187db705ae",
          "sha1": "df7eeacdc81bd9f1a818f501f485bbc4b0c02be6",
          "md5": "f9b2cb88825ceeebdd67ba0938a862b6"
        }
      ]
    }
  ]
}
