{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "registry",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "registry-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "registry-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 704762,
          "sha512": "6234f566c05a89b2df69fdfaf8558b4bcf8fb7c767f97408fdcb249ca1f25533e17de22763afddef674ba47455a0c584c5006e7b04b6d02d6529f84b0e5ce0e3",
          "sha256": "7bd9233940f5103d56a209f431ca1f34e2b1d54bc1c1da6c867b981f94adf6f4",
          "sha1": "f1d530962a88e9c788245908232a0b26d3019b8e",
          "md5": "b131346517be33fc8f401cb94d972cba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "registry-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "registry-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 704762,
          "sha512": "6234f566c05a89b2df69fdfaf8558b4bcf8fb7c767f97408fdcb249ca1f25533e17de22763afddef674ba47455a0c584c5006e7b04b6d02d6529f84b0e5ce0e3",
          "sha256": "7bd9233940f5103d56a209f431ca1f34e2b1d54bc1c1da6c867b981f94adf6f4",
          "sha1": "f1d530962a88e9c788245908232a0b26d3019b8e",
          "md5": "b131346517be33fc8f401cb94d972cba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "registry-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "registry-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 19935,
          "sha512": "f1198ff92e5fe4a0ba8015b1f6afa3e291080898c5d6db3aa9cdd3a3e965ae991cceb7cc818507809b65d9f875b3d1ad0c7f1928f95d485aed783eef3b22668c",
          "sha256": "55075adf7d5f924f7531cb77d32efe07b8d1f8a288f33e34f38cf511dac1b449",
          "sha1": "ed8ffa57bcefc98bfe86bee17dc2d457dad1586b",
          "md5": "36cf03148bf9fea7258f3a18dfedb85c"
        }
      ]
    }
  ]
}
