{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.20.1",
    "version": "0.3.0-forge1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.3.0-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.20.1-0.3.0-forge1.1.7.jar",
          "size": 52729306,
          "sha512": "840f0d564382bbee283e69b15b854228690bafe815e594f0d7753340590d98c417bf9b2be94a0cbecacaf30a1151290327654e7292c22703edcc5210037f32af",
          "sha256": "b9070ae0000b79cf2bf85d3080f8948e7cf49b5fb2bf1624651996c87fa4e35c",
          "sha1": "654e0758db9b6592f6de1af83df8657239b5e701",
          "md5": "342a0d66aa72239a4e91c8015d03c442"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784146"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "1.20.X-1.2.0"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.104"
          }
        },
        {
          "group": "curse.maven",
          "module": "spark-361579",
          "version": {
            "requires": "4738953"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6902843"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826546"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.17.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.3.0-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.20.1-0.3.0-forge1.1.7.jar",
          "size": 52729306,
          "sha512": "840f0d564382bbee283e69b15b854228690bafe815e594f0d7753340590d98c417bf9b2be94a0cbecacaf30a1151290327654e7292c22703edcc5210037f32af",
          "sha256": "b9070ae0000b79cf2bf85d3080f8948e7cf49b5fb2bf1624651996c87fa4e35c",
          "sha1": "654e0758db9b6592f6de1af83df8657239b5e701",
          "md5": "342a0d66aa72239a4e91c8015d03c442"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.20.1-0.3.0-forge1.1.7-sources.jar",
          "url": "TACZ-Refabricated-1.20.1-0.3.0-forge1.1.7-sources.jar",
          "size": 48903737,
          "sha512": "273ad2565d6964adc39062932753fe71b84d5d180b1bd444fd6f938488b399db79f1fac6546fa92a5ecdbe5699b97c9c1ea298b202a079c844015b5d3e8b8db5",
          "sha256": "ffc4d6c1260c0364700f1cece45690e8797436c24d4876e4407fbe0ff862c432",
          "sha1": "06c389aac1144299900709bd21d1295beba6b28c",
          "md5": "152a2ec876515e662f5fe30097db29dc"
        }
      ]
    }
  ]
}
