{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "level_events",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "level_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "level_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 746265,
          "sha512": "205bce15179186c2d368be8b36af4df5013d977cdc3543891eaa88d864105167bbc6fad65a0a6547c1b8e229b52f6aacdb0b374d890396cb2b8238cdbe22c5b6",
          "sha256": "750c4e8cb9877346e9de5b60f4a4cb624f45048ed9c42db71115cc620b0f0ad9",
          "sha1": "da3271d217372a63bcd76d76a61b1ee7cbd35bb0",
          "md5": "f0f46d4d85fbde8b8e1b68627ffca98e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "level_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "level_events-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 746265,
          "sha512": "205bce15179186c2d368be8b36af4df5013d977cdc3543891eaa88d864105167bbc6fad65a0a6547c1b8e229b52f6aacdb0b374d890396cb2b8238cdbe22c5b6",
          "sha256": "750c4e8cb9877346e9de5b60f4a4cb624f45048ed9c42db71115cc620b0f0ad9",
          "sha1": "da3271d217372a63bcd76d76a61b1ee7cbd35bb0",
          "md5": "f0f46d4d85fbde8b8e1b68627ffca98e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "level_events-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "level_events-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 31309,
          "sha512": "9fe3e9ed520de0d4324f29914431cfc223859e7a2c48e6fb8c0b586659b01c7ffb2cbfe4dc6922355adefa3ae99627fd96e6a31c81022b0ba004fb1e659cf301",
          "sha256": "7b6c2195b9b2c89bebc7a2c159cf9bfb33482e31bb9ba94f7e23acb6418a11dd",
          "sha1": "13d8872b7ead42a6e1b1f495750f7661c7450e1b",
          "md5": "51cdb11ce5ef005bbad2d2b53c054b6e"
        }
      ]
    }
  ]
}
