{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.6+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.6+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.6+mc1.20.1.jar",
          "size": 52633159,
          "sha512": "c5881cc3169e4ecd4ee81c8cbb328e48329c9444083d5b832c7cefb76ce424d6e208ff840b48e442d25506371c6b6021266409b510bc0c921403a002b4f39e97",
          "sha256": "cef9fb74d813112946389200b8695d79a5bc5c6a7fac462880b049e876d8143d",
          "sha1": "7ff66142314b86cc6e342a311ce63cf88ada6116",
          "md5": "40f32c7f4a43762130f3cd6b0ddead21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.3-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.6+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.6+mc1.20.1.jar",
          "size": 52633159,
          "sha512": "c5881cc3169e4ecd4ee81c8cbb328e48329c9444083d5b832c7cefb76ce424d6e208ff840b48e442d25506371c6b6021266409b510bc0c921403a002b4f39e97",
          "sha256": "cef9fb74d813112946389200b8695d79a5bc5c6a7fac462880b049e876d8143d",
          "sha1": "7ff66142314b86cc6e342a311ce63cf88ada6116",
          "md5": "40f32c7f4a43762130f3cd6b0ddead21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.6+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.6+mc1.20.1-sources.jar",
          "size": 50197249,
          "sha512": "c58a9df10b73604fb3ce76f3455be4435f1a485672d343c0b4e10f3722535937c7a63229d342177e8a15d39d453662ca25e0d0b2775d751e293ba9c42bebad0b",
          "sha256": "7c8703604668108aa97f5e23f5953b7df81113f7a9eaedf208b33e507fdb7ffd",
          "sha1": "ab8b4754f69208a6132a44181bfd24b7c29b6448",
          "md5": "4e0d1e15de53bf83d488670415613b2f"
        }
      ]
    }
  ]
}
