{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "gui_utils",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "gui_utils-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "gui_utils-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 718369,
          "sha512": "713ebd068c721f952c9b5dc001f6f1b8126a4dbdbd5b6ce0ea74edc3a2d3e8173048ff41404bac8c49a9804058c44cb9f71bc1e95ab1e058a6569a8e45e03358",
          "sha256": "87cf279e20396cb363f8007be191b07cfb69254568c3893ca28d3ffc2f6091a6",
          "sha1": "427c458c446913669b505f1fd26599d1d04d08e7",
          "md5": "fe87bbfa08bd90abbe4dfea226760635"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "gui_utils-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "gui_utils-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 718369,
          "sha512": "713ebd068c721f952c9b5dc001f6f1b8126a4dbdbd5b6ce0ea74edc3a2d3e8173048ff41404bac8c49a9804058c44cb9f71bc1e95ab1e058a6569a8e45e03358",
          "sha256": "87cf279e20396cb363f8007be191b07cfb69254568c3893ca28d3ffc2f6091a6",
          "sha1": "427c458c446913669b505f1fd26599d1d04d08e7",
          "md5": "fe87bbfa08bd90abbe4dfea226760635"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gui_utils-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "gui_utils-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 25233,
          "sha512": "f9813c8144737aa7ef38eb07ba40757839cca0e68f7825e4c25acf7a2b2c214ced7532d744544b76034adf05cb3322e3a155fbe5fa3b23a8b1d1649e1ac05cc9",
          "sha256": "97c154c0c4f7cf319cc0f52ffe37dcddcbdbb0373bdd724fee3856184b85251a",
          "sha1": "9f773aefde0fb4b912daea1f8ade761789cbf6e8",
          "md5": "1a45e9c2537547faf1cb551f26afdd9f"
        }
      ]
    }
  ]
}
