{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "TACZ-Refabricated-1.21.1",
    "version": "0.3.0-forge1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.3.0-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.3.0-forge1.1.7.jar",
          "size": 52657858,
          "sha512": "e19e46c313ba35b73351e5eeaac79d9372a2398da13453ee41c7ee381116e4228b1fd76eaf4abce404376e6bd1c504ba3f8007a31100be84ba65d3403d7a686b",
          "sha256": "82f6258950a7ccc44ea015cd5bce596e7e2a38d11105ed2f4df4ff0b246d0fd3",
          "sha1": "245d2198334bc8638d7cc480925dcc74319fc32e",
          "md5": "314aeeeadd65408344c215aa5172a0c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.moulberry",
          "module": "mixinconstraints",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.5+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "shoulder-surfing-reloaded-243190",
          "version": {
            "requires": "6784174"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6914081"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tweakeroo",
          "version": {
            "requires": "0.21.59"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "malilib",
          "version": {
            "requires": "0.21.9"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.744"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "flashback",
          "version": {
            "requires": "pOGQFvgK"
          }
        },
        {
          "group": "com.moulberry",
          "module": "lattice",
          "version": {
            "requires": "1.2.18"
          },
          "attributes": {
            "earth.terrarium.cloche.modLoader": "fabric"
          }
        }
      ],
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.3.0-forge1.1.7.jar",
          "url": "TACZ-Refabricated-1.21.1-0.3.0-forge1.1.7.jar",
          "size": 52657858,
          "sha512": "e19e46c313ba35b73351e5eeaac79d9372a2398da13453ee41c7ee381116e4228b1fd76eaf4abce404376e6bd1c504ba3f8007a31100be84ba65d3403d7a686b",
          "sha256": "82f6258950a7ccc44ea015cd5bce596e7e2a38d11105ed2f4df4ff0b246d0fd3",
          "sha1": "245d2198334bc8638d7cc480925dcc74319fc32e",
          "md5": "314aeeeadd65408344c215aa5172a0c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TACZ-Refabricated-1.21.1-0.3.0-forge1.1.7-sources.jar",
          "url": "TACZ-Refabricated-1.21.1-0.3.0-forge1.1.7-sources.jar",
          "size": 48889004,
          "sha512": "8dc634edea59a0d1fcf7fad8b04e0ba488f9ae8f78f642a698bbb9990c3f4ce275baacbbc7d341293e9204707d499300a07781d82b99cc243ea496de4414ef42",
          "sha256": "23fd62a1208b41a6ec6aa3534a637a3142ae5bdb3117ae5a6639b2dedadf42fa",
          "sha1": "486693047de16e6e8a02116c42408be51214ccdb",
          "md5": "d957948ef8ed701f63c3b2b74da4cbac"
        }
      ]
    }
  ]
}
