{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.20.1-1.2.0-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.2.0-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.20.1-1.2.0-Resharped-1.8.61.jar",
          "size": 7987527,
          "sha512": "171019edde630db6f16a69ea59b1489f395826a88009fe2ecafa12d5e731b3bc4a2f3f8ade548cfc44c0aa4a285ffc2cc58fbf8aff64f1a28a4ee6f51ed7c99d",
          "sha256": "57f8b5d5b6f7983affd3f2a5bb861a1c58dddd693344166b32136df6dce6ff5a",
          "sha1": "45ceee0c397940708a0aaa70de738b556f3e7fd9",
          "md5": "3e819f43ad51640e029038dc1c73479c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "attributes",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "emi-580555",
          "version": {
            "requires": "6420944"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5.1-1.20.1-alpha-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6815736"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6608232"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.105"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180902"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "5984629"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-83-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.2.0-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.20.1-1.2.0-Resharped-1.8.61.jar",
          "size": 7987527,
          "sha512": "171019edde630db6f16a69ea59b1489f395826a88009fe2ecafa12d5e731b3bc4a2f3f8ade548cfc44c0aa4a285ffc2cc58fbf8aff64f1a28a4ee6f51ed7c99d",
          "sha256": "57f8b5d5b6f7983affd3f2a5bb861a1c58dddd693344166b32136df6dce6ff5a",
          "sha1": "45ceee0c397940708a0aaa70de738b556f3e7fd9",
          "md5": "3e819f43ad51640e029038dc1c73479c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.2.0-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.20.1-1.2.0-Resharped-1.8.61-sources.jar",
          "size": 3648918,
          "sha512": "fbe330cfc55e7d45111ff8436d33bac3e707f456b2da52c934ad85583e1e03137ab357c714b110aa02fc3d6ca10c87ef34b169370e4c1e34aae5450a5466369d",
          "sha256": "ad69a4e9cd412e60c102f5f95e1e162614bb718f2366f25e725972f51f01020b",
          "sha1": "c9b467f815b52c4af1aa31825794d9d1f650f215",
          "md5": "5ef699966bfcc9205963fa7fef10f68c"
        }
      ]
    }
  ]
}
