{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.8+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.8+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.8+mc1.21.1.jar",
          "size": 50855552,
          "sha512": "ca0f3768d0e6471b35ba398167aa76b22c55745b290d5e1adfc1e82a279eb966855c5a7557c8647c7c6a04c70e572fc15d09da8c6ea940b9638153726d45e58a",
          "sha256": "9ff0a13161826d17e05d4b119541bd5d4a8f843a1aa08454c1920e5572d30dda",
          "sha1": "caf2e932e0fcce65ccb5d2bc42ce91855e47fd7c",
          "md5": "f6471490bfabe5f2976dd3f092068ab4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.4-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.8+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.8+mc1.21.1.jar",
          "size": 50855552,
          "sha512": "ca0f3768d0e6471b35ba398167aa76b22c55745b290d5e1adfc1e82a279eb966855c5a7557c8647c7c6a04c70e572fc15d09da8c6ea940b9638153726d45e58a",
          "sha256": "9ff0a13161826d17e05d4b119541bd5d4a8f843a1aa08454c1920e5572d30dda",
          "sha1": "caf2e932e0fcce65ccb5d2bc42ce91855e47fd7c",
          "md5": "f6471490bfabe5f2976dd3f092068ab4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.8+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.8+mc1.21.1-sources.jar",
          "size": 50564939,
          "sha512": "30cd470ab70d1f629c9ee2dd5a68afad4ed48d32ab831f8b1779e11130eedefe1fd40f734870557f348cb526145040ab8d7037a6296cde778e97651b937004ca",
          "sha256": "fc9ca7dec93461946b711fa80d9b183cf6f8a633ba13b5a38ff246bbe2de894b",
          "sha1": "dc25d7d512dd66a6cf247186352a6ab2e94c75d4",
          "md5": "7e209ef364351a7636103076ebf8a567"
        }
      ]
    }
  ]
}
