{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.4.2-Resharped-1.9.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.2-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.2-Resharped-1.9.65.jar",
          "size": 9217451,
          "sha512": "2aaeee3a3988ee12240e62a087bc9b0c926564f7b9bf97922a3ad7af9dd1f09bba10920665a50bf653c62fe41359a1b581c2a40599e8cdfae1baca3008c56eae",
          "sha256": "e8242c3cd0fff86facd2f7e940e729eed15f8ec686339ced7f8ad18474371de6",
          "sha1": "54a955a0e765866972c9b10744a0e8bbbbe5eb43",
          "md5": "43b9cd1bcd3fda6f90d04fa7fc3442df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.2-Resharped-1.9.65.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.2-Resharped-1.9.65.jar",
          "size": 9217451,
          "sha512": "2aaeee3a3988ee12240e62a087bc9b0c926564f7b9bf97922a3ad7af9dd1f09bba10920665a50bf653c62fe41359a1b581c2a40599e8cdfae1baca3008c56eae",
          "sha256": "e8242c3cd0fff86facd2f7e940e729eed15f8ec686339ced7f8ad18474371de6",
          "sha1": "54a955a0e765866972c9b10744a0e8bbbbe5eb43",
          "md5": "43b9cd1bcd3fda6f90d04fa7fc3442df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.4.2-Resharped-1.9.65-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.4.2-Resharped-1.9.65-sources.jar",
          "size": 3555525,
          "sha512": "48787d7d5fc7ddb69b0d0d606a87b082f0caafd689f5c088ffda7d3a9c8daea10cdee4c2280dd66d98729d0c5a817ac60184d08e259005475089924a7243ca49",
          "sha256": "db4c2454183bbc03cc4dbf7cd002b51da3429b0255fcd6d78512b7463bde472c",
          "sha1": "d31fb6bee4d1fcb3f91edbc4e4d0e779ba77f9f4",
          "md5": "3b8630348ea4c2d8013fccee3bd4e346"
        }
      ]
    }
  ]
}
