{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.0-Resharped-1.8.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.0-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.0-Resharped-1.8.57.jar",
          "size": 7125813,
          "sha512": "dd1c35b940e87635a1de236afd9a61ff174cc1aeab71886860518e06ae406bd57e201a6445fcde0589524c939ded3bc7b9c710ea83ec795f94afadad1d521ba4",
          "sha256": "9796aaebee25a298588e81e0b4193f5b58d0d6af7c1594f786938e3cc5dcbeb7",
          "sha1": "cff2cd5be2275eb187f3e58825695aa7f83ab339",
          "md5": "365d344687e2b3c7f9e0e70be3b8fcfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.0-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.0-Resharped-1.8.57.jar",
          "size": 7125813,
          "sha512": "dd1c35b940e87635a1de236afd9a61ff174cc1aeab71886860518e06ae406bd57e201a6445fcde0589524c939ded3bc7b9c710ea83ec795f94afadad1d521ba4",
          "sha256": "9796aaebee25a298588e81e0b4193f5b58d0d6af7c1594f786938e3cc5dcbeb7",
          "sha1": "cff2cd5be2275eb187f3e58825695aa7f83ab339",
          "md5": "365d344687e2b3c7f9e0e70be3b8fcfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.0-Resharped-1.8.57-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.0-Resharped-1.8.57-sources.jar",
          "size": 3549559,
          "sha512": "2c643ce29e8263a4fec36df9c33b562eb7c4c816fd6301f34b3587aab47d1272e20bd8045580865c0e83536bfed23508ea01fe67c573e200ea8a7eefec7c4126",
          "sha256": "4ff7dfccb36f2fd7156b2e2bba5102024944b2b05ddaa305c3299b95846bac45",
          "sha1": "f0faa87dcbba5535d943f14a8daddd3848bd6473",
          "md5": "fd5cef81b3b2dc7d3e0bf8e44c885f17"
        }
      ]
    }
  ]
}
