{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.3.0+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.3.0+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.3.0+mc1.21.1.jar",
          "size": 50845709,
          "sha512": "b1adf1bff768a432f33c88f4cb5507aa0cb8b1f2ef3d746cbfe9f92a9c2e7ab1ab4e8765e2c36c406a089fa56d8d5564dbc5766c4f0a2cb0967dc7d48aa61433",
          "sha256": "62b49ea8612024c0b3127b973fecb5e334083eb1c2a1aa323616d660134b3c30",
          "sha1": "454de4183b13d9240805b3fa724db7e05c9cf011",
          "md5": "a2e5291657892ed0190bee76246fc16c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.4.0-Resharped-1.9.65"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.3.0+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.3.0+mc1.21.1.jar",
          "size": 50845709,
          "sha512": "b1adf1bff768a432f33c88f4cb5507aa0cb8b1f2ef3d746cbfe9f92a9c2e7ab1ab4e8765e2c36c406a089fa56d8d5564dbc5766c4f0a2cb0967dc7d48aa61433",
          "sha256": "62b49ea8612024c0b3127b973fecb5e334083eb1c2a1aa323616d660134b3c30",
          "sha1": "454de4183b13d9240805b3fa724db7e05c9cf011",
          "md5": "a2e5291657892ed0190bee76246fc16c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.3.0+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.3.0+mc1.21.1-sources.jar",
          "size": 50554017,
          "sha512": "2de0a0c00dd6a8446634cf2c7efd5617f3af8929fa240312dcfca1da3908d275b90ff669ac21d6550c6e7dd7f6b25da36e88dcd99f899d16489815dbca9110dc",
          "sha256": "5aee135be0455c7c40f901d989c80fd1a987c2deb5120b7c9247079e804376f0",
          "sha1": "fd888a4574bb6bec097e1b630f0d283ae6fac265",
          "md5": "1f784f6f88daf9886414215845569c30"
        }
      ]
    }
  ]
}
