{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.0.1-Resharped-1.7.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.0.1-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.21.1-1.0.1-Resharped-1.7.55.jar",
          "size": 7121282,
          "sha512": "fc225730db3b9be3b5d0232f6a928fb569f6686c1c4ab154f7ae4d913169c38c20df363e56804f5a13f7b845efe391eb3f85b567dd0de3c4236571f0d2c9b1ec",
          "sha256": "fe1eff7716f9e2eb916cd7d1587244baf2f8ac9c1b0d37101bde88a8d4f0b0f4",
          "sha1": "97ba348cfbbfa4020357aab47623790a0112d785",
          "md5": "fa4ec16dce64caaedb30afc0431e1b80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.0.1-Resharped-1.7.55.jar",
          "url": "slashblade-refabricated-1.21.1-1.0.1-Resharped-1.7.55.jar",
          "size": 7121282,
          "sha512": "fc225730db3b9be3b5d0232f6a928fb569f6686c1c4ab154f7ae4d913169c38c20df363e56804f5a13f7b845efe391eb3f85b567dd0de3c4236571f0d2c9b1ec",
          "sha256": "fe1eff7716f9e2eb916cd7d1587244baf2f8ac9c1b0d37101bde88a8d4f0b0f4",
          "sha1": "97ba348cfbbfa4020357aab47623790a0112d785",
          "md5": "fa4ec16dce64caaedb30afc0431e1b80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.0.1-Resharped-1.7.55-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.0.1-Resharped-1.7.55-sources.jar",
          "size": 3546461,
          "sha512": "050a0d47ea77f1fda43a282e3e4e116d66eeab76e284864f5eb90ff3909121992dec32612ba1e456235b3602283836712de3f31cb9b40c7052fd100ebcd1dcc9",
          "sha256": "14ed95fea3116241c558281a62f9aaf3546368b08e92299163d09767879b51b6",
          "sha1": "aabecb78f5d598542d42747b664dde5706afc32b",
          "md5": "2a458cdfce6271af1567890324a31762"
        }
      ]
    }
  ]
}
