{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.5+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.5+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.5+mc1.21.1.jar",
          "size": 50855509,
          "sha512": "3ecee99ea35277e76c42dff3ee173df970f6e866971a06ceb0ffc23e40f2d4a6138a1513a88918d593e88f67986ab402a4f76223190efa77d9f69d2ff7f3b25a",
          "sha256": "b50334faa1189b5acda289de9819291882730c0c28f0adfbdaea981418847f66",
          "sha1": "4437425ef2a13ccdec28a126a76b97c055fdadf6",
          "md5": "4670f7984d3cb22c7ece10bd182e2945"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.2-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.5+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.5+mc1.21.1.jar",
          "size": 50855509,
          "sha512": "3ecee99ea35277e76c42dff3ee173df970f6e866971a06ceb0ffc23e40f2d4a6138a1513a88918d593e88f67986ab402a4f76223190efa77d9f69d2ff7f3b25a",
          "sha256": "b50334faa1189b5acda289de9819291882730c0c28f0adfbdaea981418847f66",
          "sha1": "4437425ef2a13ccdec28a126a76b97c055fdadf6",
          "md5": "4670f7984d3cb22c7ece10bd182e2945"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.5+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.5+mc1.21.1-sources.jar",
          "size": 50564891,
          "sha512": "413476c913f7edda0366d94c59479bc3b6fa4e217235ac94b5a0397b60ef50d99436f97e478069cfe0607e71d7ca9e4692adf05a2173eef3476ec8e2235aba62",
          "sha256": "6b668034598cda63b5d20db81df43e4ab2099da1f1b8335b821dd88dce66bdb5",
          "sha1": "898d9ecfa5abf5ca1378495b4f14ad10d20b0c56",
          "md5": "826b03ce30d13619f2905bec0951cf9f"
        }
      ]
    }
  ]
}
