{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.1-Resharped-1.8.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "size": 7126913,
          "sha512": "6e977580c6a8fbbfe060748648e67c9d6a1955fc97a2d1c41dd0b97e286415429f03c39f650cdad30a511f32dcd32aa7e65ccee069b041933b9bb0e57be49ab6",
          "sha256": "235104e6fbc8c63547662e4909658f26089484e6efd1a82cd45c9cddfb798a50",
          "sha1": "bc3f34ee9d921d900bc7a12c36460535e3a668e4",
          "md5": "3b0ecee6e749ae03b9363a17c14cb95a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "size": 7126913,
          "sha512": "6e977580c6a8fbbfe060748648e67c9d6a1955fc97a2d1c41dd0b97e286415429f03c39f650cdad30a511f32dcd32aa7e65ccee069b041933b9bb0e57be49ab6",
          "sha256": "235104e6fbc8c63547662e4909658f26089484e6efd1a82cd45c9cddfb798a50",
          "sha1": "bc3f34ee9d921d900bc7a12c36460535e3a668e4",
          "md5": "3b0ecee6e749ae03b9363a17c14cb95a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57-sources.jar",
          "size": 3549881,
          "sha512": "40ac6f6766f818e78ff05fd52c32f42e49a2bedb9a10a3e76e9d7772686aaa4e3c91ff192a9aabb70b8ed5b5bda57f3d8f6a363ad745da96235037f7f28f15b6",
          "sha256": "d37b89ab313d160d842a9bb7cdd53e61bdcf1d6b6f9a7d160a7378952cfbe5d9",
          "sha1": "1020a6a8049b6f38e7702ee0f34d13a78318beeb",
          "md5": "b4ad3a798d4a73aee7494c687c85ed58"
        }
      ]
    }
  ]
}
