{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.1-Resharped-1.8.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "size": 7126818,
          "sha512": "49014b4eda413e4cafe9e9755537ccdba573c4bd23f4d31e8ed11d2d08f17f7f81c4b9bc1f1fba076b0a9783424d927bb0dceebce24404ee0c3366f8ccf52cbd",
          "sha256": "76da79f3472b39580801bdbda300e2c7d57b4efd5fd13712ce6e6add53301ac6",
          "sha1": "875937c2b2b25ac6fcbed25baf2475dbdfdb611e",
          "md5": "7b8b499aa0527d25f7d66255226dcbe7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57.jar",
          "size": 7126818,
          "sha512": "49014b4eda413e4cafe9e9755537ccdba573c4bd23f4d31e8ed11d2d08f17f7f81c4b9bc1f1fba076b0a9783424d927bb0dceebce24404ee0c3366f8ccf52cbd",
          "sha256": "76da79f3472b39580801bdbda300e2c7d57b4efd5fd13712ce6e6add53301ac6",
          "sha1": "875937c2b2b25ac6fcbed25baf2475dbdfdb611e",
          "md5": "7b8b499aa0527d25f7d66255226dcbe7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.1-Resharped-1.8.57-sources.jar",
          "size": 3549829,
          "sha512": "b34d96be9d2ce4b6b3d9d41398480282762ca2f9b0eb17c7ddf113effe096cb82416ae1820c34a9f6843e112989e039f28641c169b2b81bd2df5bb154d572de6",
          "sha256": "825c1e1a7ea0a2b11925b72739a503571b94442b3c5392274b1f42cc9f72d523",
          "sha1": "f7e08991c8e476cf10b6ad7b3bd528abb734418d",
          "md5": "9e6d264a9539a47aeb01b8f2d86f355a"
        }
      ]
    }
  ]
}
