{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "touhoulittlemaid-fabric-1.21.1",
    "version": "0.5.0-neo1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6.jar",
          "url": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6.jar",
          "size": 24697714,
          "sha512": "a97551202ea0187331bc8c0a4996f099704dc4173aa5269c864d5360c533e126b671dd27ac1fb13b19d7b494ed81a62eae1e32cde82815c08cde0a4774a77949",
          "sha256": "913bafb4907558e6b419e6df1d46cf227ea465f55e2320a52f62ff5aba73a9ef",
          "sha1": "87a1f6c4daba4c5adc9ea19aefde9f7f6d9b5985",
          "md5": "c4d2bf7cef75e7fcc9acdf1632f5b8ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.gagravarr",
          "module": "vorbis-java-core",
          "version": {
            "requires": "0.8"
          }
        },
        {
          "group": "io.github.jaredmdobson",
          "module": "concentus",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.4+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "19.22.1.316-fabric"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "15.10.1+fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "cyberanner-ironchest",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carry-on",
          "version": {
            "requires": "2.2.2-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patchouli",
          "version": {
            "requires": "1.21-87-fabric"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.4+kotlin.2.2.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "libipn",
          "version": {
            "requires": "fabric-1.21-6.5.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "inventory-profiles-next",
          "version": {
            "requires": "fabric-1.21.1-2.1.8"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "immersive_melodies",
          "module": "immersive_melodies-fabric",
          "version": {
            "requires": "0.6.2+1.21.1"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Fabric-1.21.1",
          "version": {
            "requires": "1.0.61"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "improved-mobs",
          "version": {
            "requires": "1.21.1-1.14.2-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tenshilib",
          "version": {
            "requires": "1.21.1-2.1.1-fabric"
          }
        },
        {
          "group": "libs",
          "module": "TACZ-Refabricated",
          "version": {
            "requires": "1.21.1-0.0.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "nonconflictkeys-fabric-865546",
          "version": {
            "requires": "4572953"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patpat",
          "version": {
            "requires": "1.2.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "proxlib",
          "version": {
            "requires": "0.2.4+1.21"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.0.1-Resharped-1.7.55"
          }
        },
        {
          "group": "io.github.cottonmc",
          "module": "LibGui",
          "version": {
            "requires": "11.1.0+1.21"
          }
        },
        {
          "group": "me.zeroeightsix",
          "module": "fiber",
          "version": {
            "requires": "0.23.0-SNAPSHOT"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-minimap",
          "version": {
            "requires": "25.2.10_Fabric_1.21"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-world-map",
          "version": {
            "requires": "1.39.12_Fabric_1.21"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6.jar",
          "url": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6.jar",
          "size": 24697714,
          "sha512": "a97551202ea0187331bc8c0a4996f099704dc4173aa5269c864d5360c533e126b671dd27ac1fb13b19d7b494ed81a62eae1e32cde82815c08cde0a4774a77949",
          "sha256": "913bafb4907558e6b419e6df1d46cf227ea465f55e2320a52f62ff5aba73a9ef",
          "sha1": "87a1f6c4daba4c5adc9ea19aefde9f7f6d9b5985",
          "md5": "c4d2bf7cef75e7fcc9acdf1632f5b8ed"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6-shadow.jar",
          "url": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6-shadow.jar",
          "size": 22506344,
          "sha512": "309730463a51d28614446b7d015dd3b5e727f0dece7e7307de55c16afa59fe9dbca276b12b511a361b3bf33a8833c89c7ef349c8fb644457ecef5b8fc167de48",
          "sha256": "33b1d521c9b238e2a42344780397e3083dd4e7c9730b63f42f14a7d84e42fa87",
          "sha1": "1e4de28d9e72d25f481456e706167e886fde39a3",
          "md5": "99adfa3ea886ece4f137af5cb374e5fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6-sources.jar",
          "url": "touhoulittlemaid-fabric-1.21.1-0.5.0-neo1.4.6-sources.jar",
          "size": 20362415,
          "sha512": "9f09bab4caf8af90f017685cddfa2ca90c40cddc00ffcabaaf4370962f1415ad7470a6df0d9f9cc502b56b793d1f0b95e035900b2b8940b0e303df6c25ecb66d",
          "sha256": "76c04875aee2d6ece823d5e3538a3c36d74db3289d749dfba9ef54e28c59ae59",
          "sha1": "cfa0d78ba45e64a4e4bb49c584269468e8be7e87",
          "md5": "d806bf6c67380876261f95da69535b28"
        }
      ]
    }
  ]
}
