{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "tourguide-fabric",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "tourguide-fabric-1.0.0.jar",
          "url": "tourguide-fabric-1.0.0.jar",
          "size": 128603,
          "sha512": "eb474fa6dbe849390368955c7c81a8e859177b7feb838ca351e73aaa0a08bed2c3501eed6d9327cc28d1917dc43c97f3118169275fcbaf62d3af86e585514e64",
          "sha256": "f32b126c2049fc74536d7c3d58101d1a70bcdbfeecdc9117c1533ba05f51c659",
          "sha1": "e53865efe8cc6fd7d878b09c26d2b3a36b5eb3e4",
          "md5": "f19721eb7408e581d6ec8296b9d39429"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.16"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino-fabric",
          "version": {
            "requires": "2001.2.3-build.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "tourguide-fabric-1.0.0.jar",
          "url": "tourguide-fabric-1.0.0.jar",
          "size": 128603,
          "sha512": "eb474fa6dbe849390368955c7c81a8e859177b7feb838ca351e73aaa0a08bed2c3501eed6d9327cc28d1917dc43c97f3118169275fcbaf62d3af86e585514e64",
          "sha256": "f32b126c2049fc74536d7c3d58101d1a70bcdbfeecdc9117c1533ba05f51c659",
          "sha1": "e53865efe8cc6fd7d878b09c26d2b3a36b5eb3e4",
          "md5": "f19721eb7408e581d6ec8296b9d39429"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tourguide-fabric-1.0.0-sources.jar",
          "url": "tourguide-fabric-1.0.0-sources.jar",
          "size": 70298,
          "sha512": "023a6beb8a79cf6e1a75474d4f1a8fddd1675218efbea08d2f25000c2c563b1b61c12f285a2ba7629d198d6871214a9d5a4f10a35e416a46ad5dbf193d89c0e8",
          "sha256": "038ac6acadbf754f94f44d08b2d80c13fe03590e36a14fc33109fa06ae07c05e",
          "sha1": "4877065a5f5b45204c31358123e2061d06eae194",
          "md5": "5814d076085ed3c03d563bb63330e157"
        }
      ]
    }
  ]
}
