{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_loader",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "model_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "model_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 755200,
          "sha512": "9def268114a3ee0fd7616dd916276093f783660c9b71017dea90100707bc03bbc590101acf767063c0a60ffc11dfade8063a6035c222594c4680d7ec05c02eae",
          "sha256": "6645db4cc41a2b3cf1f3c753fcb7de0593bb5387a01f978674943a3cd68115b5",
          "sha1": "fc98af0805faf46d9ec3beb55e0bc6a5f023d231",
          "md5": "afed823728915e0d1f8292aabc39e5ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "model_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "model_loader-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 755200,
          "sha512": "9def268114a3ee0fd7616dd916276093f783660c9b71017dea90100707bc03bbc590101acf767063c0a60ffc11dfade8063a6035c222594c4680d7ec05c02eae",
          "sha256": "6645db4cc41a2b3cf1f3c753fcb7de0593bb5387a01f978674943a3cd68115b5",
          "sha1": "fc98af0805faf46d9ec3beb55e0bc6a5f023d231",
          "md5": "afed823728915e0d1f8292aabc39e5ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_loader-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "model_loader-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 45293,
          "sha512": "0b0e7fc90e23ab1839585a8fe68d89f6e66991eecbb33793798e4f1e02027f202be778d16b97a16fc1e27d0e2414744fe0e9f79b4b343eda4fff66f4e031607d",
          "sha256": "e80135b5e56cf3a9e69d15f38c40ce36455a7f39717bd4ffab657833a1d4a600",
          "sha1": "f7d4b008f16625bd0c19ff9f454e49e046a0fa39",
          "md5": "e230f40c04bffa9ab3f96c00f127c690"
        }
      ]
    }
  ]
}
