{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.0+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.22.1.316"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.0+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.0+mc1.21.1.jar",
          "size": 53343417,
          "sha512": "31691c02ecb11311ff389789ee5e96922626465cebde283336812161808abeaf6c11c7f5219c91db2aa6b91a16f56b04b72c74cc400cadaced0a930464319127",
          "sha256": "e654ab7c9269abb05178ef2a3ae8985dd103e7af0ffbdbfc1d22c62d5ae253c3",
          "sha1": "8381ff67a2416e799b489d9f802132d7b2322772",
          "md5": "54609e165c82f9bc7ad9dcccb879aca7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.0-Resharped-1.8.61"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.0+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.0+mc1.21.1.jar",
          "size": 53343417,
          "sha512": "31691c02ecb11311ff389789ee5e96922626465cebde283336812161808abeaf6c11c7f5219c91db2aa6b91a16f56b04b72c74cc400cadaced0a930464319127",
          "sha256": "e654ab7c9269abb05178ef2a3ae8985dd103e7af0ffbdbfc1d22c62d5ae253c3",
          "sha1": "8381ff67a2416e799b489d9f802132d7b2322772",
          "md5": "54609e165c82f9bc7ad9dcccb879aca7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.0+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.0+mc1.21.1-sources.jar",
          "size": 50205303,
          "sha512": "2524ca2a60de790fc3b8bef734ca1b94fb2a635f5e25335ea745b8f96d09b503731c73c1bd420a79476efad8754e20da2f8c300277a6667c3ce65235accc4b9f",
          "sha256": "1daec4edede35fbf113559ba4573c659f43a088257a206b6c16369f8547b0756",
          "sha1": "b4d94ce9103c3b9dbf49db3b2f95fe4e8e47f197",
          "md5": "348aa4d896c6d1a0c5456e36639c876c"
        }
      ]
    }
  ]
}
