{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.1.2+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.22.1.316"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.2+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.2+mc1.21.1.jar",
          "size": 6717582,
          "sha512": "8e62b513154bcd4d4944c4fb08f7fd0255df381bfe91e8b641125da22e8abf49f0a9f4ed7ecb70e0cda36ad67809a9814fdba95d5ba8b37a67f725e27e2d07ce",
          "sha256": "b636fc75be46618bab4614f10688837b7852c5935ae508f0b10474585f244593",
          "sha1": "474b368443134ef0a0a3ca39762f655a7d00821b",
          "md5": "bdc063923f688bac131686c52b03d41c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.0.1-Resharped-1.7.55"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.2+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.1.2+mc1.21.1.jar",
          "size": 6717582,
          "sha512": "8e62b513154bcd4d4944c4fb08f7fd0255df381bfe91e8b641125da22e8abf49f0a9f4ed7ecb70e0cda36ad67809a9814fdba95d5ba8b37a67f725e27e2d07ce",
          "sha256": "b636fc75be46618bab4614f10688837b7852c5935ae508f0b10474585f244593",
          "sha1": "474b368443134ef0a0a3ca39762f655a7d00821b",
          "md5": "bdc063923f688bac131686c52b03d41c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.1.2+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.1.2+mc1.21.1-sources.jar",
          "size": 3800123,
          "sha512": "54611feb283a9b96457c00aeed402f2252096dc18c714e00a46bd3484d0c87e6d8965618d9ef634fbe3dd84a3d38809258ebffe826a02453e6560bc048fe0b6c",
          "sha256": "8419f27dcdb26bf1c6108a2f54891aa7023f0568254835657415065fcc535c1a",
          "sha1": "e80d5592c7c16486e8725c59c0f10d9cde769ff9",
          "md5": "19f3628de819ac6f39653b7f4adee6b7"
        }
      ]
    }
  ]
}
