{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.20.1-1.3.3-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.3.3-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.20.1-1.3.3-Resharped-1.8.61.jar",
          "size": 7987671,
          "sha512": "7c62186198b9ffc37e0289f316e4c4051545ce9e46cad8954069fd3e0f54b88b3f50d9cd6dbb71d4c450f9399bbcc6f311f350511d86b93e794e85c2dba92f09",
          "sha256": "16634490fe6a35b9a2db20cff977029070cd6f1034126746a77f4e6f1d2eb8a2",
          "sha1": "684b1183da8138f5c4c3c7b1157470c4c21aba8f",
          "md5": "d862fe0ad57fe17851369235f3344722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "attributes",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "emi-580555",
          "version": {
            "requires": "6420944"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5.1-1.20.1-alpha-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "6815736"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6608232"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.105"
          }
        },
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "5180902"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "5984629"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-83-FABRIC"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.3.3-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.20.1-1.3.3-Resharped-1.8.61.jar",
          "size": 7987671,
          "sha512": "7c62186198b9ffc37e0289f316e4c4051545ce9e46cad8954069fd3e0f54b88b3f50d9cd6dbb71d4c450f9399bbcc6f311f350511d86b93e794e85c2dba92f09",
          "sha256": "16634490fe6a35b9a2db20cff977029070cd6f1034126746a77f4e6f1d2eb8a2",
          "sha1": "684b1183da8138f5c4c3c7b1157470c4c21aba8f",
          "md5": "d862fe0ad57fe17851369235f3344722"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.20.1-1.3.3-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.20.1-1.3.3-Resharped-1.8.61-sources.jar",
          "size": 3649105,
          "sha512": "d11db9b9993e92e48c95a2dcd18e91e105a7603b734df0a46ceea4c769b705ed633d8153c898c5957d93e61614c341f44eb38ec29eab78d7cc4f8736e039e5af",
          "sha256": "4136aa7b0a01fac215f0e48b8ec399aba036e56c5966f401a9a568f82a03db7c",
          "sha1": "1e8efcfae71579a50cce288dfda813966fe81dd7",
          "md5": "961f94c67078c90a28b240aacf2e40af"
        }
      ]
    }
  ]
}
