{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "recipe_book_categories",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "recipe_book_categories-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "recipe_book_categories-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 682456,
          "sha512": "095ebc224d3d1c9a62ff2facbc33ab165566e5e1f0e7625a15415e029e3f5f4ab7421895ca92f9f3c34e78be7c216bfc2139060bbd02110138f9a53ea01814f6",
          "sha256": "8cb700ccaaee7ea63f72a94ccf784585ae9ec06853dbd9278870affe480ef054",
          "sha1": "6fd756ca1213dc5776bf745c085855b4b0e019d3",
          "md5": "78e4c46326daf5ece0162a7aece1ad6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "recipe_book_categories-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "recipe_book_categories-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 682456,
          "sha512": "095ebc224d3d1c9a62ff2facbc33ab165566e5e1f0e7625a15415e029e3f5f4ab7421895ca92f9f3c34e78be7c216bfc2139060bbd02110138f9a53ea01814f6",
          "sha256": "8cb700ccaaee7ea63f72a94ccf784585ae9ec06853dbd9278870affe480ef054",
          "sha1": "6fd756ca1213dc5776bf745c085855b4b0e019d3",
          "md5": "78e4c46326daf5ece0162a7aece1ad6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recipe_book_categories-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "recipe_book_categories-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 5863,
          "sha512": "9af7942293c1c7734431938113b8953d99639536ee50bfba0a2066a3963dbe479169f627fbda670172675399ec7a929edb0613cac49cadc666a1f57d85ceb464",
          "sha256": "171f373c9a968ce8b7562b0140d8c518087a2670dfd068e37a358d0eb8db657c",
          "sha1": "2294b59e4d45ff12f6bcf4e1a2518370c4e5ec3e",
          "md5": "c07f962cef9756ae29d488b8b145ae77"
        }
      ]
    }
  ]
}
