{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "touhoulittlemaid-fabric-1.20.1",
    "version": "0.4.1-forge1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.4.1-forge1.4.5.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.4.1-forge1.4.5.jar",
          "size": 27108302,
          "sha512": "a4ec6cb123f9c805d83272978ab359698ff9af64ecf676dcb315525674884417ed8b4277555b24b13db7393a249cedee0ee44dadc7bff0c9a8462f5f912433f7",
          "sha256": "4516c90dc19785aa2619b4763cfe0e59ac23860c4996c8a6bf7d780bdc5f4533",
          "sha1": "2f543a8c42284e9ec23aab4a786a59459c43069b",
          "md5": "f3bdc2a4cfc1158eb6e877707b1af955"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "org.gagravarr",
          "module": "vorbis-java-core",
          "version": {
            "requires": "0.8"
          }
        },
        {
          "group": "io.github.jaredmdobson",
          "module": "concentus",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "libs",
          "module": "SlashBlade-Refabricated-1.20.1",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112-fabric"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.136"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "cyberanner-ironchest",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carry-on",
          "version": {
            "requires": "2.1.2.7-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patchouli",
          "version": {
            "requires": "1.20.1-84.1-fabric"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.4+kotlin.2.2.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "libipn",
          "version": {
            "requires": "fabric-1.20-4.0.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "inventory-profiles-next",
          "version": {
            "requires": "fabric-1.20.1-1.10.15"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "simple-hats",
          "version": {
            "requires": "SDPZOmWZ"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.16"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino-fabric",
          "version": {
            "requires": "2001.2.3-build.10"
          }
        },
        {
          "group": "net.conczin",
          "module": "immersive_melodies",
          "version": {
            "requires": "0.6.0+1.20.1+fabric"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Fabric-1.20.1",
          "version": {
            "requires": "1.0.83"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "kaleidoscope-cookery",
          "version": {
            "requires": "1.0.1-fabric+mc1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "improved-mobs",
          "version": {
            "requires": "1.20.1-1.13.6-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tenshilib",
          "version": {
            "requires": "1.20.1-1.7.6-fabric"
          }
        },
        {
          "group": "libs",
          "module": "TACZ-Refabricated-1.20.1",
          "version": {
            "requires": "0.0.7-forge1.1.6-hotfix"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "OFIAZVy7"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patpat",
          "version": {
            "requires": "1.2.1+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "proxlib",
          "version": {
            "requires": "0.2.4+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.cottonmc",
          "module": "LibGui",
          "version": {
            "requires": "8.1.1+1.20.1"
          }
        },
        {
          "group": "me.zeroeightsix",
          "module": "fiber",
          "version": {
            "requires": "0.23.0-SNAPSHOT"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-minimap",
          "version": {
            "requires": "25.2.10_Fabric_1.20"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-world-map",
          "version": {
            "requires": "1.39.12_Fabric_1.20"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.4.1-forge1.4.5.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.4.1-forge1.4.5.jar",
          "size": 27108302,
          "sha512": "a4ec6cb123f9c805d83272978ab359698ff9af64ecf676dcb315525674884417ed8b4277555b24b13db7393a249cedee0ee44dadc7bff0c9a8462f5f912433f7",
          "sha256": "4516c90dc19785aa2619b4763cfe0e59ac23860c4996c8a6bf7d780bdc5f4533",
          "sha1": "2f543a8c42284e9ec23aab4a786a59459c43069b",
          "md5": "f3bdc2a4cfc1158eb6e877707b1af955"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.4.1-forge1.4.5-sources.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.4.1-forge1.4.5-sources.jar",
          "size": 20363682,
          "sha512": "396d96f6d7294d57fecaefc4b09ea2c7507576714eb53766b1cdda833006dcc1ba3edb61bf5a733f37dedcddeb02437b11b3c182ece114b2fa567c8285e8c323",
          "sha256": "ebb8f90ad4e3e8db0573a122b658858baa668f4baf62eb66da0c81e2aac21e06",
          "sha1": "3af315a32bd601699d6a243c3962348f5c1be875",
          "md5": "f82980df12e983fb76ce79153d4e1ea5"
        }
      ]
    }
  ]
}
