{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.0+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.0+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.0+mc1.20.1.jar",
          "size": 52631615,
          "sha512": "cf25e73e70dbc8979d0c4f55e395b6d146a5d9435036164d82d1a124aa0766e3edb175be654e14936365db9ded952af942d50275d31c876ccce220fa15fa64be",
          "sha256": "71271b2e4e42bed69fce6d3617cbf985132b9d028dd36f84c8f38c29cc1b8f39",
          "sha1": "3c1a36729d64c8d48cb1080fb7ec8bf4036c61f2",
          "md5": "494369ba42da1d807a1b2811eb99a365"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.0-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.0+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.0+mc1.20.1.jar",
          "size": 52631615,
          "sha512": "cf25e73e70dbc8979d0c4f55e395b6d146a5d9435036164d82d1a124aa0766e3edb175be654e14936365db9ded952af942d50275d31c876ccce220fa15fa64be",
          "sha256": "71271b2e4e42bed69fce6d3617cbf985132b9d028dd36f84c8f38c29cc1b8f39",
          "sha1": "3c1a36729d64c8d48cb1080fb7ec8bf4036c61f2",
          "md5": "494369ba42da1d807a1b2811eb99a365"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.0+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.0+mc1.20.1-sources.jar",
          "size": 50196157,
          "sha512": "9cc774cfeb3907dcbe539b849f5cd4cabe8f5cfff944eba626dbe9c895a3d195b1ddf4a0adea7f137f4a2d910fd4bd2c53a96abe1d9fb08aeaf9e573b085bd3f",
          "sha256": "ba71db489be2c165104fd5690dd24da202a3acdff9dc499601e41f571ecad41c",
          "sha1": "ae38f2ce5423b93f7246a9c7c51c797337f13950",
          "md5": "d7ee9a3401486070f9ff287ae2dcb6e8"
        }
      ]
    }
  ]
}
