{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.10+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.10+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.10+mc1.21.1.jar",
          "size": 50855571,
          "sha512": "d46e142fb55be6fb8df90ddc9a0b51b8fb0decab9a9fc55c70def3f28c61273588f50b6734c6635dac64d397e9d7fd7d0bfec4181d523d08d8da2dfc11975703",
          "sha256": "380d687db79c01ad91be90b8ad4c87581683f9a280682b06c8f491874ba32173",
          "sha1": "9f1156c745827791d839c3073b77b7ec67f0ffc1",
          "md5": "fc704ed19b51e1fafdad1fdb99792c1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.4-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.10+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.10+mc1.21.1.jar",
          "size": 50855571,
          "sha512": "d46e142fb55be6fb8df90ddc9a0b51b8fb0decab9a9fc55c70def3f28c61273588f50b6734c6635dac64d397e9d7fd7d0bfec4181d523d08d8da2dfc11975703",
          "sha256": "380d687db79c01ad91be90b8ad4c87581683f9a280682b06c8f491874ba32173",
          "sha1": "9f1156c745827791d839c3073b77b7ec67f0ffc1",
          "md5": "fc704ed19b51e1fafdad1fdb99792c1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.10+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.10+mc1.21.1-sources.jar",
          "size": 50564977,
          "sha512": "18a9bc7f071bac48dc1b2c8e1e6d2ec2414cdffedeb67a6ff9804760fe3810edc981638c68648243bd52cd42848078238c8d9a728062dc25e21e42638507f0eb",
          "sha256": "7279c3ec5ed8b4c602917134c4aa738eb449923a3946ab1737c4e260f8dc4b35",
          "sha1": "13d4ba2d93f502a13ee63b3c09a3043772e89a11",
          "md5": "d5b26c8ca8a30d2d26d90d930cc27968"
        }
      ]
    }
  ]
}
