{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.7+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.7+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.7+mc1.20.1.jar",
          "size": 52633166,
          "sha512": "de326b472a9c29c992d2d443d5e77de7788a52f4764f4e7ee5989c2176946d8ebe24da3ec468acd6cff6ff4e9dab8a38f5a6f1ff382cf59abf86c616ab37374a",
          "sha256": "e5af37a9fdd89c1297a4550b3fe21230728b87c7e1e0aafc0387be5aac61e167",
          "sha1": "bb1d7d6131ac4e5f43ae976c3ba0dc08adefa2a4",
          "md5": "be4c550dea8814767dbe9862651513fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.3-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.7+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.7+mc1.20.1.jar",
          "size": 52633166,
          "sha512": "de326b472a9c29c992d2d443d5e77de7788a52f4764f4e7ee5989c2176946d8ebe24da3ec468acd6cff6ff4e9dab8a38f5a6f1ff382cf59abf86c616ab37374a",
          "sha256": "e5af37a9fdd89c1297a4550b3fe21230728b87c7e1e0aafc0387be5aac61e167",
          "sha1": "bb1d7d6131ac4e5f43ae976c3ba0dc08adefa2a4",
          "md5": "be4c550dea8814767dbe9862651513fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.7+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.7+mc1.20.1-sources.jar",
          "size": 50197256,
          "sha512": "a573d80e4bb6847fc9d15c8fe4d922e4ce0974bc2e25df560d698472856fb7b1b148d0cf23cefcab6d8e516d13d54a8fc235bb5d9d28093562631e2c96bea4de",
          "sha256": "397f6fcee0c565fac2b18750bcccbb910bb8e0cf1ecfc04c1a1a42f2a7d20039",
          "sha1": "edda8775246a1b5a5b5c6dfc5d789ee315c817b0",
          "md5": "9b26a19c0cd39b8fe8e0cd539e154805"
        }
      ]
    }
  ]
}
