{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.1.3-Resharped-1.8.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.3-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.3-Resharped-1.8.60.jar",
          "size": 7134224,
          "sha512": "aa0f83a5e7cc740fd9fbff984432b2db29e54050aeaaa20e454e40da1bdcd835e075f5e2ca59581854dd3c52b0a2f542ac13b81a85e67a76108b9cc6c77c9e86",
          "sha256": "dd81ea8727497b132ce2d1fcec37872b1054d0de806cceb26b60c1c1d85d2c83",
          "sha1": "617da724269530346d8e3af0984b4e46d1fbce73",
          "md5": "e518e977dccb140b29c0368f059f72b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "items",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "3.1.0-beta.75+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-fabric",
          "version": {
            "requires": "1.1.10+1.21"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.3-Resharped-1.8.60.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.3-Resharped-1.8.60.jar",
          "size": 7134224,
          "sha512": "aa0f83a5e7cc740fd9fbff984432b2db29e54050aeaaa20e454e40da1bdcd835e075f5e2ca59581854dd3c52b0a2f542ac13b81a85e67a76108b9cc6c77c9e86",
          "sha256": "dd81ea8727497b132ce2d1fcec37872b1054d0de806cceb26b60c1c1d85d2c83",
          "sha1": "617da724269530346d8e3af0984b4e46d1fbce73",
          "md5": "e518e977dccb140b29c0368f059f72b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.1.3-Resharped-1.8.60-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.1.3-Resharped-1.8.60-sources.jar",
          "size": 3555877,
          "sha512": "43d69a8a4ad3b722a0d28720c4c3af919a66eecad70e5618b1a06950da9bb228bd34358e3d3be022c08d6dda00010daf66957c3bb2e52ac732e9a20edc0cd2f3",
          "sha256": "c4e1d7ad892eb4e270f0bd58b27d68cc22b61cd2216b1afe57fa5873a50ef566",
          "sha1": "d936595923bc0c4802f6c1296c476a2e2cf10318",
          "md5": "c8e232cf3d0db6d25be1f69f75b98b22"
        }
      ]
    }
  ]
}
