{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.8+mc1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.8+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.8+mc1.20.1.jar",
          "size": 52633185,
          "sha512": "d5104748342ea48dc018cbeb8393c47cbf0636d1e74ad97c6f1d5885f599788cf71bde942922eee8bc231819a59334cc5585d80bc99808307f33cf8dffc9902a",
          "sha256": "7e54acec60a544eaf73d8008f9f25afc7fda67cd7411e71752e7fd2d56e83a15",
          "sha1": "cefd9289898072cafe09016f6acebc03896ac0d9",
          "md5": "27a426c12f5d30479a257b40cd15f9e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.20.1-1.3.4-Resharped-1.8.61"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-forge1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.botania",
          "module": "Botania",
          "version": {
            "requires": "1.20.1-446-FABRIC"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.20.1-84-FABRIC"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "1.0.2-rc1+1.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6837712"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.8+mc1.20.1.jar",
          "url": "slashblade-fabric-addons-1.2.8+mc1.20.1.jar",
          "size": 52633185,
          "sha512": "d5104748342ea48dc018cbeb8393c47cbf0636d1e74ad97c6f1d5885f599788cf71bde942922eee8bc231819a59334cc5585d80bc99808307f33cf8dffc9902a",
          "sha256": "7e54acec60a544eaf73d8008f9f25afc7fda67cd7411e71752e7fd2d56e83a15",
          "sha1": "cefd9289898072cafe09016f6acebc03896ac0d9",
          "md5": "27a426c12f5d30479a257b40cd15f9e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.8+mc1.20.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.8+mc1.20.1-sources.jar",
          "size": 50197276,
          "sha512": "5de6733e00fc6e6753b26437016d9021ad7575d135547be847f8bcc42425ab063119cd360851d371370d9bc5c45942006346af847a56276386a75afb21683589",
          "sha256": "e462337a7f2535d9bb47a626884a4bd5b8b2e40155175a9bc3f488e039ec36f7",
          "sha1": "e4a16d7079756a3762cbd2e482d8c955c54bd903",
          "md5": "d0f26896a9bf59ff255e75c816f624fe"
        }
      ]
    }
  ]
}
