{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "entity",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 994273,
          "sha512": "a9b03e253d193fc62a7a9453ebf1c79ec1fc07b1d01fcedb1928ecad2602a3fea5fb9c1e6d9c48b7bd6bb6a9ce0131eacbb0b47a9c7b3fea359835449c322d80",
          "sha256": "51ffa48fc8552f2beeb1b160f194938737f05d3e6f283936c357c72111e552a9",
          "sha1": "8e59a80b929f3632e6fdc848f69c4f4c188e558a",
          "md5": "e746f5b92a03857a4e27244d6c9ee375"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 994273,
          "sha512": "a9b03e253d193fc62a7a9453ebf1c79ec1fc07b1d01fcedb1928ecad2602a3fea5fb9c1e6d9c48b7bd6bb6a9ce0131eacbb0b47a9c7b3fea359835449c322d80",
          "sha256": "51ffa48fc8552f2beeb1b160f194938737f05d3e6f283936c357c72111e552a9",
          "sha1": "8e59a80b929f3632e6fdc848f69c4f4c188e558a",
          "md5": "e746f5b92a03857a4e27244d6c9ee375"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "entity-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 139014,
          "sha512": "4ba42430309d663decfda82051487afafeb7f5776e0bfacec28a0078cfed138105dd5f1c115ce7879b1e23d0cd31af6510628aa6f3ab3a89b7cfe5dbf3e7a5c6",
          "sha256": "19a98546f1615907adee4a629e153bc5c046ab539474a3159494c4fd4a74e800",
          "sha1": "e06d35dfc5deff1339fc9e0806812be1299af1d0",
          "md5": "949a242bbcddcc0ef3ede91cb57eefc7"
        }
      ]
    }
  ]
}
