{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "entity",
    "version": "3.1.0-beta.79-fix+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 994273,
          "sha512": "5fc530f5ed8e5492d4c6a5bee2e85cfe4a685355123bd71534f1e577aa846370f399a70e05a154c7f01514e2502f95e8491bc2eded28d723de3f412bbc0542d2",
          "sha256": "3bf0bdbd068f76eaffb3293f7528becdbb7d6e17359e38044aee51cdb8bd1c42",
          "sha1": "6cb3693f47291f8f96ef396a46df9c53f281c3b0",
          "md5": "7c24ce3e7a2f8b7222be427a602dd875"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "url": "entity-3.1.0-beta.79-fix+1.21.1.jar",
          "size": 994273,
          "sha512": "5fc530f5ed8e5492d4c6a5bee2e85cfe4a685355123bd71534f1e577aa846370f399a70e05a154c7f01514e2502f95e8491bc2eded28d723de3f412bbc0542d2",
          "sha256": "3bf0bdbd068f76eaffb3293f7528becdbb7d6e17359e38044aee51cdb8bd1c42",
          "sha1": "6cb3693f47291f8f96ef396a46df9c53f281c3b0",
          "md5": "7c24ce3e7a2f8b7222be427a602dd875"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "url": "entity-3.1.0-beta.79-fix+1.21.1-sources.jar",
          "size": 139014,
          "sha512": "75d484b6c0ba2d7607b372370080d702fbd55ff88bc2eaa4cfc53c66ca3932ae9c18abbef87c3741d35ff549d1800079f5791c32cfe528bbe0bc8b08a374b619",
          "sha256": "a0fcca5dc58a2a6eaf11c2e4b801895489a975bde9ab0987e03ab136146cf79f",
          "sha1": "9c97ca64441c3cf2dfbc96c39cfb09998fd4d793",
          "md5": "9eff24fa03cc2d0d00b9a9ceb436254a"
        }
      ]
    }
  ]
}
