{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.6+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.6+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.6+mc1.21.1.jar",
          "size": 50855505,
          "sha512": "6017f63b9a81d25350e5ea28601c74dcac50693497b520845b2e0b6ab03b83dcfeec3d5a059bd2390add1e04e32cfabc1c3f4a783afc78f730890de1608f43ca",
          "sha256": "75a59b4a64f84682cf281c5e715b7cbb15793aaacdd07724f841f29c416c807f",
          "sha1": "fb92def224bd86ddadfd5ffcd240eebc317989a3",
          "md5": "f3230c7e78c97f80e963f706045d87d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.3-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.6+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.6+mc1.21.1.jar",
          "size": 50855505,
          "sha512": "6017f63b9a81d25350e5ea28601c74dcac50693497b520845b2e0b6ab03b83dcfeec3d5a059bd2390add1e04e32cfabc1c3f4a783afc78f730890de1608f43ca",
          "sha256": "75a59b4a64f84682cf281c5e715b7cbb15793aaacdd07724f841f29c416c807f",
          "sha1": "fb92def224bd86ddadfd5ffcd240eebc317989a3",
          "md5": "f3230c7e78c97f80e963f706045d87d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.6+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.6+mc1.21.1-sources.jar",
          "size": 50564891,
          "sha512": "9f266f974d385dd9cb72c900fcbe1a734afc124da86dd397e24a76649cbd623ac7371abf49944b70a1e85a39a55fde5c2ab1f222ba7573087893f157fc082456",
          "sha256": "d77b40620bf408d641dfeef540bac330a4829fc7f542ac73f118ee707b1888b6",
          "sha1": "b00a1e15ce0ab7f92b0e5f0c1d979fe374a2a1b4",
          "md5": "bb23afebc8b651b2a3d29571acbfed28"
        }
      ]
    }
  ]
}
