{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "tlmo-additions",
    "version": "1.0.0+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tlmo-additions-1.0.0+mc1.21.1.jar",
          "url": "tlmo-additions-1.0.0+mc1.21.1.jar",
          "size": 450957,
          "sha512": "694acc77a6b7efda8f44c9d5ba818004479161d0c7162f3cc72942a2f4205397984b9f09c35a6bc57a5d0729b5ef9e91072d437dc8cfaf9d97b9e789ea1a2d1d",
          "sha256": "c35642aef36a918bd0f2b2101f8a8188780a07277d85713f8395927faa866e67",
          "sha1": "0fcc7eead89842f836345ef0b95ae4995d79f58a",
          "md5": "b43cf477733e21dac16c6902372d63b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.9+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.6.2-neo1.5.0"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "cn.sh1rocu",
              "module": "slashblade-refabricated"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "explorers-compass-491794",
          "version": {
            "requires": "5696038"
          }
        },
        {
          "group": "curse.maven",
          "module": "natures-compass-252848",
          "version": {
            "requires": "5756913"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.128"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "tlmo-additions-1.0.0+mc1.21.1.jar",
          "url": "tlmo-additions-1.0.0+mc1.21.1.jar",
          "size": 450957,
          "sha512": "694acc77a6b7efda8f44c9d5ba818004479161d0c7162f3cc72942a2f4205397984b9f09c35a6bc57a5d0729b5ef9e91072d437dc8cfaf9d97b9e789ea1a2d1d",
          "sha256": "c35642aef36a918bd0f2b2101f8a8188780a07277d85713f8395927faa866e67",
          "sha1": "0fcc7eead89842f836345ef0b95ae4995d79f58a",
          "md5": "b43cf477733e21dac16c6902372d63b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tlmo-additions-1.0.0+mc1.21.1-sources.jar",
          "url": "tlmo-additions-1.0.0+mc1.21.1-sources.jar",
          "size": 267363,
          "sha512": "bffb7f57c2cc2cc366a92b6eeda569c1f351b91e62f055788adf16042488f01b049f8120f2685e3df6d36be8a1e04746057a38333a28f320c943380e72de6638",
          "sha256": "95a7ff54f244df8879f79dc76847126e6c1ac8a107b5cbb65f08fbbc9cd3a3c5",
          "sha1": "9e4b685e7cebd745f0e19c2bce45bdd47d452f4e",
          "md5": "2afdb46864aada29ade2c0001cfe8df3"
        }
      ]
    }
  ]
}
