{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-refabricated",
    "version": "1.21.1-1.3.4-Resharped-1.8.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.4-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.4-Resharped-1.8.61.jar",
          "size": 8548487,
          "sha512": "5257fcda7873ebe519688d99fb0ee7b8475978eeda71baef5dd54c850f852c47a6250a0168642c5bf5a3228c31b53b8f472ca46f8233b3c6a9fcc049eb790649",
          "sha256": "bb8b46f6bb5bc555c3bd3546f89f85cfdac646558617e17f579f35a5475773a8",
          "sha1": "7165a1f450bbef9a0a254fdc5f66f7a5ccdfa648",
          "md5": "8125dd3ba24e630330bd396444ba3cb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "21.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "accrelatedrendering-refabricated",
          "version": {
            "requires": "1.0.5-1.21.1-fabric.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "selene-499980",
          "version": {
            "requires": "7068423"
          }
        },
        {
          "group": "curse.maven",
          "module": "mmmmmmmmmmmm-225738",
          "version": {
            "requires": "6826532"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.22.1.316"
          }
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "curse.maven",
          "module": "nbtedit-reborn-678133",
          "version": {
            "requires": "6125442"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.4-Resharped-1.8.61.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.4-Resharped-1.8.61.jar",
          "size": 8548487,
          "sha512": "5257fcda7873ebe519688d99fb0ee7b8475978eeda71baef5dd54c850f852c47a6250a0168642c5bf5a3228c31b53b8f472ca46f8233b3c6a9fcc049eb790649",
          "sha256": "bb8b46f6bb5bc555c3bd3546f89f85cfdac646558617e17f579f35a5475773a8",
          "sha1": "7165a1f450bbef9a0a254fdc5f66f7a5ccdfa648",
          "md5": "8125dd3ba24e630330bd396444ba3cb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-refabricated-1.21.1-1.3.4-Resharped-1.8.61-sources.jar",
          "url": "slashblade-refabricated-1.21.1-1.3.4-Resharped-1.8.61-sources.jar",
          "size": 3556379,
          "sha512": "c0b5be85d9a6d731df4254349a5dd68bf396c3bc4158838bc33962a042e18d8eb6e3930c2888f85ed42e7df0ce4ae8d031dd191e038fe5b5e93b01b052bfcb24",
          "sha256": "7a93671ffc9baffb1f32fc25175f623d17d61eef67d9b2a2310831fc1f224fc2",
          "sha1": "ac06419cfaad416423002af227dc3db9552e55b9",
          "md5": "7b11b76f9e182f7724bca108dce18629"
        }
      ]
    }
  ]
}
