{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "touhoulittlemaid-fabric-1.20.1",
    "version": "0.6.4-forge1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0.jar",
          "size": 28028828,
          "sha512": "b9d92ac81e3b0395f85ebd9d796106ebba2fd578f4270574f8c41675a2387da833e89995233b9e656d9b26d6bafd4e3b1e949e8ba72a6086c64a12272bcd26d9",
          "sha256": "7b2b9730f71c67d647fc5f12b816cfe5f6f17ac1f278b74682c4fe96ecf31f33",
          "sha1": "129107f3cbdf3a54db28611533c3a91f3dd53d95",
          "md5": "dbaf28919444a45a817b6816631acbfd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-core",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "com.github.FiguraMC.luaj",
          "module": "luaj-jse",
          "version": {
            "requires": "3.0.8-figura"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.6.1"
          },
          "excludes": [
            {
              "group": "org.apache.commons",
              "module": "commons-lang3"
            }
          ]
        },
        {
          "group": "org.gagravarr",
          "module": "vorbis-java-core",
          "version": {
            "requires": "0.8"
          }
        },
        {
          "group": "io.github.jaredmdobson",
          "module": "concentus",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "libs",
          "module": "SlashBlade-Refabricated-1.20.1",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-item",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112-fabric"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.136"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "jade",
          "version": {
            "requires": "11.13.1+fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "cyberanner-ironchest",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carry-on",
          "version": {
            "requires": "2.1.2.7-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patchouli",
          "version": {
            "requires": "1.20.1-84.1-fabric"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.13.4+kotlin.2.2.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "libipn",
          "version": {
            "requires": "fabric-1.20-4.0.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "inventory-profiles-next",
          "version": {
            "requires": "fabric-1.20.1-1.10.15"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "simple-hats",
          "version": {
            "requires": "SDPZOmWZ"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.16"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "rhino-fabric",
          "version": {
            "requires": "2001.2.3-build.10"
          }
        },
        {
          "group": "net.conczin",
          "module": "immersive_melodies",
          "version": {
            "requires": "0.6.0+1.20.1+fabric"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Fabric-1.20.1",
          "version": {
            "requires": "1.0.83"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "kaleidoscope-cookery-refabricated",
          "version": {
            "requires": "1.2.0-fabric+mc1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "improved-mobs",
          "version": {
            "requires": "1.20.1-1.13.6-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "tenshilib",
          "version": {
            "requires": "1.20.1-1.7.6-fabric"
          }
        },
        {
          "group": "libs",
          "module": "TACZ-Refabricated-1.20.1",
          "version": {
            "requires": "0.0.7-forge1.1.6-hotfix"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "OFIAZVy7"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "common",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.8+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "patpat",
          "version": {
            "requires": "1.2.1+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "proxlib",
          "version": {
            "requires": "0.2.4+1.20.1"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "fabric-permissions-api",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "vectorwing",
          "module": "FarmersDelight",
          "version": {
            "requires": "1.20.1-2.4.1+refabricated"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "common-network",
          "version": {
            "requires": "1.0.5-1.20.1-fabric"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "just-more-cakes",
          "version": {
            "requires": "1.18.1-fabric,1.20.1"
          }
        },
        {
          "group": "io.github.cottonmc",
          "module": "LibGui",
          "version": {
            "requires": "8.1.1+1.20.1"
          }
        },
        {
          "group": "me.zeroeightsix",
          "module": "fiber",
          "version": {
            "requires": "0.23.0-SNAPSHOT"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-minimap",
          "version": {
            "requires": "25.2.10_Fabric_1.20"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "xaeros-world-map",
          "version": {
            "requires": "1.39.12_Fabric_1.20"
          }
        }
      ],
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0.jar",
          "size": 28028828,
          "sha512": "b9d92ac81e3b0395f85ebd9d796106ebba2fd578f4270574f8c41675a2387da833e89995233b9e656d9b26d6bafd4e3b1e949e8ba72a6086c64a12272bcd26d9",
          "sha256": "7b2b9730f71c67d647fc5f12b816cfe5f6f17ac1f278b74682c4fe96ecf31f33",
          "sha1": "129107f3cbdf3a54db28611533c3a91f3dd53d95",
          "md5": "dbaf28919444a45a817b6816631acbfd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0-shadow.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0-shadow.jar",
          "size": 23381887,
          "sha512": "1ccead676658b43c4947c0912c858848c78dd14e1a10d73bd635d5d432e1a502975f208da023b9efbb768e208e3179a65803609ae70e3a9f76fe45d588cd6b36",
          "sha256": "eefea22cad976f6b0a50a9e8fb0b2ce46caac1d658eb9368b2bbb1566daf7516",
          "sha1": "d606df3f36d047e4605d22ff7a8d6800b45e3378",
          "md5": "90d2435fc4fe79005e56c1ff04ca4e30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0-sources.jar",
          "url": "touhoulittlemaid-fabric-1.20.1-0.6.4-forge1.5.0-sources.jar",
          "size": 21255604,
          "sha512": "533baa96753f1638f138017272139cf5fb65ce735d28e27ad23250ac59e9bddb448351b3dea0bdb832403260490e48b33ed06e09c14f18586c274258047a3c5e",
          "sha256": "390bd3c64b44be4090d3ec5570fc11c997f47ba5e39da08edff18057430483e5",
          "sha1": "d1b8fcba80d64e53b4eb4304c43f7c56a550c962",
          "md5": "e907f1f5823972ed959ede6137f32a9f"
        }
      ]
    }
  ]
}
