{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sh1rocu",
    "module": "slashblade-fabric-addons",
    "version": "1.2.9+mc1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-common-api",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric-api",
          "version": {
            "requires": "19.27.0.340"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.9+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.9+mc1.21.1.jar",
          "size": 50855570,
          "sha512": "d2e2f74f974553cad066f4b1fb55dd68902b1391c90bd5a37f650466919354f78a2d69e07961079da0707b673185781daa2c2ace34aef31536c700a0ab947b9d",
          "sha256": "a8878bb93185ea830688cfc01da60fc21bfa45d6efccbd883df75fc816b43e56",
          "sha1": "59531ebfe9a38115c38e5a9ca5fd07a2fbe0cec2",
          "md5": "ec1fae40073327865ddcac71617414ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "slashblade-refabricated",
          "version": {
            "requires": "1.21.1-1.3.4-Resharped-1.8.61"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "all",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "cn.sh1rocu",
          "module": "touhoulittlemaid-fabric-1.21.1",
          "version": {
            "requires": "0.5.1-neo1.4.6"
          },
          "excludes": [
            {
              "group": "libs",
              "module": "*"
            },
            {
              "group": "net.conczin",
              "module": "*"
            }
          ]
        },
        {
          "group": "vazkii.patchouli",
          "module": "Patchouli",
          "version": {
            "requires": "1.21-87-FABRIC"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-fabric",
          "version": {
            "requires": "19.27.0.340"
          }
        },
        {
          "group": "dev.kosmx.player-anim",
          "module": "player-animation-lib-fabric",
          "version": {
            "requires": "2.0.1+1.21.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "modernfix-790626",
          "version": {
            "requires": "6766123"
          }
        }
      ],
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.9+mc1.21.1.jar",
          "url": "slashblade-fabric-addons-1.2.9+mc1.21.1.jar",
          "size": 50855570,
          "sha512": "d2e2f74f974553cad066f4b1fb55dd68902b1391c90bd5a37f650466919354f78a2d69e07961079da0707b673185781daa2c2ace34aef31536c700a0ab947b9d",
          "sha256": "a8878bb93185ea830688cfc01da60fc21bfa45d6efccbd883df75fc816b43e56",
          "sha1": "59531ebfe9a38115c38e5a9ca5fd07a2fbe0cec2",
          "md5": "ec1fae40073327865ddcac71617414ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slashblade-fabric-addons-1.2.9+mc1.21.1-sources.jar",
          "url": "slashblade-fabric-addons-1.2.9+mc1.21.1-sources.jar",
          "size": 50564958,
          "sha512": "ac21bbb3b244c430ae8e5327d3deb05fb3ce748bd3c64ca90bbe8b3ca207b26a0edc1805eadaa3a382901e41c163446beccb0b1d0b603c089c37873588bce179",
          "sha256": "7ebb43998a07f7edbb0f7a939884b3893960c455600154755d1ae7961d5e320c",
          "sha1": "cf879605caa6fd02695fca34199277b721200ecf",
          "md5": "9d53745663cf12dd96300139c1db37f1"
        }
      ]
    }
  ]
}
