{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "render_types",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "render_types-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "render_types-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 690453,
          "sha512": "4ac4a81930c36291f46bcc070cef3c6747e6c60c21825058ec6403839c771c9dfff3a49dbc69ff9fdae0d20a13c2053c4b4e6ca7c50ee6b382e5f9d9fc66110f",
          "sha256": "3db0c86213327f302d25e7fce9c5aab24507a081b81ea08dfba57b02c759932c",
          "sha1": "69900f66c37a796d6d75adfcb8938969fe10e407",
          "md5": "77b7992d6b20cdcc6956c894afc23932"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "render_types-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "render_types-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 690453,
          "sha512": "4ac4a81930c36291f46bcc070cef3c6747e6c60c21825058ec6403839c771c9dfff3a49dbc69ff9fdae0d20a13c2053c4b4e6ca7c50ee6b382e5f9d9fc66110f",
          "sha256": "3db0c86213327f302d25e7fce9c5aab24507a081b81ea08dfba57b02c759932c",
          "sha1": "69900f66c37a796d6d75adfcb8938969fe10e407",
          "md5": "77b7992d6b20cdcc6956c894afc23932"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "render_types-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "render_types-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 9907,
          "sha512": "cf3af7a1539543f74de8d7df41826474abd0ba71b43c6fa57017f7c9eb0cb2fe8783e18f30b114e058cf85d05af17155fee5db637440a7bfe1669091f5cc0a0b",
          "sha256": "390ce4dd2d1642f655b32997c70e53da3f7014d1d76feed55b1b3dd8a7eeceea",
          "sha1": "c4e6d7ba2ba05b9fd63cb8429ee2720e2cc597fe",
          "md5": "1ae34cddbecc769183e443423e94ca81"
        }
      ]
    }
  ]
}
