{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_loader",
    "version": "3.1.0-beta.79-fix+1.21.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        }
      ],
      "files": [
        {
          "name": "model_loader-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "model_loader-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 755202,
          "sha512": "cf3f387d00b6d20c48a5044b5d80d0180d99292a1c7c2742589db0a47d1b5dc3818a6dc5264689d604bf70da9e39984ae31f8443178e372707e19f29b421a09d",
          "sha256": "707b634605ff2206757a2202dadfd783de8f9512a9eee611112b13a40d62ee44",
          "sha1": "839db230b6bb01eaf84420be936c5619c4b34639",
          "md5": "175ebfaefd278f76a4352ba4b21ed0e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.5.0-rc.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "render_types",
          "version": {
            "requires": "3.1.0-beta.79-fix+1.21.1-fix"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "model_loader-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "url": "model_loader-3.1.0-beta.79-fix+1.21.1-fix.jar",
          "size": 755202,
          "sha512": "cf3f387d00b6d20c48a5044b5d80d0180d99292a1c7c2742589db0a47d1b5dc3818a6dc5264689d604bf70da9e39984ae31f8443178e372707e19f29b421a09d",
          "sha256": "707b634605ff2206757a2202dadfd783de8f9512a9eee611112b13a40d62ee44",
          "sha1": "839db230b6bb01eaf84420be936c5619c4b34639",
          "md5": "175ebfaefd278f76a4352ba4b21ed0e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_loader-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "url": "model_loader-3.1.0-beta.79-fix+1.21.1-fix-sources.jar",
          "size": 45293,
          "sha512": "46c49361fe6dfebdf90f65973eaa753946ccf2bda9a48d533988cdeacaddcd85596da1b205ef8b6aca5d610b2312291089295bc073082ce2a7c317f99f098d2c",
          "sha256": "76b7dae8657dbc85c359d7a24cb41ca065661957f610aeddd9d40b1c326b8df0",
          "sha1": "b4cd25343306187726f2f0e030002eb23b991bc8",
          "md5": "694f1d2d2ef75dbe2880758f5512763b"
        }
      ]
    }
  ]
}
